### ISSUE TITLE
Potential typos

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/browser-payment-api#1015]
Dear Sir and Madam

This is Shuji Kamitsuna@Japan.

I am translating the "Payment Request API" published on September 8, 2022.

I noticed some potential typos:
Sec. 3.1, Could "optionally letting" be "optionally informing"? (I'm not sure.)
Sec. 13.4, "If isRetry if false" might be "If isRetry is false".
Sec. 14.8, Is "available. purposes." the correct expression?

Best Regards,

**Comment by ianbjacobs** [comment]
@shujikamitsuna, thank you for the translation! And thank you for signaling these editorial issues. I've created a pull request #1016
