### ISSUE TITLE
Relax user activation requirement for show()

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#1025]
After #1021, we need to bring back this text: https://github.com/w3c/payment-request/commit/d9352e287aea631c322b4e3d94752ba59bcc78bb

CC @rsolomakhin, @stephenmcgruer

**Comment by rsolomakhin** [comment]
Oh, hi! What is the reasoning for doing this after https://github.com/w3c/payment-request/pull/1021 instead of keeping the "user activation requirement" unchanged?

**Comment by ianbjacobs** [comment]
See [related answer](https://github.com/w3c/payment-request/pull/1021#issuecomment-2107832273).
