### ISSUE TITLE
Need help with using Payment Request API with Apple Pay

### ISSUE THREAD

**Issue by baskarmib** [w3c/browser-payment-api#1035]
Hi, 
We are currently using Payment request API to enable Apple Pay on our website. Based on the methods suggested as part of the apple pay demo guide we are using the same code as mentioned in the guide. 
https://applepaydemo.apple.com/payment-request-api

Below is the sample code taken from the apple demo guide. 

 const paymentMethodData = [{
            "supportedMethods": "https://apple.com/apple-pay",
            "data": {
                "version": 3,
                "merchantIdentifier": "merchant.com.apdemo",
                "merchantCapabilities": [
                    "supports3DS"
                ],
                "supportedNetworks": [
                    "amex",
                    "discover",
                    "masterCard",
                    "visa"
                ],
                "countryCode": "US"
            }
        }];

While using the above code , we are getting the below error and the canMakePayment call is returning false on a Mac/iOS device.
![image](https://github.com/user-attachments/assets/11f3906d-28eb-4edf-860a-18414d09fbf0)

Any help to resolve this issue is appreciated.

**Comment by ianbjacobs** [comment]
Hi @baskarmib,

For this question I recommend reaching out directly to the [Apple developer forums](https://developer.apple.com/forums/). I think this is not a specification issue so I'm going to close it. (If we learn it's a spec issue we can reopen this.)
