### ISSUE TITLE
[Question] Native applications

### ISSUE THREAD

**Issue by AdaltonLeite** [w3c/browser-payment-api#1037]
Hi guys,

I would like to confirm with you a scenario about native applications using the Payment Request. 

We currently have web flows for our checkout and Android application flows developed with Kotlin. Does this api have any support for 100% native flows? Or can it only be used in a browser context?

**Comment by ianbjacobs** [comment]
@AdaltonLeite,

The Chromium implementation of Payment Request on Android supports native payment apps; see Google's [Android payment app developers guide](https://web.dev/articles/android-payment-apps-developers-guide).
