### ISSUE TITLE
Payment Instrument clarification

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#104]
The payment architecture document no longer uses the term payment instrument, but I think his is still a useful term to clarify.

I believe a Payment Application stores (or gives access to) Payment Instruments and furthermore a particular Payment Instrument might be able to be presented (or used) from multiple payments applications.

So for example a Payment Instrument defined as Visa Card Number 1234567890123456 might be able to be presented by a Browser Payment App supporting cards and also a Visa Payment Application (such as V.Me/Visa Checkout) and furthermore by another 3rd party wallet.

**Comment by ianbjacobs** [comment]
The architecture document uses the term "Payment Method Data". Are you saying that;
- You are ok with that term but the meaning needs clarification
- You are ok with the concept but would rather call it "Payment Instrument"
- Or something else. :)

Ian

**Comment by mattsaxon** [comment]
The distinction is that the Payment Instrument may be obscured in some way, e.g. tokenised, but it still relates to an underlying payment instrument. I think this needs to be made clearer and the term Payment Instrument is useful in addition to Payment Method Data.

Furthermore I think it would be useful to show some sort of model, e.g. Entity Relationship Diagram to show how Apps relate to Mediators to Instrument to Organisations etc.

**Comment by adrianhopebailie** [comment]
This might be partly addressed in the Payment Apps spec using a mechanism like that proposed by @rsolomakhin in https://github.com/w3c/browser-payment-api/issues/185#issuecomment-223047965

**Comment by adrianba** [comment]
This is a comment against the payment architecture document, which the group isn't pushing forward. I recommend that if this issue is still relevant that it be discussed in the context of the new architecture documents.

Since this doesn't impact Payment Request API, I am closing this issue.
