### ISSUE TITLE
Issue Prioritisation Explainer

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#105]
In an effort to assist with prioritisation and focus for the Working Group post FPWD, I've reviewed the current list of open issues (54 at time of writing)

So we can see the maturity of the documents, I've labelled issues where there is a clear specific document that they apply to as follows;

Document Labels:
["Doc:PaymentRequestAPIArchitecture"](https://github.com/w3c/browser-payment-api/labels/Doc%3APaymentRequestAPIArchitecture)
["Doc:PaymentRequestAPI"](https://github.com/w3c/browser-payment-api/labels/Doc%3APaymentRequestAPI)
["Doc:PaymentMethodIdentifers"](https://github.com/w3c/browser-payment-api/labels/Doc%3APaymentMethodIdentifiers)
["Doc:BasicCardPayment"](https://github.com/w3c/browser-payment-api/labels/Doc%3ABasicCardPayment)

Furthermore, I've categorised the issues into some broad categories based on the type of issue as follows;

Type Labels:
[General Editorial](https://github.com/w3c/browser-payment-api/labels/General%20Editorial)
[Native Support](https://github.com/w3c/browser-payment-api/labels/Native%20Support)
[Technical](https://github.com/w3c/browser-payment-api/labels/Technical)
[Security/Privacy](https://github.com/w3c/browser-payment-api/labels/Security%2FPrivacy)
[Extensibility/Versioning](https://github.com/w3c/browser-payment-api/labels/Extensibility%2FVersioning)
[Functionality](https://github.com/w3c/browser-payment-api/labels/Functionality)

Lastly, I've applied a priority to them as follows using milestones;

Milestones:
["Priority: High"](https://github.com/w3c/browser-payment-api/milestones/Priority:%20High)
["Priority: Medium"](https://github.com/w3c/browser-payment-api/milestones/Priority:%20Medium)
["Priority: Low"](https://github.com/w3c/browser-payment-api/milestones/Priority:%20Low)

I've assessed these priorities based partly on the "type", but also applied some more (personal) logic to this as below;

General Editorial: Low 
Native Support: Medium 
Technical: Mostly medium, some lows 
Security/Privacy: High 
Extensibility/Versioning: High 
Functionality: Varies 

Overall this gives us the following breakdown of categories at the time of writing;

Document Labels:
"Doc:PaymentRequestAPIArchitecture" 3
"Doc:PaymentRequestAPI"         3
"Doc:PaymentMethodIdentifers"       0
"Doc:BasicCardPayment"          3

Type Labels:
General Editorial               6
Native Support              1
Technical                       8
Security/Privacy                7
Extensibility/Versioning            14
Functionality                   20

Milestones:
"Priority: High"                    16
"Priority: Medium"              13
"Priority: Low"                     16

We can discuss at the WG meeting on Thursday how to interpret (and refine) this data.

**Comment by fredMeignien** [comment]
Thanks Matt, this classification grandly facilitates understanding and browsing of our state of the art.

**Comment by dlongley** [comment]
We might want labels based on elements from the payments architecture, like "Payment App", "Payment Mediator", etc.

**Comment by adrianhopebailie** [comment]
Thanks @mattsaxon for this. I have started triaging these and updating labels and priorities as I go.
