### ISSUE TITLE
Review and respond to Andrew Betts’ TAG review of the spec

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/browser-payment-api#118]
See https://github.com/w3ctag/spec-reviews/issues/109#issuecomment-204992438 from Andrew Betts @triblondon.

I think it may be that the editors or chairs might end up asking that Andrew file new issues for some of the suggestions in his review (beyond just the feedback that he is providing on some existing issues).

**Comment by adrianhopebailie** [comment]
I have responded to @triblondon and put his comments into new or existing issues:

Existing issue:
- https://github.com/w3c/browser-payment-api/issues/1
- https://github.com/w3c/browser-payment-api/issues/2
- https://github.com/w3c/browser-payment-api/issues/4
- https://github.com/w3c/browser-payment-api/issues/5
- https://github.com/w3c/browser-payment-api/issues/15
- https://github.com/w3c/browser-payment-api/issues/16
- https://github.com/w3c/browser-payment-api/issues/18
- https://github.com/w3c/browser-payment-api/issues/23

New issues:
- https://github.com/w3c/browser-payment-api/issues/121
- https://github.com/w3c/browser-payment-api/issues/122
- https://github.com/w3c/browser-payment-api/issues/127
- https://github.com/w3c/browser-payment-api/issues/128
