### ISSUE TITLE
Write-up initial proposal for payment app registration spec

### ISSUE THREAD

**Issue by adrianba** [w3c/browser-payment-api#12]
This issue comes from WICG/paymentrequest#27 and @zkoch proposed an [outline in the WICG repo](https://github.com/WICG/paymentrequest/blob/gh-pages/docs/registration.md).

**Comment by msporny** [comment]
Migrating payment app registration from Web Payments WG repo: https://github.com/w3c/webpayments/issues/14

There are a variety of approaches that can be used to register payment instruments:
- Browser API call
- Installed by OS Platform (Android Pay, Apple Pay)
- Software installation (Chase Visa Card App)

There is a proposal on how to do this here:

http://wicg.github.io/web-payments-browser-api/#payment-app-registration

**Comment by msporny** [comment]
Migrating from https://github.com/w3c/webpayments/issues/26:

The [Payment Request Architecture diagram](http://wicg.github.io/paymentrequest/specs/architecture.html#architecture) suggests that we split registration from payment. While I agree that the separation of concerns is good and helps both progress independently, I'm concerned that it also creates a very easy excuse for us to ignore the registration problem and may accidentally create an oligopoly in which the browsers and OS vendors control who can and can't register.

While I don't think any one of us wants to create an oligopoly, ignoring the registration problem is something that has a moderate chance of creating such an oligopoly. For example: "BigCorp requires all registering payment instruments to pass our payment instrument criteria (which, by the way, requires your payment instrument to have a total transaction volume of X, for you to pay us registration fees, and for your company to have existed for 10 years and have at least a millions of dollars in recurring revenue)".

So, if we split these specs, I'd only be okay if we commit to similar time frames.

To be clear, the registration process has several good technical approaches we could utilize:
1. Shared, centralized corporate community run registry.
2. Decentralized WebDHT-based mechanism.
3. Decentralized payment instruments as credentials.
4. Password-manager as registration vehicle (LastPass, etc.)

... and you can't do a payment until there is some registration process available (and polyfill-able).

Spec refs:
http://web-payments.github.io/web-payments-messaging/#payment-instrument-registration
http://wicg.github.io/web-payments-browser-api/#payment-instrument-registration
http://wicg.github.io/paymentrequest/specs/architecture.html#payment-method-registration-specifications
http://wicg.github.io/paymentrequest/specs/method-identifiers.html#issue-3

**Comment by ianbjacobs** [comment]
Personally I prefer that we publish some specifications in early April, while we continue to work on the registration specification.

Ian

**Comment by adrianhopebailie** [comment]
There is a proposal that includes among other things, registration of payment apps:
https://w3c.github.io/webpayments/proposals/paymentapps/payment-apps.html

**Comment by ianbjacobs** [comment]
I have also written down some notes on payment apps for this discussion.
 https://github.com/w3c/webpayments/wiki/PaymentApp_Notes

Ian

**Comment by adrianhopebailie** [comment]
This is being actively worked on by the Payment Apps task force chaired by @ianbjacobs.
The latest draft of the proposal is at https://w3c.github.io/webpayments/proposals/paymentapps/payment-apps.html
