### ISSUE TITLE
Update Introduction to describe actors better

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/browser-payment-api#121]
In TAG review @triblondon said:

> > three key parties in every transaction
> 
> These are cited as being the user, the merchant, and the payment method. However, a payment method is an instrument, not a party, surely? Wouldn't the party be the payment app provider? And is it necessary to acknowledge that in some cases the payment app provider may not be the same as the party with whom the merchant finalizes the transaction, especially in the case of a basic card payment?

The traditional model for payments is the "4-party" model and I think we'd do well to describe the architecture in this context. The architecture puts the user agent in the role of mediator between the payer (and their PSP - likely the payment app issuer) and the merchant (and possibly their PSP too).

**Comment by sideshowbarker** [comment]
Actually I think the issue description here is citing review comments made @triblondon in https://github.com/w3ctag/spec-reviews/issues/109#issuecomment-204992438

**Comment by rsolomakhin** [comment]
Agreed that "payment method" is not really a "party." However, I don't think PSPs should be mentioned in the browser payment API spec, because the browser is not communicating to PSPs directly. PSPs can be mentioned in the architecture overview document.
