### ISSUE TITLE
How can short payment method identifiers be successful

### ISSUE THREAD

**Issue by rvm4** [w3c/browser-payment-api#123]
The Payment Method Identifiers spec suggests that short identifiers should be possible for common payment methods. The canonical example being "visa". Perhaps I don't fully grasp the proposal, but I don't understand how the payment mediator or the merchant can achieve the end goal with "visa" as the only identification.

To my knowledge some processors require different details than others under different types of integrations. For instance sometimes just the credit card number, expiration and CVV are enough, whereas at other times a full address is also required. How are these differences in requirements meant to be handled?

Would the payment mediator supply all of the potentially useful information for all requests even when it is technically superfluous?

**Comment by rvm4** [comment]
Furthermore, if "visa" is the only designation provided, how would the payment mediator be able to determine equivalence between "visa" and some special payment app that ultimately returns credit card information, but has some special encryption or authentication or other secret sauce that sets it apart. I guess this gets into payment app registration, but I think its worth noting that the use of short-form identifiers that can map to more than one payment app will also necessitate registry of an app under more than one identifier.

**Comment by halindrome** [comment]
Hmm.  The payment method identifier "visa" would obviously need to map to a specific set of requirements.   You are correct that there are a plethora of payment methods that might map into the generic identifier "visa".  The WG would need to identify the specific requirements for the one that is named "visa".  

In reality, there are going to be a bazillion payment methods, identified by URIs.  As a merchant, my payment processor is going to tell me which identifiers I should use based upon what _they_ accept.  If we were smart, we would allow a payment method "profile" - a syntax that would magically dereference into a collection of accepted payment methods.  Then let the market sort out a bunch of profiles that are interesting.

**Comment by rvm4** [comment]
Okay, I just got into reading the current app registration proposal and it seems that this complexity is at least understood/anticipated:

https://w3c.github.io/webpayments/proposals/paymentapps/payment-apps.html
