### ISSUE TITLE
complete does not talk to the Payment App

### ISSUE THREAD

**Issue by AxelNennker** [w3c/browser-payment-api#129]
As discusses in issue https://github.com/w3c/browser-payment-api/issues/17 `complete()` does tell the UA that the payment is complete. It does not talk to the Payment App.
So step 5 should be removed.

```
Pass the value of <code>success</code> to the <a>Payment App</a> that accepted the payment request.
```

**Comment by adrianhopebailie** [comment]
Addressed by #161
