### ISSUE TITLE
BasicCardResponse: cardholderName should be optional.

### ISSUE THREAD

**Issue by Torlus** [w3c/browser-payment-api#134]
I see at least two cases where this field cannot be returned:
- In France, it is forbidden to provide such information, due to the CNIL rules about personal data and rights.
- Visa, MasterCard, and others provide Anonymous Prepaid Cards, making this information irrelevant.

**Comment by mattsaxon** [comment]
In my PR #114, I have indeed showed this as optional.

**Comment by adrianhopebailie** [comment]
Addressed in PR #114

**Comment by mattsaxon** [comment]
Adrian, that PR has not been accepted yet and I've in fact closed it awaiting resolution of PR 133 which changes the shape of how PR 114 will be done.

**Comment by adrianhopebailie** [comment]
Sorry, my mistake. I saw that @adrianba had merged #131 which included the same change but now see he picked only the one specific commit.

**Comment by mattsaxon** [comment]
PR #176 submitted to address

**Comment by adrianba** [comment]
Fixed in 9c32ebc5e797c3a83828d86bc397cd534032ec14.
