### ISSUE TITLE
General Comment on Registry Design

### ISSUE THREAD

**Issue by dret** [w3c/browser-payment-api#148]
it seems that https://www.w3.org/TR/2016/WD-payment-method-id-20160421/ is w3c's first attempt to create a registry. at https://tools.ietf.org/html/draft-wilde-registries i am writing generally about the pattern and design of registries, and maybe there is some interesting input. if you find anything missing from that document, please let me know.
generally speaking, it seems to me that following IETF's pattern of making the registry definition an integral part of the spec is better than having just a spec for the registry. after all, the spec and the registry are very much dependent on each other and none can live without the other, right?
i will make more specific comments on some issues about the current registry design in separate github issues.

**Comment by ianbjacobs** [comment]
@dret,

> it seems that https://www.w3.org/TR/2016/WD-payment-method-id-20160421/ is w3c's first attempt to create a registry.

It is true that we do not frequently do registries. But we have done some (e.g., xpointer registry).

If the IG decides to keep some form of registry of payment method specifications or identifiers,
then I agree we will need some sort of policy that explains how we manage the registry.
For example, there may be some payment method specs that the WG publishes, and others
that the community publishes and that we link to.

But that gets to the point of why, to my understanding, we do not generally create registries: the Web is the registry. If payment method specs flourish, then I would expect that W3C would not try to track all that exist, but would simply maintain a list of those published by the WG (and that might be found on w3.org/TR for example).

I look forward to your more detailed comments.

Ian
[1] https://www.w3.org/2005/04/xpointer-schemes/

**Comment by halindrome** [comment]
Just for completeness... there are several other "registries" maintained by the W3C:
- RDFa maintains an "initial context" in which CURIE prefixes are registered [1]
- There is a registry of "rel" values maintained for HTML5 [2]
- There is a collection of base "role" values for XHTML and HTML [3]
- There was a naming "model" for XHTML family markup languages and DOCTYPEs that defined a more distributed model for registering document types [4]
- The Role Attribute defines an extension mechanism that uses the web as registry, but requires dereferencable end-points [5]
- JSON-LD defines an arbitrary extension mechanism via dereferencable contexts - again using the web as the registry [6]

I am sure there are more.  That was off the top of my head (and things I have worked on).  

[1] https://www.w3.org/2011/rdfa-context/rdfa-1.1
[2] https://wiki.whatwg.org/wiki/RelExtensions
[3] https://www.w3.org/1999/xhtml/vocab
[4] https://www.w3.org/TR/2008/REC-xhtml-modularization-20081008/conformance.html#s_conform_naming_rules
[5] https://www.w3.org/TR/2013/REC-role-attribute-20130328/#extending-the-collection-of-roles
[6] https://www.w3.org/TR/json-ld/#the-context

**Comment by dret** [comment]
On 2016-04-21 14:12, ianbjacobs wrote:

> @dret https://github.com/dret,
>     it seems that
>     https://www.w3.org/TR/2016/WD-payment-method-id-20160421/ is w3c's
>     first attempt to create a registry.
> It is true that we do not frequently do registries. But we have done
> some (e.g., xpointer registry).

true, i am sorry for that oversight. it's just a little different from 
IETF where the overall count of registries now is close to 2000. so they 
have an established way how to handle this.

> If the IG decides to keep some form of registry of payment method
> specifications or identifiers,
> then I agree we will need some sort of policy that explains how we
> manage the registry.
> For example, there may be some payment method specs that the WG
> publishes, and others
> that the community publishes and that we link to.

exactly. https://tools.ietf.org/html/draft-wilde-registries is where i 
am currently writing up design consideration that everybody thinking 
about defining a registry might want to ask themselves.

> But that gets to the point of why, to my understanding, we do not
> generally create registries: the Web is the registry.

the web may be used as a platform to host/manage the registry, but it's 
not a registry. questions such as design guidelines/review, 
documentation requirements/review, naming conventions/constraints, 
discoverability, and of how to manage non-URI namespaces are all not 
addressed by the web. the web offers countless ways how to implement a 
registry, but at first the important questions are what the registry 
should manage and how it should be managed, and then one can decide on 
implementation options.

> If payment method
> specs flourish, then I would expect that W3C would not try to track all
> that exist, but would simply maintain a list of those published by the
> WG (and that might be found on w3.org/TR for example).

that's one of the interesting questions of any namespace managed via 
registry: discoverability and registration requirements. such as the 
question of whether there's a two-tier namespace used such as the one 
established by RFC 5988, with short names managed by a registry, and 
non-registered extensions being represented by URIs, which optionally 
may make some documentation available at their address.

**Comment by halindrome** [comment]
This is great information.  Thanks so much for your insight!

**Comment by dret** [comment]
On 2016-04-21 16:04, Shane McCarron wrote:

> Just for completeness... there are several other "registries" maintained
> by the W3C:
> [1] https://www.w3.org/2011/rdfa-context/rdfa-1.1
> [2] https://wiki.whatwg.org/wiki/RelExtensions
> [3] https://www.w3.org/1999/xhtml/vocab
> [4]
> https://www.w3.org/TR/2008/REC-xhtml-modularization-20081008/conformance.html#s_conform_naming_rules
> [5]
> https://www.w3.org/TR/2013/REC-role-attribute-20130328/#extending-the-collection-of-roles
> [6] https://www.w3.org/TR/json-ld/#the-context

sorry for the off-topic remark: that's a very useful list and the W3C 
should have a place where it is published. IETF/IANA with their ~2000 
registries may play in a different league here, but it seems to me that 
any org managing evolving registries of values should have some place 
where people can find out about which ones are available. a registry of 
registries (pardon the pun).

http://www.iana.org/assignments/

**Comment by adrianhopebailie** [comment]
There doesn't appear to be any further discussion required here. Thanks @dret for the helpful insights.

If there are concrete spec changes proposed on the back of this information please submit these as a PR.
