### ISSUE TITLE
Registry Access/Handling Registry Change

### ISSUE THREAD

**Issue by dret** [w3c/browser-payment-api#151]
why is the model that "registry snapshots" are created at odd URIs such as v1 and v2 and v3? it seems more logical, in case the idea is to allow machine-based access to the registry (which in itself is a tough design issue https://tools.ietf.org/html/draft-wilde-registries-01#section-5.5), that registry contents can always be retrieved, and represent the current status of the registry.
the registry should be designed in a way that (a) identifier semantics never change, and (b) there is a way to mark identifiers as being deprecated, so that in the worst case scenario, snapshots fail to correctly reflect a deprecated value.
this would allow developers to at least easily check if and how the registry has changed, and they would have an easy way how to review those changes, and possibly update their implementations to support the changes in the registry.

**Comment by ianbjacobs** [comment]
I propose that W3C not create a registry for payment method identifiers other than those that it mints via its own specifications.

Ian

**Comment by dret** [comment]
On 2016-05-17 10:50, ianbjacobs wrote:

> I propose that W3C not create a registry for payment method identifiers
> other than those that it mints via its own specifications.

but than that's still a registry only with a policy that only 
w3c-produced specs will be allowed, right? that's definitely one way to go.

the question then is: what's the idea of how other payment identifiers 
can be discovered. "not at all" is one possible answer to that, 
something along the lines of:

"Payment Methods defined by W3C specifications will be registered in the 
registry. Other payment methods may be defined and made identifiable via 
payment method identifiers by non-W3C bodies, but this specification 
makes no assumptions about how identifiers for those will be minted, or 
how they can be discovered."

**Comment by ianbjacobs** [comment]
> Other payment methods may be defined and made identifiable via payment method identifiers by non-W3C bodies, but this specification makes no assumptions about how identifiers for those will be minted, or how they can be discovered."

We could say that in the spec. But I think saying nothing in the spec is equivalent.

Ian

**Comment by dret** [comment]
> We could say that in the spec. But I think saying nothing in the spec is
> equivalent.

sometimes being explicit about "saying nothing" is more helpful than 
leaving it to exegesis later on. but technically you're right.

**Comment by adrianhopebailie** [comment]
At this stage the group does not expect to maintain a registry of payment method identifiers. If there is a proposal to add the text above to the PMI spec please submit a PR.
