### ISSUE TITLE
Is it neccessary to distinguish the origin of data provided in the payment response, and how would we do it?

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/browser-payment-api#173]
Somewhat related to some of the discussion in #75 as ShippingAddress is a a good example of response data that could (in future) be provided by the payment app not the user agent.

Currently the user agent gathered data hangs directly off the response object (`response.shippingAddress`) and the data from the payment app does too (`response.details`).

If the payment app returned the shippingAddress (or some other data that the website had requested) would it sit at `response.shippingAddress` or `response.details.shippingAddress`?

**Comment by tommythorsen** [comment]
+1 for `response.shippingAddress`. I feel that `response.details` is for information that falls outside the scope of the spec, but the payment app still wants to pass to the merchant.

(To add to this, I feel that the field for opaque data in the PaymentRequest and the PaymentResponse should have the same name. In the PaymentRequest, this field is called `methodData[n].data`, while `details` refers to an instance of the PaymentDetails dictionary. In PaymentResponse, however, `details` refers to opaque data. I propose renaming `details` to `data` in PaymentResponse.)

**Comment by rsolomakhin** [comment]
The data inside of `response.details` is app-specific. The app can put whatever it wants there and document it via their own spec, like [Basic Card Payment](https://w3c.github.io/browser-payment-api/specs/basic-card-payment.html).

If the website wishes to receive shipping address from the app instead of the browser, then it should not request shipping information from the browser.

``` javascript
new PaymentRequest(
    [{supportedMethods: ["bobpay.com"], data: {bobPayAddressForShipping: true}],
    details, {requestShipping: false});
```

This can be added a non-normative note, but should not be standardized, IMHO.

**Comment by msporny** [comment]
What was the resolution to this issue? I'm concerned that we're closing issues w/o a clear resolution or reasoning as to why the issue was closed. For example, I'm fine if we decided that we're doing what @rsolomakhin suggested, but we need to document that the group made that decision.

**Comment by adrianhopebailie** [comment]
This issue is stale.

The last proposal was that there is nothing to do ( @rsolomakhin said: "should not be standardized") and there has been no further input for 3 weeks.

If anyone in the group wishes to re-open they can request that we do so based on new information
