### ISSUE TITLE
Time validity of updateWith()

### ISSUE THREAD

**Issue by adamroach** [w3c/browser-payment-api#188]
I think this is probably what everyone has in mind, but we should be clear: updateWith() needs to be valid only during the event processing loop its corresponding event fires in. We want to make sure that the web page cannot update the value _except_ when the UI is frozen as described in updateWith() processing. (Race conditions between update and submit could end up being dangerous, especially when cryptocurrencies are involved).

For example, something like this should not work:

``` javascript
payment.onmailingaddresschange=function(e) {
  setTimeout(function() {
    e.updateWith(...);
  }, 1000));
}
```

**Comment by adrianba** [comment]
The spec already does this. You can only call `updateWith()` while the dispatch flag is set.

Recommend closing this issue.

**Comment by adrianhopebailie** [comment]
@adamroach is there a change in the spec that you had in mind or can I close?

**Comment by adamroach** [comment]
Yes, on re-reading the procedure, I agree with Ade. This is taken care of already. We can close the issue.
