### ISSUE TITLE
Expand Privacy Considerations Section

### ISSUE THREAD

**Issue by adamroach** [w3c/browser-payment-api#228]
This is a recommendation from the Security and Privacy Checklist review. See https://docs.google.com/document/d/1w7ginyzNg-xZUmITK4vzcGUKB4gbMOAvlkWWaRtX14k/edit?usp=sharing for additional detail

The “Privacy Considerations” section of the Payment Request API spec includes a one-sentence treatment of this issue. This should be expanded to address the types of consent (contemporaneous consent versus stored consent), and make it clear that nearly all data exposed through the API is personally identifying.

**Comment by adrianba** [comment]
Per my [comment](https://github.com/w3c/browser-payment-api/issues/229#issuecomment-247721011) for issue #229, I don't believe the spec should try to give advice about the complex subject of user consent.

I recommend that this issue be closed with no changes to the spec.

**Comment by adrianba** [comment]
Closing in favour of #229, which @ianbjacobs took an action to make a proposal for.
