### ISSUE TITLE
Can the merchant influence order of presentation of payment apps to the user

### ISSUE THREAD

**Issue by adrianba** [w3c/browser-payment-api#23]
This issue was [discussed at the F2F](https://www.w3.org/2016/02/24-wpwg-minutes#item06).

The discussion suggested that we should support merchants specifying a preference and allow users to express a preference that overrides merchant preferences.

**Comment by adrianhopebailie** [comment]
In TAG review @triblondon said:

> #23 and #4 discuss the ability for merchants to express a payment method preference and to charge differently for different payment methods. Merchant preference seems basically meaningless unless there is a charge element - the user has no reason to choose a particular payment method simply because the merchant wants them to, but they would certainly be swayed if using one method added a surcharge. Perhaps the simplest way to model that would be to have the merchant pre-calculate a supplement charge to attach to the payment method at the PaymentRequest level, rather than polluting the PaymentDetails items dictionary with multiple additional charges per item (this is suggested in w3c/browser-payment-api#4 (comment), which I agree with). I'm concerned that any potential desire to add granularity to the cost of an individual item will get multi-dimensional very quickly - eg supporting different charges based on payment method, and also expressing pricing in different currencies, you would need a value for each intersection of that possibility space.

**Comment by ianbjacobs** [comment]
At the 8 September teleconference [1] we discussed a use case raised by Max [2]. 

Here is my understanding of our current approach to balancing merchant preferences and user preferences:
- Merchants express order preferences through payment method order (in payment request API) and through recommended apps (in the still draft payment apps spec).
- Browsers would respect those order preferences by default, but MAY provide users with additional services to order apps according to user preferences. The WPWG will not standardize those preferences, but a variety of ideas have come up such as putting recommended payment apps in a privileged position; or when a user is visiting a site and has an app with the same origin displaying that app in a privileged position; or when the browser detects usage patterns for a payment app across sites, the browser might show that one in a favorable position; or the browser might allow the user to specify a preferred order; etc.

Thus, I believe the current approach is to let merchants express preferences and assume users will also be able to do so, and then allow the browser to take that data into account to do the right thing from the user's perspective (also honoring merchant preferences to the extent possible). 

I am reopening this issue to reconfirm (or change) this approach, and to see whether any other merchant preference mechanisms would help address the use case identified by Max.

Ian

[1] https://www.w3.org/2016/09/08-wpwg-minutes.html#item02
[2]  https://github.com/w3c/webpayments/blob/gh-pages/proposals/payment_app_user_experience.markdown

**Comment by adrianba** [comment]
There doesn't appear to be any new information presented here. I believe [this comment](https://github.com/w3c/browser-payment-api/issues/23#issuecomment-245684311) reiterates the text in the spec that was added in PR #140. If this text is insufficient then please reopen this issue proposing new text otherwise I believe the spec accurately describes the WG consensus.
