### ISSUE TITLE
Expand Security Considerations Section

### ISSUE THREAD

**Issue by adamroach** [w3c/browser-payment-api#231]
This is a recommendation from the Security and Privacy Checklist review. See https://docs.google.com/document/d/1w7ginyzNg-xZUmITK4vzcGUKB4gbMOAvlkWWaRtX14k/edit?usp=sharing for additional detail

The Payment Request API document does contain privacy and security sections, but they are much smaller than will ultimately be required. They should be updated to reflect the issues discussed in this checklist analysis.

**Comment by adrianba** [comment]
There is nothing actionable for the editors in this issue and there appear to be other issues opened with specific proposals such as #233 therefore closing this. Please reopen with specific text if necessary but it is preferred to use specific concrete issues.
