### ISSUE TITLE
Clear pointer to GitHub at the top

### ISSUE THREAD

**Issue by annevk** [w3c/browser-payment-api#239]
Requiring readers to dig into "Status of This Document" to find this repository is unfriendly.

**Comment by sideshowbarker** [comment]
Duplicate of https://github.com/w3c/browser-payment-api/pull/226/commits/e6be4e9dd8d9a68881cbe8f9a965a5b994b147ec I think

**Comment by sideshowbarker** [comment]
Duplicate of https://github.com/w3c/browser-payment-api/pull/226 I think

**Comment by annevk** [comment]
Yeah.
