### ISSUE TITLE
Specify UA requirements if “value” field of PaymentCurrencyAmount does not match syntax requirements

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/browser-payment-api#260]
The spec currently states no UA requirements that can be implemented or tested for the `value` field of `PaymentCurrencyAmount` objects; [it uses RFC 2119 MUSTs to specify syntax requirements for the `value` field](https://w3c.github.io/browser-payment-api/#dfn-value), but doesn’t actually state what UAs must do for a `value` that does not match the syntax requirements.

So at this point the only relevant test case I can write for `value` is to check that the UA doesn’t throw if the `value` doesn’t match the syntax requirements—because the spec does not say the UA must throw. (And currently Chrome does actually throws for such a `value`, so [Chrome is not conforming to the current spec here](https://bugs.chromium.org/p/chromium/issues/detail?id=647766)).

**Comment by adrianba** [comment]
Right now the spec doesn't define any behaviour for this situation so I don't believe it is true that Chrome is not conforming. I think currently implementations can do what they want.

I'm not proposing that this is what the spec _should_ say, only what is or isn't said now. PR #256 is your proposal here. As I commented there, I was planning on a different solution to enable consistency between constructor and updateWith. That said, if the consensus is to throw in the constructor but do something else with updates then I could live with that. It just isn't my preference.
