### ISSUE TITLE
What should happen when invalid data is provided?

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#265]
The spec does not explicitly state that the browser should throw an exception when, for example, invalid amount is provided.

``` js
total: {label: "total", amount: {currency: "USD", value: "x"}}
```

Should the spec explicitly specify that an exception must be thrown or is that implicit?

**Comment by adrianba** [comment]
This was fixed in #256. If this change was insufficient then please reopen this issue with a specific proposal for what needs to be changed.

**Comment by rsolomakhin** [comment]
I propose that the following text be added:

"If the value is invalid, UA should throw TypeError."

Is there a better error type for signifying invalid input parameters?

**Comment by adrianba** [comment]
This is in the spec - for example see steps 5, 7, 8, 11, and 13 of the constructor algorithm.
