### ISSUE TITLE
How can a user agent not accept a payment method?

### ISSUE THREAD

**Issue by halindrome** [w3c/browser-payment-api#273]
In section 4.2 (show) step 8 it says "Let acceptedMethods be supportedMethods with all identifiers removed that the user agent does not accept."  

It is not clear to me how an UA has the wherewithal to not accept a payment method?  Is it perhaps that this is unfortunate wording?

**Comment by zkoch** [comment]
Closing as I don't think this is problematic, but feel free to reopen if you disagree.
