### ISSUE TITLE
Examples in the spec

### ISSUE THREAD

**Issue by halindrome** [w3c/browser-payment-api#274]
I think there would be value in including short JS snippets that show how the various objects, methods, and promises are actually used to help with comprehension when people read the spec.  

I am happy to offer PRs for such examples if there is agreement that it is a good idea.

**Comment by marcoscaceres** [comment]
@halindrome this may be addressed by https://github.com/w3c/browser-payment-api/pull/329

We might be better served by having an explainer for additional examples.

**Comment by marcoscaceres** [comment]
Closing, as the spec has fairly good examples now. We can add more common issues come up as people start using the various implementations.
