### ISSUE TITLE
Throwing exceptions rather than permitting broken usage

### ISSUE THREAD

**Issue by halindrome** [w3c/browser-payment-api#275]
Historically HTML and other parts of the web platform have documented the behavior of user agents when things are used incorrectly in the wild.  This is GREAT!  However, when designing new interfaces, I feel it is okay for us to throw errors when things are used incorrectly.

For example, the shippingOptions field is a sequence or items, one of which can be "selected".  The spec indicates that if more than one is selected, then user agent must select the last one in the sequence (that is selected).  I think this is broken.  If more than one is selected, the interface should throw an error.  

There are multiple instances in the spec that are like this.  We can surely test it, but I would prefer to test that the system throws an error rather than that it permits broken behavior.

If there is agreement on this, I am happy to supply PRs.

**Comment by marcoscaceres** [comment]
I don't think we can change the behavior of the spec in the manner you are proposing.

@halindrome, can we close this?

**Comment by marcoscaceres** [comment]
Closing, @halindrome please reopen if you disagree or want to propose an alternative.
