### ISSUE TITLE
What does it mean to "accept the payment"?

### ISSUE THREAD

**Issue by halindrome** [w3c/browser-payment-api#278]
In the PaymentAddress interface (last paragraph) it says "...the user's shipping address after the user has accepted the payment."  I am pretty sure this means "after the user has completed interacting with the PaymentRequest user interface and indicated that they agree to make the payment".   Later in the document there is a term "user accepts the payment request algorithm".  If that is what is REALLY meant by this phrase, I suggest we turn it and its ilk into a reference to that algorithm.  I would also suggest that the name be more pithy.

**Comment by adrianba** [comment]
Happy to change this and #273 - this is the language that we've used since the first draft. Do you have suggestions for a more pithy description?

**Comment by halindrome** [comment]
Sorry @adrianba I missed your question earlier...

Pithy?  How about "..the user's shipping address after the user has accepted the payment request algorithm." ?  It's not pithy, but it has something to link to and is precise.  If you are looking for something that scans better than that I might propose "...the user's shipping address upon the user's agreeing to make the payment."  Or something like that.  After all, what we are saying here is that they user has clicked "okay".

**Comment by dlongley** [comment]
"...user's shipping address after obtaining the user's consent to pay via the 'user accepts the payment algorithm'."?

**Comment by ianbjacobs** [comment]
I counted:
- 1 instance of "after the user has accepted the payment"  
- 1 instance of "after the user has accepted the payment request"  
- 1 instance of "After the payment request has been accepted "
- 1 instance of "acceptance of the payment request"
- 1 instance of "allows the user to accept the payment request"
- 1 instance of "to ensure that the payment is not accepted until"
- 1 instance of a subhead: "User accepts the payment request algorithm"
  which says "user accepts the payment request algorithm runs when 
  the user accepts the payment request and confirms that they want to pay."
- In that section, 1 instance of "that the user selected to accept the payment. "

Based on that, it seems the sentence in section 11 could be slightly modified to say:

  "and ultimately the PaymentResponse object with the user's selected shipping 
   address after the user has accepted the payment request."

Would it similarly make sense in 15.2.1 to change:

 "This is to ensure that the payment is not accepted" to
 "This is to ensure that the payment request is not accepted" ?

Ian

**Comment by marcoscaceres** [comment]
Editors reviewed this and concluded the spec is clear enough as is.
