### ISSUE TITLE
Should the payee be able to inspect the status of a payment?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/browser-payment-api#28]
Raised at the 23 February FTF meeting [1]. Roy wrote:

  "I'm wondering what apis there are for querying about the status of payments? Consider network cutouts during charge, or more simply asynchronous payment methods. How would the merchant expect to inspect the status of payment in these events or would that be something handled by payment methods implementations?"

Let's focus on the network outage use case. It seems to me that this issue would apply to any digital payment scenario, and thus the payment method itself would need to be prepared to address it. It feels to me that this question is one for payment apps to address.

Ian

[1] https://www.w3.org/2016/02/23-wpwg-minutes

**Comment by adrianba** [comment]
When the payment information is returned to the application from the PaymentRequest, it is up to the application to manage what happens next. An assertion that we made for the API proposal was that the web page needs to understand what to do with the response if they include a payment method identifier in the supportedMethods collection. What happens to the response given varying network conditions is also up to the web page. The spec shouldn't say anything normative about this.

Recommend we close this issue.
