### ISSUE TITLE
Should show() depend on a user action?

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/browser-payment-api#283]
(From F2F at TPAC - details to follow)

**Comment by adrianba** [comment]
I'm generally against adding user action as a requirement if we can avoid it but happy to add an informative suggestion. We could also add a suggestion about rate limiting calls to the API (e.g. it might be an option to avoid repeated calls to show() to avoid probing).

**Comment by burdges** [comment]
I'd expect security vulnerabilities if `show` did not always cause a user interaction.
