### ISSUE TITLE
Dynamic Currency Conversion requirements

### ISSUE THREAD

**Issue by Yongsta** [w3c/browser-payment-api#289]
Hi,

Ask for your input

" What is registry requirement to provide DCC in markets as a provider, other than having a contract with an acquirer?"
1. Do all DCC providers need to be PCI-DSS Compliant?
2. Does the DCC provider need to have its own servers for tranx data storage?
3. Is there required registration needed directly to the schemes? (VISA in particular)

thanks

**Comment by ianbjacobs** [comment]
Hello,

I think your question is out of scope for the work that we are doing. Do you have specific comments on the payment request API?

Regards,

Ian

**Comment by marcoscaceres** [comment]
I agree, this is out of scope. A web app should be able to use a third party service to do the conversion (or the payment app should, knowing the user, be able to provide such a conversion).

**Comment by marcoscaceres** [comment]
(I suggest closing)
