### ISSUE TITLE
PaymentRequest constructor errors should be properly annotated

### ISSUE THREAD

**Issue by msporny** [w3c/browser-payment-api#290]
In the section that details the algorithm for the Payment Request constructor, there are multiple places where a TypeError is thrown. If these errors are not annotated (_TypeError.message_ is set), it will be difficult for a developer to determine why the TypeError was thrown (as there are multiple ways it can be thrown in the constructor algorithm).

https://w3c.github.io/browser-payment-api/#paymentrequest-constructor

After chatting a bit with @rsolomakhin, he noted that Chromium does annotate the TypeErrors. The specification shouldn't make a normative requirement on what the text should be, but should provide hints via "optional messages" much like the DOM4 entry in the Dependencies section: https://w3c.github.io/browser-payment-api/#h-dependencies so that developers working across multiple browsers can depend on more or less the same TypeError annotation text.

@rsolomakhin identified the following _TypeError.message_s that can be thrown in the PaymentRequest constructor in Chromium:

https://chromium.googlesource.com/chromium/src/+/0f7bc8677b8f04c46bbbd574b98faa5a2161769a/third_party/WebKit/Source/modules/payments/PaymentRequest.cpp#166
* [x] Must specify at least one payment method
* [ ] Must specify at least one payment method identifier
* [x] Must specify at least one payment method identifier
* [x] Must specify total
* [x] Currency amount required
* [x] Total amount value should be non-negative
* [ ] <del>Currency code required</del>
* [ ] <del>Must specify at least one payment details modifier</del>
* [ ] <del>Currency value required</del>
* [ ] <del>ShippingOption id required</del>
* [ ] <del>Duplicate shipping option identifiers are not allowed</del>
* [ ] <del>Duplicate payment method identifiers are not allowed</del>
* [ ] Duplicate payment method identifiers are not allowed
* [ ] Unable to parse payment method specific data
* [ ] Data should be a JSON-serializable object
* [ ] Item label  #required

I'll try to submit a PR to fix this if it's agreed that this is a good thing to include in the spec.

**Comment by zkoch** [comment]
Sorry for delay on this! I don't have any objection to adding these, seem useful for developers. @adrianba your thoughts?

**Comment by marcoscaceres** [comment]
I agree, but this applies broadly to the whole specification. Basically anywhere a DOM Excpetion is thrown, text should be followed by:

> throw a WhatEverException, optionally informing the developer that < description of what happened >. 

Which basically we can hook into .message without being overly prescriptive (and allowing for localization of errors, etc.) . 

 Also, it's nice to drop "author" in favor of developer. Author sounds antiquated nowadays.

**Comment by marcoscaceres** [comment]
So looking at the spec, it currently defines the message of DOM Exceptions in the Dependencies section - tailored to the payment spec. However, the errors messages are very vague right now: "the object is in a invalid state" etc. 

Admittedly, I'm not a huge fan of this approach - because it overgeneralizes each error condition. As @msporny suggests, I'd rather us take the approach where we explain why an error happened in place.
