### ISSUE TITLE
Response/Request semantics and cancellation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#298]
Not sure where I'm going with this (as I'm pretty new to the spec and the community), but treat this as a question and some knee-jerk reactions... 

The spec seems to have Request and Response semantics that closely mirror the fetch spec. What was the rationale for not following the conventions set forth there? 

```JS
const req = new PayRequest(method, options); 
const payResponse = await requestPayment(req); 
```

There is also some overlap between cancellable promises and this API (the .abort() method). Has thought be given about how this will interact with cancellable promises?  

Also, why is `shippingaddreesschange` and `shippingoptionschange` on the request rather than the response?

**Comment by marcoscaceres** [comment]
Tagging @domenic, as cancellable promises are his domain.

**Comment by adrianba** [comment]
Discussed with @marcoscaceres - not intending to change here but leaving open for comments on cancellable promises.

**Comment by marcoscaceres** [comment]
Having reviewed the spec in detail, and given the behavior of #418, I'm happy to close this issue.
