### ISSUE TITLE
Should PaymentDetails.total be marked as required in IDL?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#300]
In the `PaymentRequest` constructor, it states:

> If `details` does not contain a value for total, then throw a TypeError. 

That implies that PaymentDetails.value is required, no? If so, the `PaymentDetails` dictionary should be updated.

**Comment by marcoscaceres** [comment]
@adrianba tells me that there are instances where you might use `PaymentDetails` without a total.

**Comment by ianbjacobs** [comment]
It would be good to have on this thread the use case(s). I believe one of them is "registration."

Ian

**Comment by marcoscaceres** [comment]
The spec itself documents the use cases :)
