### ISSUE TITLE
"valid decimal monetary value" should move to its own section

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#303]
It seems that the algo for "valid decimal monetary value" is used to check a number of different dictionary members throughout the spec. Hence, the definition should not be part of the `PaymentCurrencyAmount` dictionary's `value` definition.

**Comment by marcoscaceres** [comment]
@adrianhopebailie, would be really awesome if when a PR is sent, it's assigned to a reviewer instead of the person who sent the PR. Is that possible?

**Comment by adrianhopebailie** [comment]
@marcoscaceres that is happening because of a previous test we did with waffle.io. Sorry, I need to figure out how to stop it.

Management of this repo is with the editors: @adrianba, @zkoch and @rvm4
