### ISSUE TITLE
valid decimal monetary value maybe overly restrictive

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#304]
Following the [robustness principle](https://en.m.wikipedia.org/wiki/Robustness_principle), if monetary values are strings, the algorithm for "valid decimal monetary value" should maybe trim.

**Comment by marcoscaceres** [comment]
Chrome throws, so probably should not trim.

**Comment by rsolomakhin** [comment]
Robustness principle is slowly falling out of favor because it encourages incompatible implementations. Strictly defining the boundaries of valid data is also useful in security sensitive contexts, such as payments.

**Comment by rsolomakhin** [comment]
http://queue.acm.org/detail.cfm?id=1999945

**Comment by marcoscaceres** [comment]
Thanks @rsolomakhin for the pointer! Good read.
