### ISSUE TITLE
currencySystem seems like a recipe for interop hell

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#305]
How realistic is it that anyone will support any currency system other than ISO4217? 

It seems like a recipe for disaster if UAs start supporting anything but one. 

Furthermore, if the UA supports more than one, then how can the developer check what currency systems are supported by the UA (apart from forcing an exception). 

In fact, the "currencySystem" is not used anywhere in the algorithms, so IMO it should be dropped entirely from the API: the spec should just say "The currency system is X" and the currency values then represented by an WebIDL enum.

**Comment by adrianhopebailie** [comment]
> How realistic is it that anyone will support any currency system other than ISO4217?

Very realistic. There are already a number of non-ISO currencies in pretty wide use:
- Crypto currencies
- Loyalty points
- Airmiles

**Comment by marcoscaceres** [comment]
Ah, ok. So the payment request can be made with an arbitrary system. How is the relationship between the total amount and the currency system established?

Like when given: 

```
{
  "system": "SuperDuperMiles",
  "currency": "USD", // means "Upgrade Special Discount" in SuperDuperMiles
  "value" : "55.00"
}
```

(I've not read through the whole spec yet in full detail, so this might be already answered)

**Comment by halindrome** [comment]
I don't think that relationship IS enforced.  This information is just that - information.  The devil is in the details, and the real data is per-payment-method and encoded in payment-method specific ways.

**Comment by adrianhopebailie** [comment]
> I don't think that relationship IS enforced

That's my understanding too. These are all UI hints as opposed being data that is used in processing the payment.

Note that the browser doesn't ever auth a payment. The expectation is that the payment app processing the request will understand how to interpret this data correctly and therefor provide the user with the correct prompts to authorize (and confirm the amount etc).

**Comment by marcoscaceres** [comment]
I'm still uncomfortable with this member being there, particularly if it's "just information". If the UA doesn't act on it, then maybe we should reconsidered it at a later date?

**Comment by ianbjacobs** [comment]
Implementers, it would help to hear your plans around this feature. I know that it was considered important by some to be able to include emerging payment systems via alternative registries.

Ian

**Comment by webpayments-specs** [comment]
Chrome currently has no plans to do anything special with currencySystem.

--Rouslan

**Comment by webpayments-specs** [comment]
Just so you know: ISO is looking into extending the standard to accommodate other ‘types of currencies’ such as crypto’s.

**Comment by marcoscaceres** [comment]
> Implementers, it would help to hear your plans around this feature.

Mozilla also currently has no plans to do anything special with currencySystem. I don't plan on adding it to Gecko at this point.

**Comment by adrianhopebailie** [comment]
@marcoscaceres @rsolomakhin 

Does that mean that if you encounter a currencySystem other than the default that you'll throw?

**Comment by adamroach** [comment]
Sorry, lagging a bit this week due to IETF.

@halindrome  --

> I don't think that relationship IS enforced. This information is just that - information. The devil is in the details, and the real data is per-payment-method and encoded in payment-method specific ways.

I don't think that's quite right. The currencySystem is passed through to the payment app so that it has context to interpret the numbers passed to it.

**Comment by rsolomakhin** [comment]
Chrome does not throw for unknown currency systems.

**Comment by marcoscaceres** [comment]
> @adamroach,  The currencySystem is passed through to the payment app so that it has context to interpret the numbers passed to it.

So, to be clear, that's basically what we will do in Firefox... just pass it through. 

Closing, as it seems this was discussed at length prior to me joining the WG.
