### ISSUE TITLE
PaymentRequest type checks (valid non-negative monetary value)

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#306]
The following should be combined:

> If details.total.amount.value is not a valid decimal monetary value, then throw a TypeError.
> If the first character of details.total.amount.value is U+002D HYPHEN-MINUS, then throw a TypeError. total must be a non-negative amount.

We should just define a "valid non-negative monetary value" as an algorithm that calls into "valid decimal monetary value".

**Comment by marcoscaceres** [comment]
(updated the above)

**Comment by halindrome** [comment]
I don't mind this. However, if we do this we need to ensure that the relevant prose is preserved.  We often (in specs) err on the side of a well expressed algorithm at the expense of its readability by mere mortals.

**Comment by zkoch** [comment]
@marcoscaceres is this something we want for CR?

**Comment by marcoscaceres** [comment]
I think it's probably something that will actually emerge from the CR process - as we gain implementation experience and see what issues come up in practice display this stuff in native UIs.

**Comment by marcoscaceres** [comment]
Ignore my last comment, I thought this was a different bug.

**Comment by marcoscaceres** [comment]
The spec if fine as is.
