### ISSUE TITLE
API Data Integrity

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#31]
It should be possible for the Payment Application to authenticate that the PaymentDetails and data parameters that are passed to it via the browser have not been tampered with.

It should be possible for the recipient of the PaymentResponse to authenticate it has not been tampered with.

I propose that these 3 objects are signed to achieve this and that we define this is the base API specification.

I would expect that the keys to achieve this would be;
1) For the PaymentResponse, from the payment applications installation origin's SSL certificate
2) For the PaymentDetails and data objects, from the website SSL certificate that executed the PaymentRequest constructor.

references:
https://github.com/w3c/webpayments/issues/19
https://github.com/w3c/webpayments/issues/78

**Comment by burdges** [comment]
It's probably good, but maybe not always necessary, and it won't necessarily need to be checked by the merchant.  We actually [do that and pass it back even](https://api.taler.net/api-merchant.html#id1), but it just provides the customer a signed receipt.  

All the merchant checks is that the contract they eventually get back is the same one they asked for.   We do that by checking the hash.  Aside from being far more secure, using a hash removes a denial of service attack vector on the merchant that some slower public key operations represent.  If the merchant wants to limit state then an HMAC works too.

**Comment by mattsaxon** [comment]
Agreed, is we are just talking about integrity (as this thread is), but I think there are other requirements that drive towards signatures, see my comment on issue #19

**Comment by cyberphone** [comment]
Applying signatures is technically simple. However there are things that are not equally simple like:
- distribution of signatures keys (if the client is supposed to sign)
- distribution of trust anchors (if the client is going to trust the originator)
- defining whom is trusting whom and for what

As far as I understand client signature key distribution is a part of enrollment in schemes like Apple Pay.

@burdges It was cool  to see that you use a JSON parser/serializer that _preserves_ the order of properties because this (and some more) is what I have been advocating as a prerequisite for "financial messaging".  IETF's JOSE appears more suited for token signing which also it is heritage.
https://cyberphone.github.io/openkeystore/resources/docs/jsonsignatures.html

**Comment by webpayments-specs** [comment]
to make sure API data integrity
we have to think following considerations
- digital signature that the certificate is issued by trusted CA
  (pre-installed CA at user agents)
- encoding is big consideration for verifying signature.
- hashing can be alternative.

On Sun, Mar 13, 2016 at 4:22 AM, Anders Rundgren notifications@github.com
wrote:

> Applying signatures is technically simple. However there are things that
> are not equally simple like:
> - distribution of signatures keys (if the client is supposed to sign)
> - distribution of trust anchors (if the client is going to trust the
>   originator)
> - defining whom is trusting whom and for what
> 
> As far as I understand client signature key distribution is a part of
> enrollment in schemes like Apple Pay.
> 
> @burdges https://github.com/burdges It was cool to see that you use a
> JSON parser/serializer that _preserves_ the order of properties because
> this (and some more) is what I have been advocating as a prerequisite for
> "financial messaging". IETF's JOSE appears more suited for token signing
> which also it is heritage.
> 
> https://cyberphone.github.io/openkeystore/resources/docs/jsonsignatures.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/browser-payment-api/issues/31#issuecomment-195794136
> .

## 

Mountie Lee

PayGate
CTO, CISSP
Tel : +82 2 2140 2700
E-Mail : mountie@paygate.net

**Comment by ianbjacobs** [comment]
Would it suffice for the API spec to support some sort of encoding serializaiton (e.g., base64) so that people who want to ship such data can do so?

Ian

**Comment by adrianhopebailie** [comment]
As with #41 I believe this is out of scope for the API and should be handled by the apps. However, if there is a desire to consider some kind of support for this as a feature of the payment mediator then I recommend it is considered for future versions of the API.

**Comment by marcoscaceres** [comment]
Closing this, as it's outside the scope of the current API. 

This needs to be supported by particular payment methods (e.g., tokenized payments) instead. The API just provides the `.data` where the encrypted data lives, and based on the PMI used, a third-party is able to verify is the data in the `PaymentResponse` if legit or not.
