### ISSUE TITLE
Add canMakePayment() function to PaymentRequest object.

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#310]
This issue is for tracking discussion about adding canMakeActivePayment() function to PaymentRequest. See https://github.com/zkoch/zkoch.github.io/blob/master/pr-detect-avail.md for details of the proposal. It would be great to hear what other implementers think.

**Comment by halindrome** [comment]
I am curious why the name "canMake_Active_Payment" ?  I know why Active is included in the Apple API name, but in our case what is Active about it?  I think canMakePayment makes more sense.  #namingishard

**Comment by rsolomakhin** [comment]
`canMakePayment()` would be misleading, because anyone with an empty profile can make a payment by entering new credit card information into the user agent during the checkout. We need to a keyword that signifies that the user has previously setup their profile by entering valid credit card information into the user agent in the past. Not sure if we can do better than "active."

**Comment by dlongley** [comment]
I also think that `canMakeActivePayment` is kind of a strange name for a method on a PaymentRequest object, as PaymentRequest objects do not make payments. Something like `canUserMakeActivePayment` could mitigate that.

Writing out the algorithm for what the method will do may help in determining its name. It seems to me that it would roughly be:
1. If the user has a payment app installed for one the payment methods in the request, return true.
2. If the one of the payment methods has "built-in" support (e.g. UA may support basic card) and the user has already registered a payment instrument, return true.
3. Return false.

If it's something like the above, I think it's only going to be the case that "active" makes a difference for basic card. For any other method, the mediator can't really determine what payment instruments are available, right? At least if/until something is exposed at the payment app level for the mediator to be able to know that information.

It seems like what's really being asked is: "Has the user ever done anything to enable payments with any  of the specified payment methods (or will they be forced to configure something)?"

Some alternative names may be: `isPaymentMethodAvailable`, `isPaymentMethodConfigured`, `isUserReady`, `requiresSetup`, `requiresConfiguration`.

**Comment by rsolomakhin** [comment]
> I think it's only going to be the case that "active" makes a difference for basic card. For any other method, the mediator can't really determine what payment instruments are available, right? At least if/until something is exposed at the payment app level for the mediator to be able to know that information.

I plan to let payment apps expose to the mediator whether it has payment instruments available.

**Comment by rsolomakhin** [comment]
Pull request in #316.

**Comment by adrianba** [comment]
We have reviewed the `canMakeActivePayment` proposal and we do not support it.

We are not comfortable revealing to a web site that a user has a payment credential for a particular payment method without the user's consent. In addition, in practice it is not possible, with the payment system that our implementation depends upon, for us to gather this information without showing UI.

We can live with a `canMakePayment` method that only reveals information about supported payment methods.

**Comment by ianbjacobs** [comment]
@adrianba, you wrote:

 "We can live with a canMakePayment method that only reveals information about supported payment methods."

Can you say what the inputs and outputs of that are? Thanks!

Ian

**Comment by adrianba** [comment]
I think it's the same just without the "active" check.

**Comment by ianbjacobs** [comment]
Per discussion on 8 December, I have logged as separate (issue #367) on the mechanism for limiting repeated calls to canMakePayments:
 https://github.com/w3c/browser-payment-api/issues/367

Ian
