### ISSUE TITLE
Specification to include Flow Diagram

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#32]
The Flows Task force have created a generic flow to show how the API interacts with various participant in the payment pathway.

I suggest that may be useful to be included in the specification document to assist the reader.

Do others agree this would be useful?

The flow is shown below

![Generic Flow](http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://raw.githubusercontent.com/w3c/webpayments-flows/gh-pages/TargetFlows/PaymentRequestAPI.pml)

**Comment by mattsaxon** [comment]
Submitted PR #131 to address for BasicCardPayment doc

**Comment by adrianhopebailie** [comment]
+1 although not sure which document this should go in

@mattsaxon please change `instrument` to `app` in step 9.

**Comment by mattsaxon** [comment]
This flow describes cards so it is in the correct document. I have other flows which pertain to other documents, which I will submit PRs on once we have the flow in this document agreed.

**Comment by mattsaxon** [comment]
Re: instrument vs app, the payer at some point needs to choose the instrument (payment method data), not just the app.

I assert that this is being done at the point where the mediator (user agent) shows the list of apps/instruments. Otherwise this would be a 2 step process and the payer is likely to forget which instruments are associated with each app without this approach.

**Comment by adrianhopebailie** [comment]
> I assert that this is being done at the point where the mediator (user agent) shows the list of apps/instruments.

I'm a strong -1 to this. We can't assume that payment apps will always able to make payments using multiple instruments OR that user's will configure them with multiple payment instruments OR that users won't configure their mediator with a default app (and only have one installed).

It's only in the case that the user has multiple apps that support multiple payments instruments that there is even a need for a two step process.

The whole architecture is based on the user selecting an app and then within that app selecting the payment method (implicitly through selection of a payment instrument or not, we don't prescribe this) if required to do so.

Good payment apps will make this a seamless process using sensible defaults.

**Comment by msporny** [comment]
> the payer is likely to forget which instruments are associated with each app without this approach.

There are ways to address this issue, here are a few:
1. Payment app icons could be displayed beside the names for each payment method. 
2. Payment methods could be grouped by payment app.
3. Payment methods could be sorted in "most used order" and a small "..." popup info menu could be displayed beside each method with more details shown if you activate the menu.

... and so on. It's not clear which is the best approach and the "best" may be based on the mode of operation. I don't think we can suggest something safely and should instead punt the decision to the market (like most other UI decisions in front of us).

**Comment by mattsaxon** [comment]
@adrianhopebailie 

> We can't assume that payment apps will always able to make payments using multiple instruments 
> We can't assume it will always be true, but the only example we have today allows this for cards
> 
> that user's will configure them with multiple payment instruments
> It won't always be the case, but I would say it is a very common use case and would estimate that the majority of people who hold a single card, hold 2 or more (a good exmaple of why is so they can have both a debit and credit card registered)
> 
> that users won't configure their mediator with a default app (and only have one installed).
> I'd expect they will have a default one, absolutely, but we still need the ability to deal with more than one.

I think the details of this come down to the implementation, so I've revised the flow to replace "select payment instrument" with "Select Payment App/Instrument"

**Comment by adrianhopebailie** [comment]
@mattsaxon The selection of the payment app is facilitated by the browser when using the browser API. I don't believe that the browsers have any intention of mixing up payment instruments and payment apps and offering a selection UI that surfaces the payment instrument in any way.

Our architecture intentionally abstracts the whole idea of a payment instrument behind the payment app because not all payments actually use a payment instrument at all. It allows the payment app to stand for one, many or no payment instruments and the details are up to the payment app publisher.

If the issuer of a payment instrument decides that they want their payment instrument to be surfaced in the app selection UI then they need to publish a payment app that is tightly coupled to only that payment instrument.

**Comment by adrianhopebailie** [comment]
This was done for the Card Payment Method Spec in #131 so closing this.
PR #177 addresses this for the browser API spec
