### ISSUE TITLE
PaymentDetails "total" member should be required

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#320]
Right now there is prose in https://w3c.github.io/browser-payment-api/#constructor step 4 that attempts (not quite correctly) to enforce that.  Please just mark it as required in the IDL instead.

**Comment by foolip** [comment]
Just noticed this as well. AFAICT Blink always throws TypeError when it's missing, so offloading this to generated bindings would be nice.

**Comment by adrianba** [comment]
`total` isn't always required.

**Comment by foolip** [comment]
@adrianba, I see it's used also in https://w3c.github.io/browser-payment-api/#dom-paymentrequestupdateevent-updatewith, is that the place?

If so, the because the dictionary has no required members it'd have to be made optional in the constructor, even though it'd always throw when emitted. ([`getUserMedia()`](https://w3c.github.io/mediacapture-main/#mediadevices-interface-extensions) is also like this.)

**Comment by adrianba** [comment]
Yes. We discussed this with @marcoscaceres and he was going to think about refactoring.

**Comment by bzbarsky** [comment]
It's probably a better idea to just use two dictionary types in the two places that want different behavior.

Failing that, you should fix the constructor to at least properly define the behavior it wants.  And note that updateWith as specced is fairly nonsensical; I still need to report an issue on that...

**Comment by foolip** [comment]
Splitting the dictionaries SGTM, that would also get rid of the forbidden `error` in field in the constructor, which is a bit unusual.

**Comment by bzbarsky** [comment]
Note that the shared fields could be a shared parent dictionary if desired.

**Comment by domenic** [comment]
Splitting the dictionaries would have the normative change of making `error` passed to the constructor ignored, instead of causing an error to be thrown. Is that desired?

**Comment by foolip** [comment]
That seems fine to me, having a dictionary member that does nothing except throw is present is a bit odd, so unless it's expected to be a common mistake just ignoring it probably works?

**Comment by domenic** [comment]
Closed by https://github.com/w3c/browser-payment-api/commit/3c3a10057b3fd97ab21cb4f76b079d8ac5d4d787
