### ISSUE TITLE
"contains a value for" isn't defined for dictionaries

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#321]
The IDL spec defines the concept of a dictionary member being "present" or not at <https://heycam.github.io/webidl/#dfn-present>.  Please use that instead of making up new terminology here.

**Comment by bzbarsky** [comment]
Same thing for various places that use "is supplied" when they mean "is present".

**Comment by domenic** [comment]
This is now fixed and can be closed, through a combination of a couple PRs.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/w3c/browser-payment-api/issues/321#issuecomment-270523227
