### ISSUE TITLE
DOMStrings don't contain "characters"

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#322]
There are various places in this specification that talk about things like "If the first character of details.total.amount.value is U+002D HYPHEN-MINUS" where the thing under conisideration (in this case details.total.amount.value) is a DOMString.  DOMStrings contain code units, not characters.  You either need to talk about the numeric values of those code units, or use USVString and talk about characters or something.

**Comment by domenic** [comment]
I dunno this is pretty widespread in web specs. E.g. just Ctrl+Fing for "character" in the multipage HTML page I had open in one tab landed me on https://html.spec.whatwg.org/multipage/webappapis.html#dom-atob . Maybe we should move away from this term in general. Especially given HTML's [confusing definition](https://html.spec.whatwg.org/multipage/infrastructure.html#character). But it's an understandable way of writing specs.

**Comment by bzbarsky** [comment]
Maybe we need to define what "character" means for a DOMString somewhere, then.  For ASCII cases it's not too bad.

**Comment by marcoscaceres** [comment]
Blocked on https://github.com/heycam/webidl/issues/312
