### ISSUE TITLE
What is "the script calling the constructor"?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#323]
https://w3c.github.io/browser-payment-api/#constructor step 3 talks about "the script calling the constructor" but that's not a thing that's defined.  Please use something that's actually defined here.

**Comment by domenic** [comment]
This is now fixed although other issues with the allowpaymentrequest integration remain. I suggest closing (I don't have permissions to do so).

**Comment by sideshowbarker** [comment]
Closing per https://github.com/w3c/browser-payment-api/issues/323#issuecomment-266803866
