### ISSUE TITLE
Should values for supportedNetworks be defined in Basic Card or separately?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/browser-payment-api#325]
Basic Card Payment defines supportedNetworks as a sequence of identifiers for card networks accepted by the merchant. User agent support for identifiers will likely change over time, and perhaps more rapidly than the custom for W3C to update its Recommendations. Should the list be defined in Basic Card or separately?

Here is a proposal to manage them separately:
 https://github.com/w3c/webpayments/blob/gh-pages/proposals/supported-networks-list.md

Ian

**Comment by zkoch** [comment]
Ian, are you okay to close this?

**Comment by ianbjacobs** [comment]
Please close it after merging this pull request:
 https://github.com/w3c/webpayments-methods-card/pull/25

Ian

**Comment by zkoch** [comment]
Done.
