### ISSUE TITLE
PaymentOptions seems overly verbose/overlaps with HTML

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#326]
What's the rationale for using booleans for the [PaymentOptions's requested members](https://w3c.github.io/browser-payment-api/#paymentoptions-dictionary)? Why not just list the things you want. 

Also, there is a lot of overlap with HTML's [Autofill field names](https://html.spec.whatwg.org/multipage/forms.html#autofill):

```JS
const options = {
  formFields: ["name"]  // why not use values from HTML spec here instead?
  // things specific to this spec would go here... like shipping
}
```

It seems less than ideal that we end up defining the same things twice in the Platform with things that are essentially meant to work together. 

@annevk @domenic, as HTML spec editors, this might be of interest to you.

**Comment by annevk** [comment]
Agreed, I pointed this out to @adamroach before. Thanks for filing!

**Comment by marcoscaceres** [comment]
Additionally, `PaymentResponse` could just have a single FormData object that correspond to the requested `formFields`.

**Comment by nickjshearer** [comment]
> Also, there is a lot of overlap with HTML's Autofill field names

There is no autofill field name for a full address. You'd either need to override the meaning of `street-address` (which technically means only the street lines, not the city, country, postal code, etc) or define a custom field name that represented the address in its entirety. I don't really like either approach - if we need to define a custom name off the bat for a key piece of information then something's gone wrong.

Another option could be to allow discrete address fields to be specified:

`formFields = ["street-address", "address-level1", "address-level2", "country", "postal-code"]`

On the one hand, I think this is less clear than what we have right now and certainly is more verbose. On the other, this could be interesting in terms of validation - merchants could return incorrect or invalid form fields for the UA to display as needing correction. I quite like that.

**Comment by marcoscaceres** [comment]
> There is no autofill field name for a full address.

Then we should add one to HTML... like "full-address" or whatever.   

> Another option could be to allow discrete address fields to be specified:

This is basically what we do today in forms: a "spray and pray" approach: where the developer requests the data (spray the names) in the hope (pray!) the user agent has it in it's autocomplete database.

That seems most sane, because a developer can't assume they will get anything back or what they will get back will be valid. It's flawed to assume otherwise (the current design just gives you back an empty string).  
 
Thus,  adding a generalized "address" auto fill keyword  would be good... but then having the rest is better: 
 
```Js
// I need these things to process the payment
const formFields = [
 "full-address", 
 "street-address",
 "address-level1", 
 "address-level2", 
 "country", 
 "postal-code",
];
```
Then the developer can pick through form data they get back.

```JS
async ()=>{
   const response = await new PaymentRequest(method, display, modz);
   // If we go with form data... 
   for (const [name, value] of response.entries()) {
      // rehydrate and validate form... 
  }   
}
```

**Comment by sideshowbarker** [comment]
> > There is no autofill field name for a full address.

> Then we should add one to HTML... like "full-address" or whatever.

I’ve raised https://github.com/whatwg/html/issues/2105 proposing that.

**Comment by adrianba** [comment]
> Why not just list the things you want.

The reason was to support making these not Boolean.

**Comment by annevk** [comment]
@adrianba you would overload boolean? There's not really a precedent for that. Generally for extensions you would have new members.

**Comment by zkoch** [comment]
I'm not sure I'm wild about what this means from a UX perspective. By generalizing this to a single request (e.g. requestShipping: true), we're able to create a uniform experience for users going through the shipping address flow. It also reduces the likelihood of weird things happening if a developer makes a mistake (e.g. only asking for address-level2 and not address-level1).

**Comment by marcoscaceres** [comment]
> On 1 Dec. 2016, at 11:00 am, Zach Koch <notifications@github.com> wrote:
> 
> I'm not sure I'm wild about what this means from a UX perspective. By generalizing this to a single request (e.g. requestShipping: true), we're able to create a uniform experience for users going through the shipping address flow. It also reduces the likelihood of weird things happening if a developer makes a mistake (e.g. only asking for address-level2 and not address-level1).
> 

That's kinda the point though. The developer might already have "address level 1". Ultimately, we should give developers what they request - but that's independent of the UI that is presented.

**Comment by zkoch** [comment]
If it doesn't change the UI, and it doesn't change the experience that a user sees (and therefore the number of fields they fill in), I don't quite understand why we wouldn't just return it all back and let the developer take what they need from the response.

**Comment by marcoscaceres** [comment]
Marked as won't fix.
