### ISSUE TITLE
Setting internal slots of objects from asynchronous steps is not OK

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#339]
https://w3c.github.io/browser-payment-api/#abort-method step 7 says:

> Set the value of the internal slot request@[[state]] to closed. 

But this is running async.  That means its only interaction with observable objects should be via tasks queued on a task queue, to avoid violating run-to-completion semantics.

**Comment by domenic** [comment]
What task source would make sense here? User interaction task source, maybe? Although technically we're _aborting_ a user interaction; the user isn't actually doing the interaction...
