### ISSUE TITLE
"asynchronously perform the remaining steps" is not defined

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#341]
This specification uses the phrase "asynchronously perform the remaining steps" in multiple places, but the actual behavior of that is not defined.   Are those steps performed off a task?  If so, which task queue does the task use?  Or are the steps performed "in parallel" as defined in <https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel>?

My other feedback on the spec assumes you mean "in parallel"; the task interpretation really doesn't make sense for at least some of the async bits in this spec.  But if I'm wrong and some of those _are_ meant to run off queued tasks, you need to define how those work.

If you do mean "in parallel", please use that phrasing, plus a link to the definition.

**Comment by adamroach** [comment]
You may need to open an equivalent issue on the WebCrypto and WebAudio specs. They use this phrase as well; see:
- Step 6 of https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-encrypt
- Step 3 of `startRendering` in https://www.w3.org/TR/webaudio/#methods-2

**Comment by bzbarsky** [comment]
Filed https://github.com/w3c/webcrypto/issues/168 and https://github.com/WebAudio/web-audio-api/issues/1092
