### ISSUE TITLE
Is section 3.4 informative or normative?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#342]
Section 3.4 doesn't say whether it's informative or normative.  That means that presumably it's normative, but it's not clear to me what the normative content of it is....

I _assume_ this section is meant to be informative and should be annotated as such.

**Comment by bzbarsky** [comment]
I guess section 19 says all diagrams are non-normative.  That means this section says that the [[state]] follows a non-normative set of state transitions.  But following that non-normative set of state transitions is a normative requirement.

I still think it would be clearer to just explicitly label this section non-normative.

**Comment by marcoscaceres** [comment]
The state transition section should just be folded into where [[state]] is defined, as a note.
