### ISSUE TITLE
What does it mean for a user agent to validate displayItems?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#344]
https://w3c.github.io/browser-payment-api/#paymentdetails-dictionary description of displayItems says:

>  The user agent MAY validate that the total amount is the sum of these items

If the UA does that... what does that mean?  What is the corresponding observable behavior or processing model?

**Comment by ianbjacobs** [comment]
One behavior might be a warning to the user. I don't know whether any browser is implementing that.

I don't recall whether another potential behavior was for the payment request to fail with a message to the merchant who could take steps to correct the error.

In any case, it would be good to know what the implementers so far have done (if anything).

Ian

**Comment by bzbarsky** [comment]
Is closing the web page a valid behavior?  Setting the computer on fire?

Seriously, if there's going to be any hope of interop here, the range of valid behaviors really needs to be defined.

**Comment by zkoch** [comment]
I'd be fine taking this out. I believe this was added to give flexibility in implementation. Chrome does not do any validation here.

**Comment by marcoscaceres** [comment]
Agree. Let's take this out.
