### ISSUE TITLE
The shippingOptions field is used in more cases than the spec claims, as far as I can tell

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#345]
https://w3c.github.io/browser-payment-api/#dom-paymentdetails says this in the `shippingOptions` section:

> The shippingOptions field is only used if the PaymentRequest was constructed with PaymentOptions requestShipping set to true. 

but this doesn't match the normative text in updateWith, as far as I can tell: that will use the shippingOptions no matter how the PaymentRequest was constructed...

**Comment by domenic** [comment]
Is this a bug in the description or a bug in updateWith? @zkoch, @adrianba?

**Comment by zkoch** [comment]
I think it's a bug in the updateWith text. Right now it says:

> If details contains a shippingOptions sequence, then:

Perhaps it should say:

> If requestShipping is true and if details contains a shippingOptions sequence, then:

But then the question seems to become: what happens if details.shippingOptions is provided but requestShipping is not true. It seems like ignoring is best, but I guess throwing is more explicit. @adrianba ?

**Comment by bzbarsky** [comment]
What would a typical JS library do with an options object like this?  I suspect ignore, not throw, but this isn't really my area of expertise...

**Comment by domenic** [comment]
I agree a typical JS library would ignore. That appears to be what Blink does too, FWIW:

https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/payments/PaymentRequest.cpp?sq=package:chromium&rcl=1481717748&l=399

I guess I'll add this to #372.
