### ISSUE TITLE
It's probably a good idea to use https://www.w3.org/2001/tag/doc/promises-guide#shorthand-reacting in updateWith

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#348]
Currently updateWith is explicitly poking at Promise internal state.  It's probably better to use the terminology in https://www.w3.org/2001/tag/doc/promises-guide#shorthand-reacting for consistency with other specifications.

This is particularly important because the two options  are not actually black-box identical as far as I can tell.  UAs are going to have a codepath that looks like the shorthands defined in https://www.w3.org/2001/tag/doc/promises-guide#shorthand-reacting but may not have one for doing "Wait until d settles" without actually invoking the initial value of `Promise.prototype.then`.

**Comment by marcoscaceres** [comment]
FWIW, all parts of the spec that talk about promises should be rewritten to adhere to the [promises guide]( https://www.w3.org/2001/tag/doc/promises-guide). It would also address the "in parallel" issue in various places too.
