### ISSUE TITLE
The "if d is resolved" section of updateWith needs to be more explicit about how it gets a PaymentDetails dictionary

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#349]
Right now it says:

> If d is resolved with details and details is a PaymentDetails dictionary, then

but what d is resolved with is an ES value.  What you probably want to do is to convert this value to a dictionary using <https://heycam.github.io/webidl/#es-to-dictionary>.  This can throw exceptions; the spec needs to say what happens if an exception is thrown.

**Comment by domenic** [comment]
This isn't taken care of automatically by Web IDL declaring the argument as `Promise<PaymentDetails>`? I guess it would be if we used https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled instead of the promises guide ... although that itself doesn't account for coercion errors, I think. Hmm.

**Comment by bzbarsky** [comment]
> This isn't taken care of automatically by Web IDL declaring the argument as Promise<PaymentDetails>

Not on its own, no.  You're right that using https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled would be better; it would also address https://github.com/w3c/browser-payment-api/issues/348

That said, https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled and https://www.w3.org/2001/tag/doc/promises-guide#shorthand-reacting have different behavior in terms of whether they call the initial value of `then` or not; we should really harmonize them.

**Comment by domenic** [comment]
I'll use promises guide for now. Using the per-instance `.then` and not handling errors seems bad; I don't think perform steps once a promise is settled is really up to snuff yet. Although we (I) do indeed need to add better promise primitives to Web IDL.
