### ISSUE TITLE
Any plan to allow this API to be called by non-merchants?

### ISSUE THREAD

**Issue by dlongley** [w3c/browser-payment-api#35]
One consideration in the WPCG browser API spec was to allow merchants to publish payment request messages (akin to digitally-signed digital offers) that use push-based payments on a website. Then, for example, a search engine could find these and present them directly as search results. The search result page could call the browser API when a user clicked on one of these digitally-signed payment requests and execute the payment directly.

Will this API have any room for this concept in the future? Are we building it such that it will no longer be a possibility -- and require a separate API to accomplish it? Is it possible for non-merchant sites to call this API -- or do we envision it as a future possibility?

**Comment by webpayments-specs** [comment]
@dlongley,

Other than verbiage that implies that merchants are the intended target for one end of this API, does the API preclude the use cases you have in mind? 

I haven't thought about it deeply yet, but I don't see at first glance limitations on who can call the API.

Ian

**Comment by dlongley** [comment]
On 03/10/2016 01:21 PM, webpayments-specs (Ian Jacobs) wrote:

> @dlongley https://github.com/dlongley,
> 
> Other than verbiage that implies that merchants are the intended target
> for one end of this API, does the API preclude the use cases you have in
> mind?
> 
> I haven't thought about it deeply yet, but I don't see at first glance
> limitations on who can call the API.

If we don't plan for it, it's likely we'll end up building in
restrictions unwittingly -- just based on assumptions regarding its
current use.

The WPCG API allowed you to provide all of the necessary parameters for
performing a payment in a single object, potentially digitally-signed
object. Each specified supported payment method could also include
custom, extensible data. These features don't exist in the current
manifestation of the browser-payment-api -- and there's no way to
support push-based payments. The current API is strongly targeted at
being called by a merchant site that uses pull-based payment methods.

Now, there are some issue markers related to the above that are present
in the document. But I wanted to make clear that the answer is "Yes,
there are currently implicit limitations on who can call this API and
these will only continue to proliferate if we don't plan for more wide use."

**Comment by adrianhopebailie** [comment]
@dlongley this feels like something that should be described in the HTTP API?

Could you describe the use case you are wanting to support in more detail and also how this could be supported? If possible a concrete proposal in the form of a PR to the specs that shows the changes required to support this use case would help us make progress faster on this.

**Comment by dlongley** [comment]
@adrianhopebailie,

> this feels like something that should be described in the HTTP API?

The use case should be supported by it, yes. We intend to be clear in how it's supported as that spec evolves.

> Could you describe the use case you are wanting to support in more detail and also how this could be supported? If possible a concrete proposal in the form of a PR to the specs that shows the changes required to support this use case would help us make progress faster on this.

Unfortunately, we already had a concrete proposal (with the WPCG API) that was rejected. However, I am hopefully that support for this case will actually fall out from the debates we've been having regarding passing a payment request message as separate data to the `PaymentRequest` constructor. It may turn out that ensuring we separate concerns there, that we'll once again be able to support this use case as a natural consequence.

**Comment by adrianhopebailie** [comment]
Use case addressed by the HTTP API

**Comment by dlongley** [comment]
I don't think this is addressed solely by the HTTP API. How would the user get access to their in-browser installed Payment Apps? In one use case, we want an API that can be triggered from a search result web page.

**Comment by adrianhopebailie** [comment]
@dlongley Can you log a new issue that describes specifically what features of the API you consider to be missing and include some more detail about the use case you want to support that require these?

Logging the issue as a question made it unclear exactly what the issue was.

**Comment by msporny** [comment]
> Logging the issue as a question made it unclear exactly what the issue was.

Just to be clear, we started logging issues as questions because there were some folks in the group that (understandably) felt like our proposals were too aggressive by suggesting concrete changes.

The question poses a problem and requests that the browser API editors provide their thoughts on how this problem should be addressed by the browser API. The use case cannot be addressed by the HTTP API because it has no way of accessing the in-browser payment apps. This is definitely a browser API issue, and it remains unaddressed.

We've been holding off on opening the signed offer/payment request can of worms until the group got its footing a bit more established. Happy to do that now if that's what you're asking us to do @adrianhopebailie

**Comment by adrianhopebailie** [comment]
@msporny @dlongley this question is open-ended and asks about design intent. I don't agree that it proposes a problem and asks for proposed solutions. 

Even if we have an answer to this question as stated it doesn't help us make any progress on the spec.

Perhaps a better way to phrase this is:
- How can payment requests be embedded in a webpage as declarative content and then used with the PaymentRequest API?

Either way, I think it would be useful to explain exactly what the use case is and propose how the API needs to change to acheive this. I don't think that is clear at this point.
