### ISSUE TITLE
updateWith will silently ignore data in hard-to-debug ways

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#350]
There are various cases in which updateWith will ignore the data its argument promise is resolved with.  For example, it will ignore various negative amounts, onvalid decimal monetary values, etc.

When this happens, there is no indication to the caller of updateWith that anything went wrong.  Should there be (e.g. via a Promise that updateWith returns)?  I assume UAs are free to report things to the console here, of course, but that only helps if the page author is reproducing the problem themselves...

**Comment by domenic** [comment]
If this returning a promise idea were desired, it'd be a slight breaking change, as all the synchronous error throwing would become rejected promise-returning.

**Comment by marcoscaceres** [comment]
@domenic, given that it returns void right now, would it be that harmful to start returning a promise?

**Comment by domenic** [comment]
I don't think so, but who knows, maybe people are try-catching the errors it produces.
