### ISSUE TITLE
There is no concept of "called from" some browsing context

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#362]
The PaymentRequest constructor steps, step 3, say:

> If the constructor is called from a nested browsing context, then 

but there is no concept of being "called from" some browsing context.

In any case, you probably don't care where it's called _from_.  What you care about is whether the current settings object in the constructor has a responsible browsing context that is a nested browsing context.

**Comment by adrianba** [comment]
This is great feedback. Thank you. Even better would be to propose new language that you would approve. Then we can add it in instead of guessing.

Thanks for the review.

**Comment by bzbarsky** [comment]
I did propose new language, no?  Again:

> If the current settings object has a responsible browsing context that is not a top-level browsing context, then ....

with the relevant links to https://html.spec.whatwg.org/multipage/webappapis.html#current-settings-object and https://html.spec.whatwg.org/multipage/webappapis.html#responsible-browsing-context and https://html.spec.whatwg.org/multipage/browsers.html#top-level-browsing-context

@domenic, @annevk we don't have a shorter way of saying this, do we?  Should we?

**Comment by annevk** [comment]
Not sure, is it common?

**Comment by bzbarsky** [comment]
I don't know.   The need to do it here will go away once feature policy exists, I expect...

**Comment by adrianba** [comment]
> I did propose new language, no? Again:
> > If the current settings object has a responsible browsing context that is not a top-level browsing context, then ....

Great, thanks. See #366.

**Comment by bzbarsky** [comment]
Looks good, thank you!
