### ISSUE TITLE
"allowed to use" check is incorrect

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#363]
PaymentRequest constructor, step 3.3, says:

> If any ancestor browsing context of context has an active document with an origin that is not the same as origin and context's browsing context container's node document is not allowed to use the feature indicated by attribute name allowpaymentrequest, then throw a SecurityError. 

So this will check whether the _parent_ document is allowed to use the feature.  Shouldn't we be checking whether _this_ document is allowed to use the feature?

**Comment by sideshowbarker** [comment]
> So this will check whether the _parent_ document is allowed to use the feature.  Shouldn't we be checking whether _this_ document is allowed to use the feature?

Yes. See https://github.com/w3c/browser-payment-api/pull/359#discussion_r90871814. #324 and #332 still need to be fixed—the entire paragraph quoted in the issue description here needs to be revisited/rewritten. It’s not implementable as currently specced.

**Comment by sideshowbarker** [comment]
> Yes. See #359 (comment). #324 and #332 still need to be fixed—the entire paragraph quoted in the issue description here needs to be revisited/rewritten. It’s not implementable as currently specced.

oofs, ignore what I said there—I didn’t realize til just now that the paragraph quoted in the issue description is new from the https://github.com/w3c/browser-payment-api/commit/056e9f4377ce23ecfff50d108c3767b638f6336b change intended to fix #324 and #332.
