### ISSUE TITLE
What is the mechanism for limiting repeated calls to canMakePayments ?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/browser-payment-api#367]
At our 8 December call [1] we agreed to move forward with some form of canMakePayment and
resolved to separate out the issue of how to limit repeated calls to it.

Ian
[1] https://www.w3.org/2016/12/08-wpwg-minutes.html#item01

**Comment by ianbjacobs** [comment]
Please don't close this issue yet. We intentionally opened this as a separate issue to continue discussion of the mechanism for rate limiting.

**Comment by marcoscaceres** [comment]
The spec says:

> If the method is called too often, the user agent might instead return a promise rejected with a "QuotaExceededError" DOMException, at its discretion.

@ianbjacobs, is that sufficient? can we close?

**Comment by ianbjacobs** [comment]
Yes, ok to close. I believe we had consensus to let browsers try different approaches.
