### ISSUE TITLE
Editorial: refer to methods with parentheses for clarity, and spell out their params in their definition

### ISSUE THREAD

**Issue by domenic** [w3c/browser-payment-api#378]
E.g. instead of

> abort can only be called after the show method has been called

say

> abort() can only be called after the show() method has been called

and instead of

> The complete method MUST act as follows: 

say

> The complete(result) method MUST act as follows:

**Comment by marcoscaceres** [comment]
I can definitely do 1 as I just added support for that in ReSpec. I might be able to do 2 with some "data-lt=" magic.
