### ISSUE TITLE
PaymentApp fails to abort payment flow 

### ISSUE THREAD

**Issue by maheshkk** [w3c/browser-payment-api#384]
After invoking paymentRequest.show() if merchant decides to abort the payment and if user-agent has already invoked payment app, shouldn't user-agent attempt to abort proceeding? 
-  Try to abort the payment flow with paymentApp 
-  If paymentApp responded with payload by then, user agent ignores the payload because Merchant already said they don't want payload.

**Comment by ianbjacobs** [comment]
Hi @maheshkk,

Is this fundamentally a third-party payment app question, or is this also a question for the browser-as-card-data-payment-app? 

If this is fundamentally a third-party payment app, then I suggest we move this issue to:
 https://github.com/w3c/webpayments-payment-apps-api/issues

Ian

**Comment by rsolomakhin** [comment]
This question spans both the `.abort()` algorithm in `PaymentRequest` spec and all the payment app specs.

**Comment by marcoscaceres** [comment]
@zkoch, thoughts?

**Comment by zkoch** [comment]
My concern is that this is almost impossible to implement or guarantee in practice, especially when considering push payment scenarios. For example, if the user is inside of iDeal pushing money to the merchant bank account inside of the native iDeal app on Android, how do we abort that? I think technically this is difficult, but even more difficult is trying to figure out what should happen, especially if you're mid-transaction. This is why we chose not to support this.

**Comment by zkoch** [comment]
Going to close this for now, as I'm not sure there's much we can do. But re-open if you disagree.
