### ISSUE TITLE
Adding dialog close event

### ISSUE THREAD

**Issue by rvm4** [w3c/browser-payment-api#387]
We noticed that there is not a way to respond to the Payment Mediator UI being torn down. We have the .show() callback when the PaymentRequest is resolved, but the spec currently says this occurs as soon as the PaymentResponse is received. 

I propose that we add an event for when the dialog closes, an "ondialogclose" event. Thoughts?

**Comment by rsolomakhin** [comment]
Promises have a way to do this: rejecting a promise. Merchants handle promise rejection via `.catch(errorHandler)` call. Let's specify that user dismissal of the dialog should trigger rejection of the `.show()` promise with a "Request cancelled" message. For example:

```javascript
new PaymentRequest(methodData, details, options)
.show().then(handlePayment)
.catch(error => {
    console.log(error);  // Should print "Request cancelled" on dismissing the dialog.
});
```

**Comment by rvm4** [comment]
I don't mean a dismissal of the dialog, I mean the browser tearing it down in success. Basically, the dialog closing after the PaymentResponse is marked complete.

**Comment by webpayments-specs** [comment]
That event is signalled to merchant by resolving the .complete("success")
promise. For example:

instrumentResponse
.complete("success")
.then(handleBrowserDialogHidden)
.catch(handleError);

--Rouslan

**Comment by rvm4** [comment]
Hmm, okay, good to know. Thanks for the clarification.
