### ISSUE TITLE
Providing/Generating paymentRequestID during construction

### ISSUE THREAD

**Issue by sanjoypal** [w3c/browser-payment-api#388]
The specification says that "If a paymentRequestID was not provided during construction, generate a paymentRequestID". 

Specification is not clear about providing paymentRequestID while construction. 
Constructor accepts PaymentMethodData, PaymentDetails and PaymentOptions.

Constructor(sequence<PaymentMethodData> methodData, PaymentDetails details, optional PaymentOptions options).

**Comment by marcoscaceres** [comment]
"generate" is also underfined.

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

My sense from previous discussions is that we did not want to require a specific format, but that some sort of UUID would make sense. Therefore, UUID could be cited but not required.

Would that answer your question, or do you have other requirements in mind (e.g., length limit, etc.)?

Ian

**Comment by marcoscaceres** [comment]
Related discussion: https://github.com/w3c/browser-payment-api/issues/287

**Comment by marcoscaceres** [comment]
For UAs, it would be interesting to know what Chrome and Edge currently set for this. There are always security considerations for these kinds of things, so a "RECOMMENDED"/"SHOULD" for the ID type might be in oder.

**Comment by ianbjacobs** [comment]
@marcoscaceres,

+1 to hearing what the UA developers have done or are thinking of. I apologize; I cannot recall (or find minuted) the version of UUID that people were suggesting as "recommended". Perhaps someone else can.

Ian

**Comment by rsolomakhin** [comment]
We currently don't have this implemented, as it was a late addition to the spec. Once it's implemented it should probably be a GUID, like `4c967042-5045-40d9-b4a6-1dfa1c1f8646`. Is there a standard to which we can point for this?

**Comment by marcoscaceres** [comment]
[RFC 4122](https://tools.ietf.org/html/rfc4122)
