### ISSUE TITLE
Internal slots vs. attributes

### ISSUE THREAD

**Issue by tommythorsen** [w3c/browser-payment-api#393]
I've been wondering for some time: Why are the `methodData`, `details` and `options` properties of the `PaymentRequest` interface defined as "internal slots" and not attributes? It's not that it doesn't work, or that there's any problem with having them as internal slots, I just found it weird. Is there a good reason for declaring these properties in this way?

If there is no good reason at all, then I would actually suggest changing them to attributes, as it would make the `PaymentRequest` structure a tiny bit easier to understand just by looking at the WebIDL.

**Comment by domenic** [comment]
The idea is that they are not accessible via JavaScript. (Web IDL only specifies things that are accessible to JavaScript as part of the public API.)

Maybe you were asking for a feature request of exposing those things to JavaScript, which is a separate issue; I don't know why they aren't exposed. But given the desire to not expose them, the spec formalism here is correct.

**Comment by tommythorsen** [comment]
Yes, my question is: why are these properties not exposed to javascript as attributes? I see no good reason that they need to be hidden, and I think `PaymentRequest` would look a little bit better with these as attributes.

**Comment by marcoscaceres** [comment]
@tommythorsen, exposing the internal state might be good, but we should consider them on a case-by-case basis (in terms of developer value). Specifically, if the internal slots just hold the values that were passed as arguments to the PaymentRequest constructor, then developers can just get at those (original) references: they passed them in, so they know what they are.  

```JS
// These are all accessible
const methodData = {...};
const details = {...};
const options = {...};

// These are copied... but basically reflect the above
const request = new PaymentRequest(methodData, details, options);
```

Also, given that we now have two shipping implementations (and a third one on the way in Gecko), we probably don't want to make these kinds of API additions for v1 unless they solve some fairly compelling use cases.

**Comment by marcoscaceres** [comment]
Closing this for now, @tommythorsen - please reopen if you would like to discuss further or have compelling use cases.
