### ISSUE TITLE
[WebIDL] reference is wrong

### ISSUE THREAD

**Issue by domenic** [w3c/browser-payment-api#394]
https://w3c.github.io/browser-payment-api/#normative-references somehow despite using the reference string [WEBIDL-2] it is still linking to Web IDL Level 1. In addition to depending on the many bugfixes in the Web IDL master draft, this spec uses features only present there, such as [SecureContext].

**Comment by marcoscaceres** [comment]
Yeah, noticed that also. I think we need to fix that over on Specref or see if there is some alternative ID for WebIDL pointing to the correct spec.

**Comment by marcoscaceres** [comment]
Ok, did a little digging.... WebIDL-2 is just an alias for W3C WebIDL Rec. For some reason, WebIDL (latest) is not auto-published yet. 

@tobie or @heycam, can we please get WebIDL auto-published at:

https://www.w3.org/TR/WebIDL/

It currently redirects to WebIDL-1, which is problematic.

**Comment by tobie** [comment]
See https://github.com/heycam/webidl/pull/221.

**Comment by tobie** [comment]
Oops, sorry I thought auto-deploy was also on this PR.

**Comment by domenic** [comment]
It seems like fixing WebIDL-2 to point to the right URL would be better than changing WebIDL to deploy to TR.

**Comment by marcoscaceres** [comment]
@domenic, ok, but we need agreement on what the "right URL" is... for you an I, it's obviously going to be: https://heycam.github.io/webidl/

But that might not fly with others.

**Comment by tobie** [comment]
Well, there's always [WebIDL-1] if you want anything more specific.

**Comment by domenic** [comment]
@marcoscaceres the fact remains that only https://heycam.github.io/webidl/ has the Web IDL defined in this specification, so that's what this specification should reference, one way or another.

**Comment by marcoscaceres** [comment]
@tobie no, that one is obsolete. 

@domenic agree. I'll send a PR to specref and then we can change it to point to w3c once auto-pub is in place.

**Comment by marcoscaceres** [comment]
Sent: https://github.com/tobie/specref/pull/324

**Comment by marcoscaceres** [comment]
WebIDL-2 now points to the right place.
