### ISSUE TITLE
Drop redundant reference to secure context + other redefinitions

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#399]
The spec now relies on HTML's "allowed to use" to generate the "SecurityError" DOMException, so the current wording in the spec is a bit misleading, because it makes mention of secure contexts. 

I suggest we drop:

 * [x] the reference to Secure Context, 
 * [x] the note that defines what [SecureContext] is (dup definitions always end in sadness - we shouldn't redefine things from WebIDL). 
 * [x] the messages from the DOMExceptions (we now link directly to WebIDL - these are not needed). Additionally, error messages should be defined in place where they are generated to provide developers with context of why an error occurred. Generic error messages are usually pretty unhelpful.

**Comment by domenic** [comment]
I agree with all of these suggestions; they were things I was already scratching my head about.
