### ISSUE TITLE
`PaymentInstrument.complete(result)` wording

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#402]
The spec says:

> Calling the complete() method tells the user agent that the user interaction is over (and should cause any remaining user interface to be closed).

This phrasing is confusing, because user is not interacting with the webpage before `PaymentInstrument.complete(result)` is called. The user agent would normally block user interaction with a "Processing transaction..." message before this call. Therefore, the phrasing should be changed to:

> Calling the complete() method tells the user agent that the _transaction_ is over (and should cause any remaining user interface to be closed).

**Comment by zkoch** [comment]
I agree this is probably closer to the intended meaning.
