### ISSUE TITLE
PaymentRequestID initialization

### ISSUE THREAD

**Issue by rvm4** [w3c/browser-payment-api#412]
I (a colleague) realized that in a previous PR I introduce the paymentRequestID field on PaymentRequest without any way to actually set this value. I would like to take this value in as the first parameter to the constructor of PaymentRequest since none of PaymentMethodData, PaymentDetails and PaymentOptions makes much sense for holding this value.

Thoughts?

**Comment by rsolomakhin** [comment]
As long as it's optional :+1:

**Comment by rvm4** [comment]
Great, I'll PR it.

**Comment by marcoscaceres** [comment]
closed via #426
