### ISSUE TITLE
paymentRequestID is spelled wrong :(

### ISSUE THREAD

**Issue by domenic** [w3c/browser-payment-api#414]
Per https://w3ctag.github.io/design-principles/#casing-rules it should be "paymentRequestId" (lowercase).

I assume this is too late to change now, unless paymentRequestID/d is one of the things that are in the spec but nobody has shipped yet? If it is indeed too late, we should add a note to the spec saying essentially "sorry for creating an API inconsistent with the rest of the platform".

**Comment by marcoscaceres** [comment]
It doesn't look like it's in Chrome 🎉. Is it in Edge?

**Comment by marcoscaceres** [comment]
Here is Chrome Canary (Version 58.0.3005.2): 
![screenshot 2017-02-09 11 07 33](https://cloud.githubusercontent.com/assets/870154/22763332/32c65824-eeb8-11e6-91e4-7fa43ec203bc.png)

**Comment by marcoscaceres** [comment]
(definitely ok for us to change on the Gecko side, obviously)

**Comment by marcoscaceres** [comment]
I've pinged Molly from Microsoft to confirm if it's ok to change.

**Comment by marcoscaceres** [comment]
Got an ok from Microsoft to change this. They've not shipped it either.
