### ISSUE TITLE
It is never stated how the payment request ID is used

### ISSUE THREAD

**Issue by domenic** [w3c/browser-payment-api#415]
It appears that it's meant to be (a) set during construction, see #413, then (b) PaymentResponse is supposed to set its paymentRequestID to the same value of the PaymentRequest that generated it.

This latter part (b) never happens in the spec, so it is spec-complaint right now for paymentResponse.paymentRequestID to return anything at all.

"user accepts the payment request algorithm" needs to have a step that copies over the paymentRequestID value.

This should be done after #413 since it looks like #413 is going to introduce an internal slot to hold the paymentRequestID on the PaymentRequest object.

**Comment by marcoscaceres** [comment]
closed via #426
