### ISSUE TITLE
Terminology across all Web Payments documents should be aligned

### ISSUE THREAD

**Issue by msporny** [w3c/browser-payment-api#43]
Migrating from https://github.com/w3c/webpayments/issues/23:

The specs should import the Web Payments IG glossary. An example of how to do this is in the Web Payments CG's Browser API spec:

https://github.com/WICG/web-payments-browser-api/blob/5034393370c54226eb13fbdacde2462ba5e11713/index.html#L170-L177

You will also need to include a script here:

https://github.com/WICG/web-payments-browser-api/blob/5034393370c54226eb13fbdacde2462ba5e11713/index.html#L13

which can be found here:

https://github.com/WICG/web-payments-browser-api/blob/5034393370c54226eb13fbdacde2462ba5e11713/utils.js

Spec refs:
http://wicg.github.io/paymentrequest/specs/architecture.html#glossary
http://wicg.github.io/web-payments-browser-api/#terminology

**Comment by ianbjacobs** [comment]
We have discussed previously the expectation that once the WG has settled on terms, we should look to back port them to the IG work.

Ian

**Comment by msporny** [comment]
Porting becomes unnecessary if we're all working from the same terminology document. We shouldn't add layers of abstraction for the editor's that are not needed.

**Comment by adrianhopebailie** [comment]
I'm :+1: on using the existing mechanism to import the necessary terminology from the common glossary.

It feels like unnecessary extra work to back-port the terminology if it can just be added to the IG glossary as we go.

If the IG is happy for the Wg editors to edit the glossary as required they should do that.

**Comment by ianbjacobs** [comment]
If the editors wish to do that, that is fine. But I would not obligate the WG editors to do it. 

Ian

**Comment by adrianhopebailie** [comment]
Migrated to https://github.com/w3c/webpayments/issues/135
