### ISSUE TITLE
`country` vs `sortingCode`

### ISSUE THREAD

**Issue by agektmr** [w3c/browser-payment-api#434]
According to [the spec](https://w3c.github.io/browser-payment-api/#paymentaddress-interface):
**country**: This is the [CLDR] (Common Locale Data Repository) region code. For example, US, GB, CN, or JP.
**sortingCode**: This is the sorting code as used in, for example, France.

These look counterintuitive for me. Also, it's not super clear what `sortingCode` is. In Chrome, I only get blank  "".
Shouldn't these be swapped? Are these intentional?

For reference, in ApplePayJS:
**country**: The colloquial country name for the contact.
**countryCode**: The contact’s ISO country code.

**Comment by marcoscaceres** [comment]
Would really like the i18n WG to take a look at all this 😬

**Comment by rsolomakhin** [comment]
1. PaymentRequest's **sortingCode**:

Sorting code is also known as CEDEX. See [Wikipedia entry](https://en.wikipedia.org/wiki/Postal_codes_in_France#CEDEX) for some background.

The **sortingCode** field would be non-blank only for countries that support it. Try an address in France, for example. The address editor UI in Chrome will show the sorting code field in that case.

2. PaymentRequest's **country**:

The **country** field in PaymentRequest is equivalent to the **countryCode** field in Apple Pay JS.

3. Apple Pay JS's **country**:

The **country** field in Apple Pay JS does not have an equivalent field in PaymentRequest. If a merchant needs to map the CLDR country code to a country name, they would need to use a helper library.

**Comment by agektmr** [comment]
Thanks @rsolomakhin for clarification. As long as this is not a typo / mistake, I'm fine.
