### ISSUE TITLE
Initial values for internal slots

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#436]
The spec says:

```HTML
The <a>PaymentRequestUpdateEvent</a> constructor MUST set the
internal slot [[\waitForUpdate]] to false.
```

For things like the above, might be better for the above just to have initial values for internal slots. 

It's also a bit odd to declare something related to the constructor outside of an algorithm.

**Comment by zkoch** [comment]
@marcoscaceres is this blocker for CR?

**Comment by domenic** [comment]
(Probably not a CR blocker.)

IMO the best solution here is for the constructor algorithm to just set the values.

**Comment by marcoscaceres** [comment]
Agree. Not a CR blocker.

**Comment by marcoscaceres** [comment]
I concur with https://github.com/w3c/payment-request/issues/436#issuecomment-286309922
