### ISSUE TITLE
Authors are not conformance classes 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#440]
The spec says:

``` HTML
Authors SHOULD NOT set <code>selected</code> to true on more than one item. 
```

This needs to be converted to a note. 

See also #437.

**Comment by domenic** [comment]
I don't understand this; we give authoring guidance using normative terms all the time in other specs.

**Comment by marcoscaceres** [comment]
Would prefer developer "best practices" be worked out on MDN or elsewhere, and the spec just handle "if you do questionable thing Y, then X will happen or Y gets ignored".

**Comment by domenic** [comment]
Why include example code in the spec at all then though?

**Comment by marcoscaceres** [comment]
> Why include example code in the spec at all then though?

TBH, I kinda wish we didn't. I talked to MDN folks about this too: I would prefer we worked with MDN folks to come up with great examples and have those documented elsewhere. 

I've used the examples in the spec on MDN, and used them to explain to MDN folks how the API works.  So, they are primarily there to help the documentation folks. 

The secondary use is for me to copy/paste when I'm trying stuff out.

**Comment by ianbjacobs** [comment]
@marcoscaceres, cc @dontcallmedom 

To whom should I speak at MDN about material we have been gathering on the web payments dev portal?
https://github.com/w3c/payment-request-info

Specifically these code examples (largely from @rsolomakhin):
 https://github.com/w3c/payment-request-info/wiki/CodeExamples

Ian

**Comment by dontcallmedom** [comment]
See https://github.com/w3c/payment-request-info/issues/4
