### ISSUE TITLE
Fix markup errors that broke autopublishing

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/browser-payment-api#444]
See https://lists.w3.org/Archives/Public/public-tr-notifications/2017Feb/0168.html

Autopublishing of the spec is currently broken due to a large number of duplicate IDs and some malformed URLs and other markup errors in the source of the spec.

**Comment by marcoscaceres** [comment]
Looks like the bad ids are being generated by ReSpec (I swear, if I ever meet whomever maintains that...👊). 

Will fix.

**Comment by ianbjacobs** [comment]
...please thank him first, before rearranging his face.

Ian

**Comment by marcoscaceres** [comment]
> ...please thank him first, before rearranging his face.

No promises. Filed ReSpec issue https://github.com/w3c/respec/issues/1119

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3c/respec/issues/1120 for the malformed fragments.

**Comment by marcoscaceres** [comment]
Fixed the duplicate IDs. 

@sideshowbarker, is there a URL that I can POST to at validator.w3.org? Something that will give me back JSON that I can machine process?

**Comment by sideshowbarker** [comment]
> is there a URL that I can POST to at validator.w3.org? Something that will give me back JSON that I can machine process?

https://validator.w3.org/nu/?doc=https://w3c.github.io/browser-payment-api/&out=json

**Comment by marcoscaceres** [comment]
I'll poke around /nu/, as I need to post from localhost when running the tests.

**Comment by marcoscaceres** [comment]
back in business! https://lists.w3.org/Archives/Public/public-tr-notifications/2017Mar/0029.html

**Comment by sideshowbarker** [comment]
> back in business! https://lists.w3.org/Archives/Public/public-tr-notifications/2017Mar/0029.html

w00t 🎉

**Comment by ianbjacobs** [comment]
Thanks !!
