### ISSUE TITLE
Addition of flag on PaymentMethodData to indicate that line items should be shared with apps

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/browser-payment-api#446]
The Payment Apps Task Force has proposed the following solution to addressing concerns about sharing line items from the request with the payment app: https://github.com/w3c/webpayments-payment-apps-api/issues/91#issuecomment-283111711

This would impact the Payment Request API so adding it here too to track it.

**Comment by zkoch** [comment]
RESOLVED: Payment app spec does not include displayItems in payment app request data

Resolved in 03/16/17 WPWG meeting
