### ISSUE TITLE
NotSupportedError in private browsing mode

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#448]
Should `PaymentRequest.show()` ever reject the promise with `NotSupportedError` in private browsing mode? My intuition is "no", because that lets the website know more information than the user might want to share in private browsing mode. I propose to reject with `"Request cancelled"` string instead. Let me whether this should be placed in in spec or is an implementation detail.

**Comment by marcoscaceres** [comment]
Rejecting things with strings is not really an option for a number of reasons (e.g., you lose the stack, it's weird when used in async/await try-catch, etc.). Needs to be a real error.

**Comment by domenic** [comment]
Agreed with @marcoscaceres, but the question is, what real error can we use? Preferably not one that is private-browsing-mode specific. `NotSupportedError` is used for the case where there are no payment methods available, so it seems like a reasonable candidate. Are there any other candidates that show() might reject with in the normal course of operation?

In terms of spec change, if we go with NotSupportedError we could say this is an implementation detail and that in private browsing mode implementations may just decide that no payment methods are available. That this is allowed could probably be a bit clearer in the spec though, e.g. by inserting a step like

> Optionally, reject acceptPromise with a "NotSupportedError" DOMException and abort these steps.
>
> NOTE: this allows the user agent to decide, without consulting any payment apps, that the payment request cannot be fulfilled. For example, in certain privacy-sensitive modes user agents may take advantage of this step.

**Comment by rsolomakhin** [comment]
Today Chrome rejects .show() with "Request cancelled" string when user
cancels the payment in the course of normal operation.If that's not
desired, what error  should be used instead?

--Rouslan

**Comment by domenic** [comment]
Oh, heh, I was wondering what happened in that situation, given that it doesn't appear to be in the spec... I think "AbortError" DOMException is good.

Let me work on a spec PR for both the user-cancels and browser-cancels case.

**Comment by domenic** [comment]
This was fixed by 361e72084830d4c9aa3b09c8c1f08dc316dc71ce.
