### ISSUE TITLE
maybe add `DisplayItem` dictionary

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#457]
As I was implementing using the API on a site, I found I needed to gather together "display items" (`PaymentShippingOption` and `PaymentItem`) in order to calculate tax (`PaymentItem`). Critical for displaying these to the user is the `label` and `amount`. 

As such,  think we should make an Editorial change to introduce:

```JS
dictionary DisplayItem : Localizable {
    required DOMString             label;
    required PaymentCurrencyAmount amount;
};

// and so... 
PaymentShippingOption : DisplayItem {
   // other members
}
PaymentItem : DisplayItem {
  // other members
}
```

**Comment by marcoscaceres** [comment]
@domenic, thoughts?

**Comment by domenic** [comment]
I don't really understand. You are describing this as something that helps gather display items and calculate tax and display them to the user. But this is just an editorial change; it can't help with any of those.

**Comment by marcoscaceres** [comment]
`<rant>`
I guess it doesn't matter too much, but in my *web developer* facing implementation of this API  (i.e., this is not from a Browser Vendor's implementation perspective!) I have the following ES classes.  

```JS
class DisplayItem extends Localizable { /* stuff */ };
class PaymentShippingOption extends DisplayItem {  /* stuff */ }
class PaymentItem extends DisplayItem {  /* stuff */ }
```

And then I have classes like `InventoryTable` (e.g., list of clothing items) and a `ShippingOptionsPicker` that expose a `displayItem` accessor property.

```JS
class InventoryTable {
   get diplayItems() {/* returns PaymentItems */}
}
class ShippingOptionsPicker {
   get diplayItems() { /*returns the selected PaymentShippingOption */}
}
class TaxCalculator {
   get diplayItems() {/* returns PaymentItem representing the calculated tax, based on the above */}
}
``` 

So, then a `TaxCalculator` can calculate tax by, amongst other things, accessing and summing the values of `.displayItems` from `InventoryTable ` and `ShippingOptionsPicker` (with some type assurance, based on the `DisplayItem` sub-class). Eventually, all the "display items" are gathered to produce the `.total` and  line items sent to the `PaymentRequest` constructor.

My point is that it's helpful to be able to reuse things in the spec in user land code. 
`</rant>`
Thought I'd raise it for illustrative purposes. But closing because, meh :)

**Comment by adrianhopebailie** [comment]
Making this API easier to use for developers seems worth keeping this open for...
https://www.w3.org/TR/html-design-principles/#priority-of-constituencies

**Comment by marcoscaceres** [comment]
@adrianhopebailie, we should coordinate with folks from, for instance, Shopify or similar, to see what they will eventually ship to their customers - particularly to see how they wrap the API. Cosmetic changes, like the one I proposed here, might emerge from those libraries: they are all going to have to deal with the things I listed above in one way or another (even if the browser doesn't do any math on the display items, the merchant site will have to... and something will emerge from that).
