### ISSUE TITLE
Ambiguity in "Process payment methods:"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#458]
In the construction of PaymentRequest, for "Process payment methods", sub-step reads:

> Let serializedData be the result of JSON-serializing paymentMethod.data into a string, if the data member of paymentMethod is present, or null if it is not. Rethrow any exceptions.

Which translates to:

```JS
let serializedData = JSON.strigify(paymentMethod.data || null);
```
@domenic, is that correct? If so, for cases where null, `JSON.parse(serializedData)` at any later point will then result in the string "null". 

Or is actually supposed to be:

```JS
let serializedData = paymentMethod.data ? JSON.strigify(paymentMethod.data) : null;
```

In which case, we should change this to:

> If the data member of paymentMethod is present, let serializedData be the result of JSON-serializing paymentMethod.data into a string. Rethrow any exceptions. Otherwise,  let serializedData be null.

Yes, not having "Let serializedData ... " at the start is not as nice... but can be fixed.

**Comment by marcoscaceres** [comment]
Same issue further down in "Process payment details modifiers".

**Comment by rsolomakhin** [comment]
I would prefer the latter. I think `serializedDdata = null` makes more sense than `serializedDdata = "null"`.

**Comment by domenic** [comment]
The latter is what is intended. I don't understand how you could possibly interpret the sentence as the former. The "end parenthesis" of `JSON.stringify` is denoted in prose by the "into a string". You'd have to write something like 

> Let serializedData be the result of JSON-serializing paymentMethod.data, if the data member of paymentMethod is present, or null if it is not, into a string.

to get the former interpretation.

**Comment by marcoscaceres** [comment]
> I don't understand how you could possibly interpret the sentence as the former. 

Sorry, but that is what I concluded from reading what was there (and yes, I know "null" is not what was intended). I read it multiple times and felt uncertain enough to file this bug. That's a sign that it needs rephrasing, as I'm sure I'm not the only one who could misinterpret it. 

Everything else in the constructor section was crystal clear tho.
