### ISSUE TITLE
Why are two sections non-normative?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/browser-payment-api#466]
I revisited PR API today. I am wondering why sections 17 (iframe) and 18.1 (summary of shipping events) are non-normative.

For the iframe section, it seems to me more than non-normative if we are saying "here's how you do this."

It's not clear to me what the purpose of 18.1 is. There is normative text elsewhere about the two events. Does that not suffice?

**Comment by marcoscaceres** [comment]
Whoops!

**Comment by domenic** [comment]
I think 18.1 is reasonably useful for developers. It parallels a similar construct in other specs, e.g. https://html.spec.whatwg.org/#events-2 . It's borderline though, as indeed there is not a lot of information there.

**Comment by domenic** [comment]
Oh, and section 17 is non-normative because it doesn't contain any normative statements. It just links out to a definition of something that does. It's basically telling you that another spec exists which you might find useful as a reader of this spec. That seems non-normative to me.
