### ISSUE TITLE
'Interactive' Bias in API

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#467]
The WebPayment IG discussed a set of automotive use-cases, many of which have requirements to be non-interactive (for safety purposes).

We should review the API to see if the API lends itself towards non-interactive use.... Whilst I believe it does, the internal state machine does have an interactive status, and the spec a bias towards interactions with the user.

**Comment by nickjshearer** [comment]
What about the non-interactive cases covered in https://w3c.github.io/webpayments-http-api/ - isn't the HTTP API intended for such things?
 
I would also add that user interaction doesn't necessarily mean interacting with a screen. It could, for example, include vocal interaction or other hands-free usage.

**Comment by zkoch** [comment]
We should add a non-normative note about this use case.

**Comment by adrianba** [comment]
The spec already says:

> Although this specification is primarily targeted at web browsers, it is feasible that other software could also implement this specification in a conforming manner. 

I think this is sufficient. Recommend closing this issue.

**Comment by marcoscaceres** [comment]
We discussed this during the editors call, and concluded that the current text in the spec is sufficient. 

@mattsaxon, feel free to reopen if you disagree with the Editors' decision to close this issue.
