### ISSUE TITLE
Add explicit extension point to matching algo

### ISSUE THREAD

**Issue by zkoch** [w3c/browser-payment-api#470]
^^

**Comment by adrianhopebailie** [comment]
https://github.com/w3c/browser-payment-api/pull/492

**Comment by adrianhopebailie** [comment]
At the WG call on [11 May](https://www.w3.org/2017/05/11-wpwg-minutes.html#item02) the @adrianba agreed to propose a different PR (to supersede #492).

**Comment by marcoscaceres** [comment]
Postponing until after CR.

**Comment by ianbjacobs** [comment]
@marcoscaceres and @adrianba, would you mind providing rationale for the postponement? Thank you,

Ian

**Comment by marcoscaceres** [comment]
There has been no movement on it for many months and it's unstable for the purpose of CR. Also, I think we can solve it in the Handler spec, because basic-card handlers and proprietary handlers can, theoretically, already do everything without needing this "hook".

**Comment by marcoscaceres** [comment]
s/unstable/untestable... autocorrect 🤦‍♂️

**Comment by marcoscaceres** [comment]
Closing this, as I think we can easily add it when we actually need it (i.e., once we pivot back to payment handler and work out exactly, if anything, we need).
