### ISSUE TITLE
Clarity required in section 21.2 regarding privacy

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#475]
Section 21.2 states "There may be legitimate scenarios for calling repeatedly (for example, to control the order of payment method selection)".

Does this imply that this should be supported?

The following wording "The fact that a successful match to a payment method causes a user interface to be displayed mitigates the disclosure risk" does not allow for the use of CanMakePayments() which has no such mitigation.

I recommend this wording is reviewed.

**Comment by marcoscaceres** [comment]
Noting that this whole section is not well written at all... the API is not "called"... methods are called, instances get created, etc. This whole thing is super hand-wavy and not a very helpful manner. We should rewrite it to be more precise with regards to `.canMakePayment()`... and we should actually move this to `.canMakePayment()`.

**Comment by marcoscaceres** [comment]
(this is not a CR blocker... just noting it can be significantly improved)

**Comment by marcoscaceres** [comment]
Actually, we should remove this text entirely. The spec already has a Notes in both `.show()` and `.canMakePayment()` around this privacy concern. 

@mattsaxon, can you take a look? I think it would make more sense.

**Comment by ianbjacobs** [comment]
Is there value to a visible Privacy section (header) with a high-level statement of intent, as well as pointers to specifics?

Ian

**Comment by marcoscaceres** [comment]
IMO, no. "Less is more".
