### ISSUE TITLE
Editors to figure out text on line items

### ISSUE THREAD

**Issue by zkoch** [w3c/browser-payment-api#477]

**Comment by ianbjacobs** [comment]
Here's one idea for consideration. Old:

"For example, it might include details of products or breakdown of tax and shipping."

New:

 "For example, it might include a breakdown of tax and shipping."

(Example 3 shows this sort of usage.)

**Comment by zkoch** [comment]
Chatting at editor meeting, preferred route is to remove this sentence and add something in the privacy section about not sharing this data.
