### ISSUE TITLE
Does PR API need to include text around matching to take payment method manifest into account?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/browser-payment-api#478]
Payment method manifest enables payment method owners to authorize payment apps. This means that other payment apps will not match. I don't believe at this time that PR API matching algorithms speak explicitly about the impact of manifests on matching. Does it need to (e.g., some extension point)?

**Comment by marcoscaceres** [comment]
No it doesn't. Separation of concerns and all that :)
