### ISSUE TITLE
Should list of accepted payment methods be strings or objects?

### ISSUE THREAD

**Issue by msporny** [w3c/browser-payment-api#48]
Migrated from https://github.com/w3c/webpayments/issues/37:

The paymentRequest API asserts that the list of accepted payment methods that a payee exposes to the payer should be a list of strings:

http://wicg.github.io/paymentrequest/specs/paymentrequest.html#paymentrequest-interface

For example:

``` javascript
["visa", "bitcoin", "bobpay.com"]
```

The Web Payments CG Browser API asserts that the list should be composed of objects:

http://wicg.github.io/web-payments-browser-api/#processing-a-payment-request

For example:

``` javascript
acceptedScheme: [{
    scheme: [
      'https://w3id.org/payment-schemes#Visa',
      'https://w3id.org/payment-schemes#Mastercard',
      'https://w3id.org/payment-schemes#Discover'
    ],
    transfer: {
      amount: '4.35',
      currency: 'USD'
    },
    paymentRequestService: 'https://merchant-psp.example.com/services/getPaymentInfo'
  }, {
    scheme: 'https://w3id.org/payment-schemes#Bitcoin',
    transfer: {
      amount: '0.0177',
      currency: 'BTC'
    },
    destination: '3QJmV3qfvL9SuYo34YihAf3sRCW3qSinyC'
  },
```

Should list of accepted payment methods be strings or objects?

**Comment by adrianhopebailie** [comment]
PR #133 proposes a solution to the issue.
