### ISSUE TITLE
Should the user agent generate the `id` when it's empty?

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#483]
@rvm4 Should the user agent generate the `id` when it's empty? The spec has a non-normative note to generate the `id` when it's absent, but that's different from an empty or null string.

**Comment by domenic** [comment]
This was discussed in the PR. We shouldn't treat any values as "trigger the default behavior" besides the one specific value specified by JavaScript for that purpose, viz. undefined. Otherwise it's an open-ended guessing game as to author intent (e.g. what about false? 0? "please generate ID"?)
