### ISSUE TITLE
Supplement QuoteExceededError with NotAllowedError for canMakePayments

### ISSUE THREAD

**Issue by nickjshearer** [w3c/browser-payment-api#485]
I think `QuotaExceededError` is the wrong type of error for `canMakePayments`, since the user agent can return it at its discretion - not just when a quota limit has been reached.

For example, a user agent may decide to not service a `canMakePayments` request when in a private browsing mode or similar, or may allow the user the option to decline to reveal their payment methods to the merchant.

In those cases a quota hasn't been reached, the call has simply been denied. I wonder if it would therefore be better to permit user agents to return `NotAllowedError` instead. It's somewhat of a semantic argument, but otherwise merchants could end up with a scenario when they call that API a single time and get a quota exceeded error, which doesn't make much sense.

**Comment by rsolomakhin** [comment]
`NotAllowedError` makes sense. @zkoch @domenic Thoughts?

**Comment by zkoch** [comment]
Fine by me

**Comment by domenic** [comment]
Yeah seems reasonable.
