### ISSUE TITLE
Standardize on "Payer" and "Payee" terms

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/browser-payment-api#493]
There are a a great deal more uses of the word "merchant" than are necessary in this spec. We should stick to the generic payer and payee terminology, especially in the normative sections.

**Comment by marcoscaceres** [comment]
The words "payer" and "payee" are very close tho, which can make the distinction confusing.

**Comment by ianbjacobs** [comment]
The Intro sets the expectation that "payee" will be used in the document. 

My concrete suggestion is that starting at section 4, there are 8 instances of the word "merchant" and that they be replaced by payee. Before that, it's more informative and for people getting into the document, "merchant" may help establish a picture of what the API does.

Ian

**Comment by adrianhopebailie** [comment]
@marcoscaceres said:

> The words "payer" and "payee" are very close tho, which can make the distinction confusing.

I know! I sympathize, but this argument comes up in every group that is developing technical documentation related to payments. It's standard terminology that we SHOULD adopt to be consistent with others.

**Comment by marcoscaceres** [comment]
> I know! I sympathize, but this argument comes up in every group that is developing technical documentation related to payments.

That kinda makes my point tho. If it's already known to cause confusion, we should avoid it. What we could do is say at the start of the spec: "In this spec, we avoid the use of the common terms 'payer' and 'payee' because they are known to cause confusion: we instead use **merchant** in place of 'payee' and  'end user' in place of 'payer'. " or something like that. 

> It's standard terminology that we SHOULD adopt to be consistent with others.

But I, and probably others, don't want to be Googling for which is which every time we read the spec. Let's be rebels and use something different! [🏍 😎](https://www.youtube.com/watch?v=xm5DPlNCmtk)

N.B: https://www.youtube.com/watch?v=xm5DPlNCmtk

**Comment by ianbjacobs** [comment]
I have no objection flipping the way we use the terms, but I would not do it as @marcoscaceres has done. Maybe something like this:

This specification describes an API that allows user agents (e.g., browsers) to act as an intermediary between three parties in a transaction:
    - the merchant: the entity that runs an online store. Merchant can be generalized to mean "any party that wishes to be paid" (also called the "payee").
    - the user: the end user that makes a purchase at that online store, and who authenticates and authorizes payment as required. User may be generalized to mean "any party wishing to make a payment" (also called the "payer").

**Comment by adrianhopebailie** [comment]
I don't like the term merchant because it assumes this is only going to be used for online shopping...

Let's figure out the color of paint and then when we are done I suspect we'll have ended up back at payer and payee. (Even though they are different shades of grey...)

**Comment by mattsaxon** [comment]
Hopefully not to muddy the waters, but there are some alternative terms that you might consider that don't have these issues;

1. ISO20022 uses Debtor and Creditor
2. Originator and Beneficiary are another alternative pair (highlighted as synonyms in ISO20022)

Regards,
Matt

**Comment by ianbjacobs** [comment]
We went through similar conversations previously and landed on payer and payee. 

I have not heard anybody express confusion about the meaning of the terms, nor have I heard anybody say "I would have understood your API better had you used different terms." Therefore, like Adrian, I prefer we stick with payer and payee. 

As I mentioned previously, I think that it's fine to use another term in the intro (e.g., merchant / end user) to give people a few hooks for understanding the common use case.

Ian

**Comment by marcoscaceres** [comment]
I find them terribly confusing, so won't be making that change. But PRs welcomed if anyone feels strongly enough to make the change.

**Comment by marcoscaceres** [comment]
IIRC, this was addressed by https://github.com/w3c/browser-payment-api/pull/465 

@adrianhopebailie, please reopen if you are still not satisfied with the text in the spec (or kindly please send a PR with changes you would like to see).
