### ISSUE TITLE
PaymentAddress and null values

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#495]
In the "Shipping address changed algorithm", the spec says: 

> Set the shippingAddress attribute on request to the shipping address provided by the user. 

However, it gives no guidance about null values incoming from the information source for the `PaymentAddress`. As such, a lot of those attributes could end up as empty strings. That's ok, but it's not clear in the spec what to do.  

It's also ambiguous in that "new PaymentAddress" is never actually called (even though it has no declared constructor).

**Comment by marcoscaceres** [comment]
Fixed above to say "PaymentAddress".

**Comment by marcoscaceres** [comment]
For my own sanity, I can see: 

1. In PR constructor: PaymentRequest.shippingAddress is initially null. 
2. "shippingaddresschange" losely sets PaymentRequest.shippingAddress, as per OP above. 
3. When `PaymentResponse` is created, `PaymentResponse.shippingAddress` is a reference to `PaymentRequest.shippingAddress`. 

Noting this assumes that there is _always_ a "shippingaddresschange" event fired before `PaymentResponse` is constructed (and returned via the `[[acceptPromise]]`). 

Is that correct? @domenic?

**Comment by marcoscaceres** [comment]
To outline the problem, a browser's Autofill DB from which we might pull shipping addresses might be Swiss Cheese when it comes to the `ShippingAddress` values. In other cases, the information might not be appropriate (e.g., `organization`, and `dependentLocality`)

**Comment by domenic** [comment]
Sorry, I'm not too familiar with this part of the spec. To me it seems like this issue is talking about a bunch of separate unconnected things, so I will just reply to each individually, and you can help me understand how they're accepted.

> However, it gives no guidance about null values incoming from the information source for the PaymentAddress.

What is "the information source for the PaymentAddress"? How would null values be incoming from it?

> Noting this assumes that there is always a "shippingaddresschange" event fired before PaymentResponse is constructed (and returned via the [[acceptPromise]]).

The spec seems pretty vague on that:

> The shipping address changed algorithm runs when the user provides a new shipping address.

I don't know what counts as the user providing a new shipping address. If this is indeed an invariant, maybe we should state it. @rsolomakhin, does Chrome always fire "shippingaddresschange"?

> To outline the problem, a browser's Autofill DB from which we might pull shipping addresses might be Swiss Cheese when it comes to the ShippingAddress values. In other cases, the information might not be appropriate (e.g., organization, and dependentLocality)

I'm not sure how this is related. It seems the same as the user not typing values. I am not sure how the spec handles this; the only validation I see is whether it's null or not. Probably it's up to the UA to determine whether the user has entered enough information (through autofill or otherwise) and whether it wants to allow them to click the "proceed" button or whatever.

**Comment by marcoscaceres** [comment]
> What is "the information source for the PaymentAddress"? How would null values be incoming from it?

It can be a range of things: 

 * A custom "addresses" data store, specifically for Web Payments. 
 * Browser's Autofill DB (same hooks as HTML autocomplete data). 
 * Contacts.app on MacOS, or other third-party contact information provider.
 * Or a mix of the above. 

> I don't know what counts as the user providing a new shipping address.

Presumedly a result of user action of selecting an address on the payment sheet - but does the UA automatically selecting a default address trigger `shippingaddresschange`? This needs to be clarified because it seems one can conclude a payment flow without triggering a `shippingaddresschange` (see below).  

> If this is indeed an invariant, maybe we should state it. @rsolomakhin, does Chrome always fire "shippingaddresschange"?

... and if so, what are the triggers for it? 

> I'm not sure how this is related. It seems the same as the user not typing values. I am not sure how the spec handles this; the only validation I see is whether it's null or not. 

Well, it all of the above lead back to this: should all the attributes on `PaymentAddress` be nullable. 

> Probably it's up to the UA to determine whether the user has entered enough information (through autofill or otherwise) and whether it wants to allow them to click the "proceed" button or whatever.

Yes, absolutely. And we certainly aim to do that in Firefox. However, it really does appear that one can return incomplete information without a) having complete address information, b) requiring any user action. Example from ApplePay (the bogus address is coming from Contacts.app):

![screenshot 2017-04-04 11 55 59](https://cloud.githubusercontent.com/assets/870154/24639056/727db136-1930-11e7-813a-60a69365f7f3.png)

**Comment by domenic** [comment]
Thanks for the clarifications. I'm still not clear what role you see the spec playing here, though. So far I know we want to clarify whether paymentaddresschange always fires before show() completes. But this business about nullable paymentAddress fields is unclear to me. Why does it matter whether the browser sets them to null or an empty string or "foolandia"? We could change it to allow null in more places but the browser is still going to be the one determining what to put their (in interaction with the user) so it's not like that's going to get us more interoperability. Unless you are thinking of adding normative UI requirements (like "if the user doesn't do anything this field must be null")?

**Comment by marcoscaceres** [comment]
> I'm still not clear what role you see the spec playing here, though.

It's basically what you state, but to be clear: 

1. should the `shippingaddresschange` event always fire? Or can a flow be complete without firing an event? 
1. should `PaymentAddress`'s attributes be nullable or always the empty string.

I still feel uneasy about 1, because it assumes that there will be a UI and that `.updateWith()` will always have the opportunity to play a role in the payment flow.  

> Why does it matter whether the browser sets them to null or an empty string or "foolandia"?

Because types matter, even when they can be coerced. 

> We could change it to allow null in more places but the browser is still going to be the one determining what to put their (in interaction with the user) so it's not like that's going to get us more interoperability. 

You are probably right wrt interop. I might be arguing for purity. 

> Unless you are thinking of adding normative UI requirements (like "if the user doesn't do anything this field must be null")?

No, definitely don't want language like that. It's again, more about what information the user agent can pass back to the app with certainty (not null) - but sometimes it could pass back the empty string for certain attributes, if that's the data it has been provided with by the user.

**Comment by marcoscaceres** [comment]
Having gained to implementation experience, empty strings are best here when interacting with form elements.
