### ISSUE TITLE
Reference to payment apps in Introduction needs updating

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#496]
In Section 1. Introduction, "The details of how to fulfill a payment request for a given payment method are handled by payment apps. In this specification, these details are left up to the user agent, but future specifications may expand on the processing model in more detail."

need updating to represent latest status.

**Comment by ianbjacobs** [comment]
+1. If Payment Handler API is a FPWD before PR API becomes a CR, then let's include a reference to Payment Handler. I think this is likely to be an informative reference since there will be different integration specifications (at least between native and web).

Ian

**Comment by marcoscaceres** [comment]
Fine to have it as non-normative. However, it does indeed depend on timing and we should not block on it.

**Comment by marcoscaceres** [comment]
closed via 9e1b9859
