### ISSUE TITLE
Payment App or Payment Handler language

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#497]
Standardise the use of Payment App vs Payment Handler in the spec.

For example show() step 8 states says which "Payment App", but I believe this should say which "Payment Handlers" in this context.

**Comment by mattsaxon** [comment]
Another example if in section  3.5 canMakePayment(), step 6 states "user agent or other payment app". The user agent in this example IS a payment app, so this wording is unnecessary.

**Comment by ianbjacobs** [comment]
I can live with "payment app" but agree with Matt that "payment handler" may be an improvement.
