### ISSUE TITLE
Consider adding examples of payment matching algorithm

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#498]
In show() step 8.1, an example would be useful, especially considering the language used isn't easy to pass e.g. "the second element of the tuple"

**Comment by marcoscaceres** [comment]
Might destructure the tuple into `var`s, for easier reading. I agree that "the second element of the tuple" is a bit confusing.

**Comment by adrianhopebailie** [comment]
May be redundant given #492

**Comment by marcoscaceres** [comment]
@mattsaxon, I've prepared a PR for this, but I'm reluctant to add an example there because we want implementers to implement from algorithms not examples.  

See #530 and let me know if it's ok.

**Comment by mattsaxon** [comment]
@marcoscacares, thanks, happy with this.
