### ISSUE TITLE
Should the web page be able to provide status information before calling complete()

### ISSUE THREAD

**Issue by adrianba** [w3c/browser-payment-api#5]
This issue comes from WICG/paymentrequest#32 and was [discussed at the F2F](https://www.w3.org/2016/02/24-wpwg-minutes#item11).

The resolution at the F2F meeting was:

> Include user message feature in spec and ask for feedback.

**Comment by adrianhopebailie** [comment]
In TAG review @triblondon said:

> Yes. Unless the API can set out guarantees or limits on the duration of the merchant's payment processing, it must support feedback. It's also out of the scope of this API to understand whether a payment method contains distinct phases to its settlement process, and if it does, but those cannot be surfaced, PR may be an inferior user experience to the current methods available to merchants.

**Comment by adrianhopebailie** [comment]
This seems like a useful thing to offer the website developer but I don't think we can provide any guarantee that the user agent is able to deliver it to the app that has the focus.

So that begs the question, should we do it all or do it and put a warning in the spec that sometimes the interface between the browser and app may not allow for this message to get to the app.

**Comment by ianbjacobs** [comment]
@adrianhopebailie,

Please suggest a phrasing that involves conformance (e.g., "the user agent MAY ....." or "the user agent is NOT REQUIRED to ....").

Ian

**Comment by adrianhopebailie** [comment]
@ianbjacobs,

At this stage there is no mechanism described in the API to do this so there is not conformance required. If this is added then I would suggest that the conformance will be:

"The user agent SHOULD notify the user of processing events via the UI" or something like that.

**Comment by marcoscaceres** [comment]
Given what we've learned over the last year from implementing these UIs (and the feedback they provide to users about what is going on in the flow), I think it's safe to close this. 

Please let me know if you think we should reopen.
