### ISSUE TITLE
Clarify use of API in (or not in) Secure Contexts

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/browser-payment-api#501]
My understanding is that the API is to be used in Secure Contexts. I note that:

* SecureContext is optional on PaymentRequest constructor
* Where SecureContext appears elsewhere in the spec it is not optional
* There is no clear statement in the prose about calling the API in a SecureContext
* For iframes, the allowpaymentrequest attribute is non-normative.

It seems to me we need in the spec at least strong guidance about calling the API from a SecureContext, if not something normative. 

Ian

**Comment by marcoscaceres** [comment]
> On 4 Apr 2017, at 1:43 am, ianbjacobs <notifications@github.com> wrote:
> 
> My understanding is that the API is to be used in Secure Contexts. I note that:
> 
> SecureContext is optional on PaymentRequest constructor

You've misread the IDL. There is no such thing as optional SecureContext 😊

> Where SecureContext appears elsewhere in the spec it is not optional
> There is no clear statement in the prose about calling the API in a SecureContext

That would be redundant. Though the link to the definition is currently broken (ReSpec bug, will fix)

> For iframes, the allowpaymentrequest attribute is non-normative.
It's normative in HTML. 

> It seems to me we need in the spec at least strong guidance about calling the API from a SecureContext, if not something normative.
> 

We already have all of the above, I assure you. This can be closed.

**Comment by ianbjacobs** [comment]
Thanks for the clarification, @marcoscaceres. I've added a (terse) note to the FAQ:
 https://github.com/w3c/payment-request-info/wiki/FAQ#is-payment-request-api-called-in-a-secure-context

I welcome suggestions to make that note more useful.

Ian

**Comment by marcoscaceres** [comment]
I don't have time to add this to the FAQ, but someone should broadly define what a "secure context" actually is (as per WebIDL) for the layperson.

**Comment by marcoscaceres** [comment]
> That would be redundant. Though the link to the definition is currently broken (ReSpec bug, will fix)

fixed. Shipping updated ReSpec now...
