### ISSUE TITLE
Links to some HTML definitions are broken

### ISSUE THREAD

**Issue by npdoty** [w3c/browser-payment-api#502]
At least the following don't resolve to the expected definition:
* https://html.spec.whatwg.org/multipage/#elementdef-iframe
* https://html.spec.whatwg.org/multipage/#element-attrdef-iframe-allowpaymentrequest

**Comment by marcoscaceres** [comment]
Blocked on: 
https://github.com/tobie/specref/issues/344

**Comment by marcoscaceres** [comment]
Worst case, we switch back to W3C HTML :(

**Comment by domenic** [comment]
I think this just needs to be fixed to point to the correct fragments:

- https://html.spec.whatwg.org/multipage/#the-iframe-element
- https://html.spec.whatwg.org/multipage/#attr-iframe-allowpaymentrequest

You don't need to know what page things are on.

**Comment by marcoscaceres** [comment]
Wait? is that some dynamic redirect voodoo?

**Comment by domenic** [comment]
Basically, yeah.

**Comment by marcoscaceres** [comment]
Ok, let me try... the link checker is getting upset... but if it's just that the fragments are wrong, then that's easy: 

https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.w3.org%2FTR%2Fpayment-request%2F&hide_type=all&depth=&check=Check

**Comment by marcoscaceres** [comment]
Following need updating. @domenic, some of these are going in infra (e.g., "in parallel"), right? Is it too ambitious to start citing that? 

 * [x] #in-parallel (lines 1951, 2009, 2068, 3061, 3235, 3791)
 * [x] #top-level-browsing-context (lines 2062, 3780)
 * [x] #elementdef-iframe (lines 3110, 3793)
 * [x] #element-attrdef-iframe-allowpaymentrequest (lines 1702, 3110, 3795)
 * [x] #user-interaction-task-source (lines 2015, 3529, 3555, 3598, 3670, 3776)
 * [x] #allowed-to-use (lines 1701, 3788)
 * [x] #queuing (lines 2015, 3529, 3555, 3597, 3670, 3773)
 * [x] #current-settings-object (lines 1700, 3784)
 * [x] #eventhandler (lines 1580, 1582, 2101, 2123, 3770, 3899, 3901)
 * [x] #responsible-document (line 1700)

**Comment by domenic** [comment]
None of those should go to Infra. If you want to start citing it for list manipulation/iteration/etc., that'd be neat though; we're doing that in many specs so far. Not high priority though.
