### ISSUE TITLE
Provide better mapping between PaymentAddress and HTML5 autofill

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#505]
For instance, be more clear that:
 * [ ] region maps to address-level1. 
 * [ ] city is address-level2.
 * [ ] Example of sorting code.  
 * [ ] Point to ISO country codes. 

This helps with the conversion from auto-filled form fields to payment `PaymentAddress`.

**Comment by marcoscaceres** [comment]
Does `dependentLocality` map to [address-level1](https://html.spec.whatwg.org/multipage/forms.html#attr-fe-autocomplete-address-level1) or 2? or something else?

**Comment by marcoscaceres** [comment]
sorting code example would also help?

**Comment by marcoscaceres** [comment]
Also, the `country` attribute pointing to [CLDR] is not very helpful. It should point directly to the ISO 2-digit country codes.

**Comment by rsolomakhin** [comment]
`dependentLocality` is `address-level3`. @evanstade introduced the `address-level*` naming convention, I believe.

Sorting codes are used in France and related countries. See the [Wikipedia entry](https://en.wikipedia.org/wiki/Postal_codes_in_France#CEDEX). Our French working group members should be able to provide some good examples.

CLDR is better than ISO in that it's updated more frequently to reflect the changes in the real world, like the break-up of Yugoslavia.

@lararennie: Please double-check my i18n-foo.

**Comment by lararennie** [comment]
The field labelled "sorting code" is not just used for that, but is country specific: in some countries it manifests as a post office indicator.

Comments for this field should be:
// This corresponds to the SortingCode sub-element of the xAL
// PostalServiceElements element. Use is very country-specific. Where it is
// used, the value is either a string like "CEDEX", optionally followed by a
// number (e.g. "CEDEX 7"), or just a number alone, representing the "sector
// code" (Jamaica), "delivery area indicator" (Malawi) or "post office
// indicator" (e.g. Côte d'Ivoire).

Note that address-level1 and 2 does NOT map to the levels used for administrative purposes in a country, but in an *address*. For instance, for the US, level1 would be state, and level2 would be city/post-town NOT county. In Spain, the top-level admins e.g. Catalonia are not in an address, so level1 is the province, which is.

**Comment by lararennie** [comment]
Good link for CLDR: http://www.unicode.org/cldr/charts/31/supplemental/territory_information.html

**Comment by zkoch** [comment]
@marcoscaceres why is this a blocker for CR?

**Comment by marcoscaceres** [comment]
Closing in favor of https://github.com/w3c/contact-picker/issues/71
