### ISSUE TITLE
Define expected behavior when no 'shippingaddresschange ' event listener is defined

### ISSUE THREAD

**Issue by gauntface** [w3c/browser-payment-api#507]
cc @zkoch @domenic @rsolomakhin 

At the moment the Chrome implement has an edge case that results in a bad user experience:

If the developer requires shipping details and doesn't set a shippingaddresschange event listener, the following happens:

1. The Payment Request sheet opens up.
1. The user adds or changes address
1. A spinner is shown (where it's waiting for event.updateWith() to be called)
1. The API times out and rejects the request.show() promise.

One of two things should be happening:

1. The API *requires* a `shippingaddresschange` event listener be defined and if it's not the case and `shipping` is required, an error should be thrown when `show()` is called.
1. The API doesn't require an event listener, but if there is no listener defined, allow the user to define any address (basically allowing the developer to skip validating the address or shipping option).

I'm in favor of the listener *not* being required just for developer ergonomics and allowing the developer to move this check to the very end of the checkout flow after the `show()` promise has resolved (i.e. not ideal for a user experience but could be the only option for developers).

The relevant spec section is https://www.w3.org/TR/payment-request/#updatewith-method 

> 7. If target.[[updating]] is true, then throw an "InvalidStateError" DOMException.
> 8. Set event's stop propagation flag and stop immediate propagation flag.
> 9. Set event.[[waitForUpdate]] to true.
> 10. Set target.[[updating]] to true.

I think a step needs to be added after 7 which consists of "If no event listener is defined, the user agent will XYZ", where XYZ will be either allow the changes from the user OR throw another "InvalidStateError".

**Comment by rsolomakhin** [comment]
+1 this would be nice to have.

**Comment by gauntface** [comment]
Also worth nothing that the same behavior exists in chrome is `shippingoptionchange` event listener isn't defined.

**Comment by nickjshearer** [comment]
I prefer simply allowing the user to define any address and proceed with the transaction should the developer not implement `shippingaddresschange`.

**Comment by rsolomakhin** [comment]
This would also work for me.

**Comment by gauntface** [comment]
+1 @nickjshearer

**Comment by zkoch** [comment]
Isn't @nickjshearer's idea how the spec is written currently?

**Comment by gauntface** [comment]
@zkoch Either the spec isn't clear enough or Chrome's implementation is simply not to spec. Right now Chrome *requires* a shippingaddresschange event listener.

**Comment by gauntface** [comment]
Looking at the spec some more, I may have been looking at the wrong part, maybe I should have been looking at:

https://www.w3.org/TR/payment-request/#dfn-shipping-address-changed-algorithm

> 17.1 Shipping address changed algorithm
>
> The shipping address changed algorithm runs when the user provides a new shipping address. It must run the following steps:
> 
> 1. Let request be the PaymentRequest object that the user is interacting with.
> 2. Let name be "shippingaddresschange".
> 3. Queue a task on the user interaction task source to run the following steps:
> > 1. Set the shippingAddress attribute on request to the shipping address provided by the user.
> > 2. Run the PaymentRequest updated algorithm with request and name.

It doesn't have any information on what to do in terms of not-having a listener for the shippingaddresschange event.

Again, I'm not very versed in reading specs, so it could be that the language is actually defining the behavior discussed in this issue and I'm not seeing it.

**Comment by marcoscaceres** [comment]
Related https://github.com/w3c/browser-payment-api/issues/495

**Comment by domenic** [comment]
(Finally getting back to PaymentRequest issues...)

The spec as-written seems to be OK, with Chrome's implementation at fault. In particular the spec says that if the user adds or changes an address, a "shippingaddress" change event must be fired. It never says that the UI should be blocked until someone calls event.updateWith().

It sounds like some browsers may block the UI while this event is being fired, but that's not required by the spec in any way, as far as I can tell.

As such I'm inclined to close this (perhaps filing a bug on Chrome about its UX).

**Comment by domenic** [comment]
Actually, what we can do is say that if you don't call updateWith() synchronously, you don't get to call it ever, and it's treated as if you don't care. Since it accepts a promise, this is not restricting. This is related to https://github.com/w3c/browser-payment-api/issues/508. I will work on a PR for both.

Update: you already must call updateWith() synchronously, because of the check on the event's dispatch flag. So yeah, we should close this.
