### ISSUE TITLE
"User accepts payment request" algorithm should timeout without .complete().

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#508]
The [User accepts payment request](https://w3c.github.io/browser-payment-api/#user-accepts-the-payment-request-algorithm) algorithm should timeout if the website never calls `.complete()` method on the `PaymentResponse`.

**Comment by domenic** [comment]
So more concretely, this means that sometime after the user accepts the payment request and the PaymentResponse has been handed back to author code, we should:

- Set the response's [[completeCalled]] to true (so that future calls to .complete() return a rejected promise)
- Close down any remaining user interface with a "timed out" user experience

Is that about right?

**Comment by rsolomakhin** [comment]
This sounds about right. To clarify, Chrome user interface shows a "Processing..." message after resolving the `.show()` promise and before seller calls `.complete()`.

Chrome has a 60 second timer that starts after resolving `.show()` promise. Chrome closes down any remaining user interface either when the seller calls `.complete()` or when the timer expires, whichever happens first.

As additional trivia, if the seller calls `.complete("fail")` or the timer expires, then Chrome shows a "Transaction failed" message. That shouldn't be part of the spec, because it's implementer-specific UX.

**Comment by rsolomakhin** [comment]
Now that I read [Shipping address/option changed](https://w3c.github.io/browser-payment-api/#shipping-address-changed-algorithm) algorithm, I don't see a timeout in there. Chrome also has 60 second timeout for the seller to invoke `.updateWith(details)` after `"shippingaddresschange"` and `"shippingoption"` change algorithm. Should we spec that out?

**Comment by domenic** [comment]
Yes, that seems like a good idea. My guess is that in both cases we should spec a user-agent defined optional timeout (instead of exactly 60 seconds). In that case it should not be controversial to add. @marcoscaceres, do you agree?

**Comment by romandev** [comment]
There seems to be the explanation in updateWith() method part.
https://w3c.github.io/browser-payment-api/#updatewith-method (Number 12)

**Comment by rsolomakhin** [comment]
From the spec:

> Implementations may choose to implement a timeout for pending updates if detailsPromise doesn't settle in a reasonable amount of time. If an implementation chooses to implement a timeout, they must execute the steps listed below in the "upon rejection" path. Such a timeout is a fatal error for the payment request.

This is implemented via a timer. What should the task queue for the timer be?

**Comment by marcoscaceres** [comment]
@domenic, I agree. We plan to add similar timeout behavior.

**Comment by domenic** [comment]
> This is implemented via a timer. What should the task queue for the timer be?

This should use the same task queue as used for the "upon rejection" path. Which is currently underspecified: https://github.com/w3ctag/promises-guide/issues/52.

---

There are three separate timeouts being discussed here:

1. User accepts payment request and .complete() is not called promptly
2. Shipping address/options changed and .updateWith() is not called promptly
3. updateWith(promise) is called but with a promise that does not settle promptly (already in the spec)

(2) and (3) are obviously related, and are also related to https://github.com/w3c/browser-payment-api/issues/507. My proposal is that (2) doesn't need a timer, it just needs a blanket requirement that you must call updateWith() synchronously. Then the timer can be about how fast your promise settles.

I will work on a PR for these.

**Comment by domenic** [comment]
Update: you already must call updateWith() synchronously, because of the check on the event's dispatch flag. OK, so everything is already taken care of, except (1).

**Comment by domenic** [comment]
And.... it looks like (1) is already in the spec too:

> For this reason, implementations MAY impose a timeout for the page to call complete(). If the timeout expires then the implementation will behave as if complete() was called with no arguments. 

So, nothing to do here, actually?
