### ISSUE TITLE
How does the API support enrollment (aka subscription, future payment) use cases?

### ISSUE THREAD

**Issue by msporny** [w3c/browser-payment-api#52]
Migrating from https://github.com/w3c/webpayments/issues/65 and https://github.com/WICG/paymentrequest/issues/43:

@ianbjacobs writes:

Here is a use case that should be supported:
1. Service asks user at enrollment to register payment details for future use
2. API is used to retrieve those details, but no payment should actually take place.

Some payment apps might support this (e.g., raw credit card information) while others might not
(e.g., those that return 1-time tokens).

What (if anything) does the API need to say to help readers recognize that it supports this
enrollment use case?

**Comment by ianbjacobs** [comment]
Subsumed by 
https://github.com/w3c/browser-payment-api/issues/19
