### ISSUE TITLE
CR check list 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#520]
For all Transition Requests, to advance a specification to a new maturity level other than Note, the Working Group:

* [x] must [record the group's decision to request advancement](https://lists.w3.org/Archives/Public/public-payments-wg/2017Jul/0057.html).
* [x] must obtain Director approval.
* [x] must provide [public documentation of all substantive changes to the technical report since the previous publication](https://github.com/w3c/browser-payment-api/pulls?q=is%3Apr+is%3Aclosed+label%3Acr-substantive).
* [x] must [formally address all issues raised about the document since the previous maturity level](https://github.com/w3c/browser-payment-api/milestone/8).
* [x] must provide public documentation of any Formal Objections (none received).
* [x] should provide public documentation of [changes that are not substantive](https://github.com/w3c/browser-payment-api/commits/gh-pages).
* [x] should report which, if any, of the Working Group's requirements for this document have changed since the previous step.
* [x] should report any changes in dependencies with other groups.
* [x] should provide [information about implementations known to the Working Group](http://caniuse.com/#feat=payment-request).

To publish a Candidate recommendation, in addition to meeting the general requirements for advancement a Working Group:

 * [x] must show that the specification has met all Working Group requirements, or explain why the requirements have changed or been deferred,
 * [x] must document changes to dependencies during the development of the specification,
 * [x] must document how adequate implementation experience will be demonstrated,
 * [x] must specify the deadline for comments, which must be at least four weeks after publication, and should be longer for complex documents,
 * [x] must show that the specification has received wide review, and
 * [x] may identify features in the document as "at risk". These features may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation.

**Comment by ianbjacobs** [comment]
Hi Marcos,

Thanks for putting this together. Here are some additional notes:

* Implementations: I believe that Facebook and Samsung Internet browser also
   implement PR API. (I imagine some code is shared in the case of Samsung but
   I don't know details.)

* Implementation experience documentation. My understanding is that we will create
   a test suite and an implementation report. Could you link to the test suite?
   https://w3c-test.org/payment-request/

* Deadline for comments: @adrianba sent a link to a static spec with a CR End date of
   2017-10-31. I'm not sure the WG discussed that yet.

* Features at risk. I've requested addition of an id to be able to link directly to them:
   https://github.com/w3c/browser-payment-api/pull/559

Thanks!

Ian

**Comment by marcoscaceres** [comment]
> I believe that Facebook and Samsung Internet browser also implement PR API.

For the purpose of CR (i.e., to count as conforming implementations), we will need to add the web platform test data output somehow. 

> Implementation experience documentation. 

Linked from the top of the document. We will also add an implementation report. 
https://github.com/w3c/browser-payment-api/issues/560

> Deadline for comments: @adrianba sent a link to a static spec with a CR End date of
2017-10-31. I'm not sure the WG discussed that yet.

The logic was to get everything done for TPAC. Feel free to discuss with the WG. The Editors feel it is sufficient time, but happy to hear alternatives. 

> Features at risk. I've requested addition of an id to be able to link directly to them:
#559

Thanks! Left some comments.

**Comment by ianbjacobs** [comment]
@marcoscaceres,

Regarding the comment end date of 2017-10-31: I will mention it at this week's meeting, and people can comment on it if they want during the CfC review period.

Ian

**Comment by marcoscaceres** [comment]
Closing this, as all that is left if #598.
