### ISSUE TITLE
shippingOption description is misleading

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#534]
Spec says: 

> A PaymentRequest's shippingOption attribute is populated when the user chooses a shipping option. It is null by default. When a user chooses a shipping option, the shipping option changed algorithm runs.

This is not really true. It can be set during construction. It's only null if there was no selected shipping option.

**Comment by bentian** [comment]
Spec should also specify for _PaymentShippingOption.selected_ since 'display by default' does not necessarily mean 'assign to _request.shippingOption_ during construction'.

> This is set to true to indicate that this is the default selected PaymentShippingOption in a sequence. User agents should display this option by default in the user interface.

**Comment by marcoscaceres** [comment]
This is actually true now thanks to https://github.com/w3c/payment-request/pull/610! :)
