### ISSUE TITLE
canMakePayment() needs to match .show()

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#535]
We need to make sure `canMakePayment()` matches `show()` with respect to how .data is checked in `.show()`. We should make a note about IDL conversions that can take place there and be clear that IDL violations result in "false".

**Comment by zkoch** [comment]
@marcoscaceres, @adrianba and I thought you really wanted this one

**Comment by marcoscaceres** [comment]
You guys are the kindest people I know 🎁 ... 💥.

**Comment by ianbjacobs** [comment]
See pull request:
 https://github.com/w3c/payment-request/pull/682
