### ISSUE TITLE
updateWith() "InvalidStateError" DOMException

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#544]
@domenic, in `updateWith()` step 2-4, are: 

> 2. Let request be the value of event's target attribute.
> 3. If request is not a PaymentRequest object, then throw a TypeError.
> 4. If the dispatch flag is unset, then throw an "InvalidStateError" DOMException.

It seems impossible to ever throw in 4 because an event's `.target` cannot be set without dispatching the event through another object (thus the dispatch flag is set). 

If we want to catch 4, we would need to swap it with 3. So:

```JS
const ev = new PaymentRequestUpateEvent("test");
ev.updateWith(Promise.resolve({})); // would throw InvalidStateError, not TypeError.
```

However, that seems slightly pointless - unless there is precedence in the platform to do that. 

WDTY? Swap 3-4, or just delete 4?

**Comment by domenic** [comment]
Yep, you're right. I don't have a strong preference on which way we fix this; if we delete 4, then it comes down to how friendly the error message is for 3, which is a quality of implementation issue. I guess less code seems better, so I'd default to deleting it.

**Comment by vinniespina** [comment]
Question and concern
