### ISSUE TITLE
Unstrusted events can update PaymentRequest

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#546]
Unless I've missed something, it seems one can co-opt and untrusted event to do the work of a trusted event*:

```JS
const request = new PaymentRequest(defaultMethods, defaultDetails);
const untrustedEvent = new PaymentRequestUpdateEvent("test"); 
request.dispatchEvent(ev); // set .target
request.show();
request.onshippingaddresschange = () => {
  const update = {
    total: {
      label: "Untrusted",
      amount: {
        currency: "USD",
        value: "1111.00",
      },
    },
  };
  untrustedEvent.updateWith(Promise.resolve(update));
};
```
We might just need to say in `.updateWith()` that if the event is untrusted, throw a `SecurityError` or `NotAllowedError`.

*Chrome ignores this.

**Comment by domenic** [comment]
Great catch. Related issue: https://github.com/w3c/ServiceWorker/issues/1040. I do believe checking isTrusted is the right thing to do here, now that we've clarified that it's automatically set for all UA-dispatched events.
