### ISSUE TITLE
WebIDL serializer has been deprecated in favor of toJSON operation

### ISSUE THREAD

**Issue by tobie** [w3c/browser-payment-api#555]
Hi!

We recently [deprecated WebIDL serializers][0]. You can now directly specify [toJSON operations][1] instead, which you previously weren't allowed to do.

To deal with common cases, we added a new [\[Default\] extended attribute][2] which triggers the [default toJSON operation][3] that behaves similarly to how `serializers={attributes}` or `serializers={attributes, inherit}` used to. That is, it serializes all attributes that are of a [JSON type][4] into a vanilla JSON object.

It seems the following interfaces in this spec are impacted by this change:

- [x] [`PaymentAddress`](https://w3c.github.io/browser-payment-api/#paymentaddress-interface)
- [x] [`PaymentResponse `](https://w3c.github.io/browser-payment-api/#paymentresponse-interface)

Both seem to be good candidate for the [default toJSON operation][3]. The below should be all you need:

```webidl
[SecureContext]
interface PaymentResponse {
  [Default] object toJSON();
  // ...
};

[SecureContext]
interface PaymentAddress  {
  [Default] object toJSON();
  // ...
};
```

I'm sorry for the inconvenience this causes, but our hope is that this ultimately makes things a lot simpler and clearer for everybody.

Please feel free to reach out if you have any questions.

Thanks!

[0]: https://github.com/heycam/webidl/commit/a505f33
[1]: https://heycam.github.io/webidl/#idl-tojson-operation
[2]: https://heycam.github.io/webidl/#Default
[3]: https://heycam.github.io/webidl/#es-default-tojson
[4]: https://heycam.github.io/webidl/#dfn-json-types

**Comment by marcoscaceres** [comment]
@tobie, can you check if https://github.com/w3c/browser-payment-api/pull/556 is all good?
