### ISSUE TITLE
UX guidance article

### ISSUE THREAD

**Issue by mustafa-x** [w3c/browser-payment-api#558]
Hi all

I just wrote a post on the Google Developers blog about [UX design considerations with PR API](https://developers.google.com/web/fundamentals/discovery-and-monetization/payment-request/payment-request-ux-considerations)

Let me know your thoughts and additions. Also I added a stickersheet so designers could explore the flows some more in Sketch, it is Chrome only but if other browser vendors were interested we could be a repo will all of them together.

**Comment by marcoscaceres** [comment]
Nice one, @mustafa-x! I've forwarded this to the WG's mailing list and asked them to provide feedback here. Will leave this open for a bit to give you a chance to gather feedback. 

In the future tho, it might be best to go directly to the mailing list and provide a link directly to the Google Web Fundamentals repo. That way, we keep things separate.

**Comment by mustafa-x** [comment]
Hi @marcoscaceres 
Sorry, didn't realise there was a mailing list. Ill do that in the future :)

**Comment by marcoscaceres** [comment]
no problem at all - we prefer github over mailing list for most things.

**Comment by ianbjacobs** [comment]
Thanks @mustafa-x! I have linked to the guide from the "developer guides" section of the web payments portal we are populating:
 https://github.com/w3c/payment-request-info/wiki/DeveloperGuides

I look forward to reviewing the material.

Ian

**Comment by mustafa-x** [comment]
Many thanks!

**Comment by marcoscaceres** [comment]
Closing, as it's moved to Washington Wiki.

**Comment by marcoscaceres** [comment]
Arrgghh... autocorrect and 📱
