### ISSUE TITLE
Populate implementation report

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#560]
Once we are in CR, and more tests get added, we will need to periodically generate an implementation report. 

We can use [wptreport](https://www.npmjs.com/package/wptreport) to generate it.

**Comment by marcoscaceres** [comment]
Stub is in place. https://w3c.github.io/browser-payment-api/reports/implementation.html

Will work with @sideshowbarker to get it populated.

**Comment by marcoscaceres** [comment]
@sideshowbarker, what's the relationship between the above and the "(not very useful yet)" Dashboard: https://wptdashboard.appspot.com/payment-request

**Comment by marcoscaceres** [comment]
(Ideally, the dashboard would be the implementation report at some point, right?.... is that going to happen, or should we just populate "[implementation.html](https://w3c.github.io/browser-payment-api/reports/implementation.html)" for now?)

**Comment by sideshowbarker** [comment]
> what's the relationship between the above and the "(not very useful yet)" Dashboard: https://wptdashboard.appspot.com/payment-request

No relationship. They serve some of the same purposes. The dashboard is clearly better in that it is populated automatically, whereas anything we do with wptreport is manual at this point. One thing that dashboard lacks is the specialized report pages that wptreport does that show tests which are passing only in one UA (`less-than-2.html`) and in no UAs (`complete-fails.html`).

By the way the canonical URL for the dashboard is now http://wpt.fyi/

> (Ideally, the dashboard would be the implementation report at some point, right?....

Yes

> is that going to happen,

It is going to happen eventually but not super soon

> or should we just populate "implementation.html" for now?)

Yeah in the mean time we should maintain our own report using wptreport

**Comment by marcoscaceres** [comment]
From @sideshowbarker, need to start doing:

> Run:
> http://web-platform.test:8000/tools/runner/index.html 
> Enter `/payment-request` under *Run tests under path*, then after all the 
> tests have run, you’ll see a *Download JSON results* button. Push that 

And then use: https://www.npmjs.com/package/wptreport

**Comment by marcoscaceres** [comment]
Being populated manually, so closing :)
