### ISSUE TITLE
PaymentItem.pending can be true, but transaction can "complete"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#571]
Is any implemeter supporting "pending" in any meaningful way (i.e., in their UIs)? 

If not, we should mark it "at risk".

**Comment by rsolomakhin** [comment]
Chrome on Android makes "pending" line items have slightly lighter text color.

**Comment by marcoscaceres** [comment]
I don't know what we will do with this in Firefox. I'm concerned this will confuse users - maybe, the spec should prevent pressing "Pay"until all `PaymentItem`s are no longer pending: otherwise, the total risks being deceptive. 

@zkoch, thoughts?

**Comment by marcoscaceres** [comment]
@adrianba, do you do anything in Edge?

**Comment by zkoch** [comment]
Few thoughts:

* Apple also has support for "pending" types, so we added this to be closer to Apple's API.
* I do think there's value here. IMO, line items shouldn't change, just the values they have should change. For example, if you have the following:

Subtotal: 5.00
Tax: 1.00
Shipping _pending_

This helps set user expectations that the total price is not reflective at the moment and will be updated after some event (that hopefully makes sense to them given the label of the line item).

* I don't think we should enforce UI constraints around "Pay" buttons active/disabled state. I can imagine scenarios where pending is actually valuable even at time of "payment". For example, authorizations in general.

**Comment by marcoscaceres** [comment]
Thanks, I wasn't aware Apple supported this - I'll see how they handle it. 

However, I'm confused by "shipping pending", as shipping options can't be pending? 

On reflection, agree about not putting the constraints on "pay". Will talk to our UX/UI team.

**Comment by zkoch** [comment]
The shipping price can be pending until you select a shipping address/option combo. :)

**Comment by marcoscaceres** [comment]
> The shipping price can be pending until you select a shipping address/option combo. :)

Yep, got that - as it's an invariant in the spec that the `onshippingaddresschange` will fire, hence it has an way to enter a stable state. Where there is no shipping involved, I am left wondering how a `displayItem` then becomes `pending: false`?    

It's a super edge case... but an somewhat annoying one.

**Comment by marcoscaceres** [comment]
Ok, here is the Apple one:
https://developer.apple.com/documentation/applepayjs/applepaylineitem/1916084-type

> Note that if a line item's type is pending, the Apple Pay payment sheet does not display the value in amount, and instead displays "pending".

**Comment by marcoscaceres** [comment]
@hober, given that `DisplayItem.pending` seems to have been added for ApplePay compat, can Apple Pay complete a payment if an item is "pending"? Do you have any thoughts on pending based on the above or below?

For record keeping purposes, just adding this test case (where a payment can be completed):

```JS
const response =  await new PaymentRequest( 
  [ 
    { 
      supportedMethods: "basic-card", 
    }, 
  ], 
  { 
    displayItems: [ 
      { 
        label: "This is pending ... it could be lots more", 
        pending: true, 
        amount: { currency: "USD", value: "0.6"}, 
      }, 
    ], 
    total: { 
      label: "Total", 
      amount: { currency: "USD", value: "1.2" }, 
    }, 
  } 
).show();
// The pending item never changed false. 
response.complete("success");
```

**Comment by zkoch** [comment]
FWIW, this doesn't seem any worse to me than a set of line items that don't properly add up to the total.

**Comment by marcoscaceres** [comment]
True that.
