### ISSUE TITLE
Support for "redirected" payment providers like PayPal, iDEAL/NL,Direktbetalning/SE etc

### ISSUE THREAD

**Issue by cyberphone** [w3c/browser-payment-api#573]
It is not obvious to me how you can deal with one-of-a-kind payment methods which redirects you to a specific server using an URL holding proprietary payment request data.

https://www.ideal.nl/demo/en/?screens=dskweb

**Comment by rsolomakhin** [comment]
I recommend such payment providers to implement the [payment handler](https://w3c.github.io/payment-handler/) spec and use [`PaymentRequestEvent.openWindow()`](https://w3c.github.io/payment-handler/#openwindow()-method) to open their pages instead of redirection.

**Comment by ianbjacobs** [comment]
Because this is not a concrete issue about the Payment Request API, I am closing this issue.

I have added some information to answer this question to the Payment Method Good Practice wiki:
 https://github.com/w3c/payment-request-info/wiki/PaymentMethodPractice#openwindow-instead-of-redirects

Ian

**Comment by cyberphone** [comment]
Would it be possible creating a repository for implementers where you may be able to put "dumb" questions like how you do this and that using W3C Payment Technology?

**Comment by ianbjacobs** [comment]
This is our developer portal:
 https://github.com/w3c/payment-request-info

See in particular the FAQ, code examples, and intros.

As part of tracking these threads I (and others) enhance those resources.

(Aside: I expect that as the portal becomes useful, we will endeavor to make it
even more usable, but beautifying it is not the current top priority. )

Ian
