### ISSUE TITLE
Dealing with "other" payment methods

### ISSUE THREAD

**Issue by cyberphone** [w3c/browser-payment-api#580]
I don't have a specification to offer at this stage so regard this request as something that may or may not have a reasonable solution.  The core problem is that there's quite a bunch of methods which aren't covered by the current set of specifications including:

- PayPal
- Schemes using an external mobile device as "payment method" to a desktop browser session.  This method is gaining traction and effectively you already have it in Alipay using QR code as invocation method

My question is simply if you feel that it would be _worthwhile_ looking into a possible (user-friendly) way to register external methods so that they would show up in the GUI.  This is by no means perfect but the workaround (offering a button for "other methods") isn't that great either.

This is particularly an issue on the desktop side which probably won't be supported by native payment applications to the same extent as for example Android.

An external method would only return the selected method leaving the execution to subsequent steps performed by the merchant in similarity to "basic cards".

**Comment by marcoscaceres** [comment]
Please watch Zach' IO talk:  
https://youtu.be/hU89pPBmhds

It's all answered there. I think we already solve everything above.

**Comment by marcoscaceres** [comment]
(skip to 28 mins to see the PayPal bit! It's awesome)

**Comment by cyberphone** [comment]
I find no support for what I asked about in the mentioned presentation at 28 min (it deals with third party native Android payment app integration).  Later in the presentation Zack mentioned that Google is working with PayPal to create a (presumably) proprietary integration solution which also seems like an entirely different thing.

**Comment by webpayments-specs** [comment]
Hi Anders, you might want to watch again. :) In that presentation I, along
with Max and Jiajia from AliPay, talk about the following:

* Opening up the third party ecosystem for native payment apps
* Opening up the third party ecosystem for web-based payment apps
* PayPal will be working with us to build a web-based payment app, *based
on the WG's PaymentHandler API*

So I do think everything you're asking for is covered.

-Zach
