### ISSUE TITLE
[architecture] Use "user agent", not "browser"

### ISSUE THREAD

**Issue by halindrome** [w3c/browser-payment-api#59]
W3C specifications talk about user agents typically.  A "browser" is one type of user agent, but there are others.  This architecture should extend to some / most / all of those.

**Comment by msporny** [comment]
I don't think the architecture document is about anything but the browser. At least, it doesn't read that way to me. The other architecture document (that @adrianhopebailie worked on) and the one that Pat Adler worked on in the IG is about user agents, though. We need to sort out exactly what architecture we're talking about w/ the architecture spec.

**Comment by halindrome** [comment]
I agree that this document is specifically about the payment api as it is reflected in browser-like environments.  I just want to believe that it is possible to support the architecture in other sorts of user agents (e.g., a mobile application with in-application payments should be able to access this interface / environment.)  After all, any UX related to this API is at the "chrome" level of the environment.  That should be accessible from user-space application that is acting as the agent between a user and whatever they are doing.  A good example would be the shopping app from newegg.  When I am in there and press buy, I want to use my chosen "wallet" to select payment instruments, provide shipping address, whatever.

**Comment by msporny** [comment]
I'm pretty sure you and I agree on what the architecture document /should/ talk about, @halindrome. I'm just pointing out that there is currently a fairly decent disconnect on the purpose of that document (whether it's talking about user agents, or it's talking about browsers). I'm claiming it's the latter, even though I agree that it should be talking about user agents (and thus the document should have a broader scope).

That, or we keep that documents narrow scope, but make sure it's clear that we're only talking about browser payment architecture (and that architecture might deviate from the broader user agent payment architecture).
