### ISSUE TITLE
Third party Method not recognized- why

### ISSUE THREAD

**Issue by biseraivanovska** [w3c/browser-payment-api#593]
Hi, 

Since Google supports using payment request api to pay with third party methods, I followed the instructions from 
- https://www.xda-developers.com/google-officially-adopts-the-payment-request-api-allowing-you-to-pay-with-3rd-party-apps-in-chrome/
- https://developers.google.com/web/fundamentals/discovery-and-monetization/payment-request/deep-dive-into-payment-request#defining_supported_payment_methods

but mine method fails when I call request.canMakePayment(). I guess the payment method is not recognized.

On the other hand, there are two examples provided with Alice and Bob pay (respectively), I also tried to implement them, but with no success.

What am I missing? Can you give me a hint?

Thanks in advance,
Bisera

**Comment by marcoscaceres** [comment]
@biseraivanovska unfortunately, we can't assist with developer questions here. I'd recommend you contact @gauntface directly on Twitter - he is super nice and I'm sure he would be willing to help you out and improve the docs.

**Comment by cyberphone** [comment]
@biseraivanovska I have already got an answer on this:
https://github.com/madmath/payment-request-show/issues/13#issuecomment-317460376

**Comment by rsolomakhin** [comment]
I'm happy to review implementations and offer advice for integrating 3rd party payment apps.
