### ISSUE TITLE
PaymentAddress attribute definition is wrong

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#601]
Spec currently says: 

> This is the [CLDR] (Common Locale Data Repository) region code. For example, US, GB, CN, or JP.

This should actually be ISO 3166-1 alpha-2 codes. 

It should also state that the user agent needs to convert the code to upper case.

**Comment by marcoscaceres** [comment]
Also, I can't find any "[CLDR] (Common Locale Data Repository) region code"? The CLDR is very badly organized and hence "region code" could basically mean anything. 

Any idea who was responsible for suggesting this?

**Comment by ianbjacobs** [comment]
Hi Marcos,

I believe this came from:
 https://github.com/w3c/payment-request/commit/075a2759214469085db87fac2a3a974d04429c71

@rsolomakhin, @zkoch, and @adrianba can you confirm you are ok with changing this reference?

Ian

**Comment by rsolomakhin** [comment]
> I can't find any "[CLDR] (Common Locale Data Repository) region code"

You can see the list of region codes at http://unicode.org/cldr/charts/31/supplemental/territory_containment_un_m_49.html, for example.

> This should actually be ISO 3166-1 alpha-2 codes.

We went with CLDR instead because CLDR is updated more frequently. @lararennie and @roubert: Do you have any examples of where CLDR is better than ISO 3166-1?

**Comment by roubert** [comment]
The important difference between CLDR and ISO is that CLDR guarantees non-reuse of codes, while ISO does not, so CLDR codes will be stable over time while an ISO code might take on a new meaning in the future.

**Comment by marcoscaceres** [comment]
How often do the ISO codes change tho? It seems extremely edge-casey. 

Also, from a dev perspective (and from someone trying to test and implement this) I couldn't find the codes in the mess that is the Unicode site. 

I don't imagine average developers would have much luck finding those either, hence I'm more inclined to cite ISO.

**Comment by marcoscaceres** [comment]
(On the flip side, I wouldn't mind not citing ISO because their specs are neither free nor open: we have to rely on Wikipedia to get the country list... so I could be convinced to cite the CLDR so long as we point to the actual chart and use the correct terminology: "2-letter county code listed in the Territory Containment Table")

**Comment by adrianhopebailie** [comment]
> I wouldn't mind not citing ISO because their specs are neither free nor open: we have to rely on Wikipedia to get the country list

Enough justification for me

**Comment by marcoscaceres** [comment]
The problem is that CLDR cites the [UN list](https://unstats.un.org/unsd/methodology/m49/), which itself cites the ISO list (but uses the 3-letter codes, but that's fine). 

The other problem with the CLDR chart is that it's version dependent (e.g., 31). 

Lastly, I made another attempt today to find my way to the territories chart, and failed. I can't cite something that is nearly impossible to reach/find, and that also changes from one version to another (because obviously we can't lock ourselves to a particular version).

**Comment by rsolomakhin** [comment]
Can we write this?

> The country code is the latest version of CLDR region code, for example [v31](http://unicode.org/cldr/charts/31/supplemental/territory_containment_un_m_49.html).

I've filed an [issue against CLDR](https://unicode.org/cldr/trac/ticket/10621) to address your concern of ease of use.

**Comment by marcoscaceres** [comment]
Let me look into this a little bit more. We don't want to get into a WebSQL/SQLite situation - where versioning literally killed that whole effort (won't obviously happen here, because this is a tiny thing - but it smells similar).

**Comment by rsolomakhin** [comment]
See also a wealth of information at http://unicode.org/cldr/trac/browser/trunk/common/supplemental/supplementalData.xml

**Comment by rsolomakhin** [comment]
@marcoscaceres: The CLDR maintainers on http://unicode.org/cldr/trac/ticket/10621 are suggesting that we use http://www.unicode.org/cldr/charts/latest/supplemental/territory_containment_un_m_49.html. Does that work?

**Comment by marcoscaceres** [comment]
@rsolomakhin unfortunately, no, for the reason I gave above. So, it's totally correct to *implement* with the CLDR (we do the same in Gecko). But citing the CLDR is still not right for the spec for the two reasons I gave:

1. The CLDR cites "[Standard country or area codes for statistical use (M49)](https://unstats.un.org/unsd/methodology/m49/)" (and takes the Alpha-2 codes from ISO, as far as I can tell)
1. M49 cites ISO 3166-1 for the codes. 

Thus, 3166-1 is the authoritative source for the codes, even if CLDR is how those codes are derived (which is an implementation detail). 

@adrianhopebailie, [ISO finally came to its senses](https://www.iso.org/new-way-of-using-iso-3166.html) and made the language codes available in multiple formats and searchable: https://www.iso.org/obp/ui/#search

**Comment by marcoscaceres** [comment]
Added link to M49 above.

**Comment by marcoscaceres** [comment]
Going back over everything, I'm still convinced that ISO 3166-1 is the correct standard to cite here (even if the implantation is powered by CLDR).

@rsolomakhin, I'm happy to discuss further tho if I'm misunderstanding.

**Comment by rsolomakhin** [comment]
Sure, ISO it is. The link is https://www.iso.org/obp/ui/#search/code/, btw.

**Comment by rsolomakhin** [comment]
(As long as using CLDR for implementation is still correct.)

**Comment by rsolomakhin** [comment]
@marcoscaceres Did you see that CLDR has addressed your comment about clarity of their region code list?

http://unicode.org/cldr/trac/ticket/10621#comment:11

**Comment by adrianhopebailie** [comment]
@marcoscaceres happy for you implementors to figure this out as long as we don't cite anything that's not publicly accessible.

**Comment by marcoscaceres** [comment]
> (As long as using CLDR for implementation is still correct.)

It is :) Don't worry. I'm pretty sure we (Moz) will also use the CLDR to derive the language code. 

> @marcoscaceres Did you see that CLDR has addressed your comment about clarity of their region code list?

Yes, that was helpful. 

> @adrianhopebailie, happy for you implementors to figure this out as long as we don't cite anything that's not publicly accessible.

We are all good on that regard.
