### ISSUE TITLE
PayerAddress.phone and PayerResponse.payerPhone

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#606]
We should explicitly set `PayerAddress.phone` to empty string when `requestPayerPhone` is false. 

Otherwise, it can leak through accidentally in #603.

**Comment by rsolomakhin** [comment]
I don't see `PayerAddress` in the spec. Can you elaborate on this?

**Comment by marcoscaceres** [comment]
Sorry, "PaymentAddress" I mean. Been looking at this spec for too long.

**Comment by rsolomakhin** [comment]
Shipping address phone number may be required for the carrier to resolve delivery problems. If you're shipping something as a gift, then the shipping address phone number may not be the same as the payer phone. Therefore, I believe that `requestPayerPhone` should not affect `PaymentAddress.phone`.

**Comment by marcoscaceres** [comment]
I see. I'd still like to somehow make it clear the a user's phone number doesn't accidentally get leaked tho.

**Comment by zkoch** [comment]
I agree with Rouslan. I'm not sure I see the issue here. A phone number is part of a shipping address. The user will have to select this for it to get passed back to the merchant. This, to me, is WAI.

**Comment by marcoscaceres** [comment]
Agree. They are separate things that sometimes overlap.
