### ISSUE TITLE
If requestShipping is false, pr.shippingOption should be null

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#609]
During testing, a weird case came up. 

If you have:

```JS 
const options = {
   requestShipping: false
};

const someShippingOption = {
   id: "never-selected",
   selected: true,
  // other props 
};

const details = {
   //... things
   shippingOptions: [someShippingOption]
}

const pr = new PaymentRequest(methods, details, options); 
console.assert(pr.shippingOption === "never-selected");
```

That seems bad. If no shipping was requested by the merchant, then the selected shipping option should actually be `null`, no? Even if the merchant screwed up and added shipping options that can't ever actually be selected by the end user (there is no UI to make the selection).

**Comment by marcoscaceres** [comment]
Tried to clarify the above issue a bit more.

**Comment by marcoscaceres** [comment]
This is the actual test that shows this special handling:
https://github.com/w3c/web-platform-tests/pull/7239/files

**Comment by marcoscaceres** [comment]
Note that `response.shippingOption` will be `null` - so this is correctly handled on the `response` side.

**Comment by marcoscaceres** [comment]
I also noticed that `.updateWith()` actually has this check too - so this is definitely a spec bug.

**Comment by marcoscaceres** [comment]
To be clear:

```JS
ev.updateWith({
   // updating with new shipping options would leave pr.shippingOption === "never-selected" 
   shippingOptions: [{id: "THIS_IS_NEVER_SELECTED" , selected: true}]
});
```

**Comment by rsolomakhin** [comment]
I agree with your reasoning, @marcoscaceres
