### ISSUE TITLE
Decide on currencySystem

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#617]
The currencySystem is marked at risk. We need to check at the end of CR period if has implemented it.  If not, we need to remove it.  

To date (March 22, 2018), no one implements support for it.

**Comment by marcoscaceres** [comment]
Blocked on https://github.com/w3c/web-platform-tests/issues/7369

**Comment by marcoscaceres** [comment]
@ianbjacobs, @adrianhopebailie, should we start a CFC for this? 

I think currency system may make a return in the future - but we might need to think them out a bit more.

**Comment by ianbjacobs** [comment]
@marcoscaceres, let's mention this at today's call (at least).
Ian

**Comment by ByteEater-pl** [comment]
> I think currency system may make a return in the future

Yea, definitely! A centralized registry won't be able to keep up with DeFi and proliferation of monetary units (whether you call them currencies or not) like cryptocurrencies, credits in barter systems, game currencies, currencies of new states and smaller territories or issuers not tied to some level of government (e.g. there used to be hundreds of privately issued currencies in USA and UK in the 19th century), extraterrestrial currencies (keep in mind that space is 3D, unlike the Earth's surface) and other wonderful stuff. And ISO contemplating four-digit codes just seems to indicate how clueless they are (unless it's a deliberate measure to hinder DeFi, but let's not assume malice without solid premises) – 456976 is clearly an insufficient limit.
