### ISSUE TITLE
Make iframe allowpaymentrequest normative 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#618]
The spec depends heavily on HTML iframe's `allowpaymentrequest` attribute, so the reference to it should be normative. 

I've linked the tests to the spec (and the tests are part of the official test suite), so lets make it official.

**Comment by domenic** [comment]
It's already normative in the PaymentRequest() constructor, where it matters. The section at https://w3c.github.io/payment-request/#paymentrequest-and-iframe-elements is just a non-normative summary of the actual normative requirement at https://w3c.github.io/payment-request/#constructor .

So I think this should is fine as-is.

**Comment by marcoscaceres** [comment]
Yeah, agree looking at it again now.
