### ISSUE TITLE
Documentation error? 55 + 5 = 65

### ISSUE THREAD

**Issue by edent** [w3c/browser-payment-api#622]
"2.2 The details argument" shows

            displayItems: [
              {
                label: "Sub-total",
                amount: { currency: "USD", value: "55.00" },
              },
              {
                label: "Sales Tax",
                amount: { currency: "USD", value: "5.00" },
              },
            ],
            total: {
              label: "Total due",
              amount: { currency: "USD", value: "65.00" },

https://github.com/w3c/payment-request/blob/gh-pages/index.html#L288

If my mathematic reasoning is correct, 55+5=60.  Or have I misunderstood what the code is trying to say?

**Comment by marcoscaceres** [comment]
Just realized the $5 comes from the selected shipping option. But it was wrong not to have a comment not explaining that.
