### ISSUE TITLE
Handling Digital Assets (i.e. Bitcoin and Ethereum)

### ISSUE THREAD

**Issue by paranoid-android** [w3c/browser-payment-api#635]
I was looking to use the Payment Request API to accept Bitcoin and Ethereum. However, it looks like the API is focused on pulling money via a credit card. Yet, Bitcoin and Ethereum are focused on letting users "push" money. This is one way they promote privacy.

In my opinion, I think digital assets should be supported in the payment request API. For example, if a developer chose "crypto" as a `supportedMethod`, the experience of the Payment Request dialog | card should change. I would imagine a QR code appearing. Or, letting a user choose a crypto wallet. 

Please consider adding support for crypto assets to the Payment Request API.

**Comment by ianbjacobs** [comment]
Hi @paranoid-android,

The API will support a variety of payment methods, including push payment methods. We look forward to members of the group working on cryptocurrency payment methods, which may be used with Payment Request API. As this is not an issue on the Payment Request API itself, I am closing this issue.

To track what work we are actively developing, see:
 https://github.com/w3c/webpayments/wiki

Ian
