### ISSUE TITLE
Allow default option for donation in PaymentShippingType

### ISSUE THREAD

**Issue by billhannah** [w3c/browser-payment-api#638]
If this API is used for accepting donations (for example, a 501.3c organization is the US), the default delivery options do not make sense as no goods are being exchanged. It is not clear if we can avoid using the default `PaymentShippingType` ENUM and replace it with a custom option (instead of adding to the end of the default list).

**Comment by rsolomakhin** [comment]
Why does a donation need a shipping address?

**Comment by billhannah** [comment]
Sorry, can you avoid displaying the Shipping Type? I just started reviewing this today for my organization and I haven't gotten through all the details. From the UX page at Google it suggested that all the details would be displayed

**Comment by billhannah** [comment]
Found it - it is optional. Thank you for your response. Closing

**Comment by rsolomakhin** [comment]
Always happy to help. Please don't hesitate to reach out with any questions.
