### ISSUE TITLE
Is browser support for PR API configurable?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/browser-payment-api#642]
Hi all,

I believe browsers allow users to turn off autofill. Are browsers planning to implement a similar switch for PR API support so that users of computers in public settings (library, at work) do not inadvertently store sensitive information?

Ian

**Comment by rsolomakhin** [comment]
Chrome has the option to not save the credit card when paying via PaymentRequest on Android. Similar feature is coming to desktop soon as well.

**Comment by ianbjacobs** [comment]
Thanks, @rsolomakhin!

@marcoscaceres, @molly26dalton I would also be interested hearing about your implementations.

Ian

**Comment by marcoscaceres** [comment]
Ours is also configurable- there is a checkbox at checkout time that says “don’t save my card details”.

**Comment by dontcallmedom** [comment]
@marcoscaceres I think @ianbjacobs 's question was about making it impossible for a specific browser configuration to save any card details (rather than relying on the user to check the "don't save" box).

**Comment by marcoscaceres** [comment]
Ah, I think it's possible by disabling autofill via settings, by unchecking "Remember logins and passwords for websites" maybe?.  It's all coming out of the same autofill database. 

@mnoorenberghe, can you confirm?

**Comment by mnoorenberghe** [comment]
I think there is some confusion in this thread but Firefox will have a checkbox to save the profile (unchecked by default) during the PR flow. Given that our checkbox will be unchecked by default, I don't think we'd need any preference toggle. I'm not sure how we will handle Private Browsing yet.

**Comment by marcoscaceres** [comment]
Closing, as I think the question was more or less answered. This question applies to basically any API, "can I turn off API X?". Answer is, "maybe depends".

**Comment by 719media** [comment]
@rsolomakhin do you have any additional details in regards to chrome allowing payment request api to not save sensitive data? we are looking at integration of payment request api, and this is one of the problems we ran into: browser supports payment request api, but user is on a public (e.g. library) computer. Even though this scenario may be considered "uncommon", it's the sole reason we still have to support legacy checkout when the browser supports payment request api.
