### ISSUE TITLE
Add way to update `total` and `displayItems` after `.show()` but before user interaction

### ISSUE THREAD

**Issue by jenan-stripe** [w3c/browser-payment-api#645]
This is related to but different from #639.

Some users have reported to us that they may not know the total or line items at the time of attempting to open the payment sheet with `show()` -- there may be asynchronous server-based logic yet to be resolved.

Apple Pay provides an unrelated API that users can repurpose to work around this: if you listen for [onpaymentmethodselected](https://developer.apple.com/documentation/applepayjs/applepaysession/1778013-onpaymentmethodselected), you can get a loading state when the sheet opens and then asynchronously update the total and return control to the sheet. We have at least one user that has been relying on this behavior with Apple Pay.

Is it worth adding a way to signal that the browser should show a spinner or equivalent and wait to allow end user interaction until an update? The alternative is for Payment Request implementors to block the end-user action (not great) or show a manually-created loading modal (probably also not great).

**Comment by michelle** [comment]
(I work with @jenan-stripe.)

> The alternative is for Payment Request implementors to ... show a manually-created loading modal (probably also not great).

It's worth noting that this workaround is not ideal, because `show()` may not always be callable without a user gesture. Thus, this method is not guaranteed to work across all browsers. This is allowed for by the spec:

> For example, the user agent may require the call to be triggered by user activation

**Comment by rsolomakhin** [comment]
Something that could work:

```webidl
interface PaymentRequest { 
  Promise<PaymentResponse> showWithLoadingScreen(Promise<PaymentDetails>);
}
```

Example usage:

```javascript
const pr = new PaymentRequest(/* ... */);
if (pr.showWithLoadingScreen) {
  pr.showWithLoadingScreen(new Promise((resolve, reject) => {
    const updatedDetails = /* ... */;
    resolve(updatedDetails);
  }).then(handlePayment).catch(handleError);
} else {
  pr.show().then(handlePayment).catch(handleError);
}
```

**Comment by michelle** [comment]
That would work, although I think “loading screen” is a bit specific. The promise management for the user here is also a bit tricky — if the merchant is trying to update greedily, they will need to store a reference to the promise corresponding to their last update. How about something like this:

```js
    let pr = new PaymentRequest(/* ... */);
    const updatePromise = fetchDisplayItemsAndTotal();
    
    if (pr.update) {
      pr.update(updatePromise); // this is a new API.
    }
    
    // later on...
    pr.show().then(handlePayment).catch(handleError); // this shows the payment sheet in a loading  state if one of the update promises hasn't resolved yet.
```

This is a nice developer experience because it detaches updates from the `show()` API, which has pretty clear semantics. The update API could have its own error messages.

The merchant can also call update as much as they’d like as the interface changes (as they do today), and the user agent can handle races between `update` resolution (likely preserving the last update only).

Another alternative is to mirror the other events that PaymentRequest emits and emit a `initialize` (exact naming TBD) event that the user can call `ev.updateWith(updatePromise)` on. This has the same promise management issue that the proposed API has, but is a more familiar API for the merchant.

**Comment by rsolomakhin** [comment]
Can the `initialize` event also be used to solve the use case of a _merchant validation_ event?

**Comment by marcoscaceres** [comment]
> It's worth noting that this workaround is not ideal, because show() may not always be callable without a user gesture.

I don't think there is a requirement on user gesture... just that the page has focus. Does that help? I don't remember who showed this... but: 

```JS
const pr = new PaymentRequest(method, details, options);
try {
const response = await pr.show(getUpdateTotal()); // show loading until `getUpdateTotal()`'s promise resolves  
} catch(err){}
```

**Comment by marcoscaceres** [comment]
> I don't think there is a requirement on user gesture

Ah, @michelle, you mean like clicking a "buy button" (not browser gated)... would the proposal of using `.show(promise)` above work still? 

I'm thinking the initial `total` would just be set to "0" initially, and the the promise updates it.

**Comment by marcoscaceres** [comment]
WIP pull request https://github.com/w3c/payment-request/pull/668 

Would appreciate review/feedback.

**Comment by marcoscaceres** [comment]
@michelle so, given #655 requiring use activation on .show(), you could still do:

```js
let pr = new PaymentRequest (/*...*/);
const updatePromise = fetchDisplayItemsAndTotal();

// later on...
button.onclick = async ev => {
  const response = await pr.show(updatePromise);
  try {
    // this shows the payment sheet in a loading
    // state.
    handlePayment(response);
  } catch (err) {
    handleError(err);
  }
};
```

Does that work?

**Comment by michelle** [comment]
Yes, that works! (I think the `await` should be in the `try` block, though?)

**Comment by marcoscaceres** [comment]
Yeah, true. Ok, cool. 

Now we need implementer buy-in.

**Comment by aestes** [comment]
WebKit is implementing this: https://bugs.webkit.org/show_bug.cgi?id=182538

**Comment by rsolomakhin** [comment]
Blink is implementing this: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/Lc2qCQgqqqk
