### ISSUE TITLE
Add support for merchant validation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#646]
We need a means to do merchant validation, as per:
https://developer.apple.com/documentation/applepayjs/providing_merchant_validation

However, this is "one and done" event, so it's a good candidate to be a promise. So, sketch:

```JS
const url = await PaymentRequest.validationURL;
await merchantSession = await fetch(myServer + url ).then(r => r.text());
const pr = new PaymentRequest({
  supportedMethod: "apple-pay", 
   data: { merchantSession }
});
await pr.show();  
```

**Comment by rsolomakhin** [comment]
Here's what should happen for the `validationURL`:

```javascript
fetch('/validate?url=' + encodeURIComponent(validationURL))
    .then(onMerchantValidationResult);
```

**Comment by marcoscaceres** [comment]
```javascript
await canMakePayment = PaymentRequest.canMakePayment(methodData);
const pr = new PaymentRequest({
  supportedMethod: "apple-pay", 
});
pr.canMakePayment();
pr.addEventListener('merchantvalidation', (evt) => {
  evt.complete(new Promise((resolve, reject) => {
     return fetch(severUrl + evt.merchantValidationUrl).then((r) => r.text());
  });
});
response = await pr.show(promise(someOtherDetails)); 
let paymentMethod = response.methodName;
try {
  response = await response.complete("retry", {"errorField": "postalCode"});
} catch (error) {
  console.log('retry rejected');
  if (isPush(paymentMethod)) { /* custom logic */ }
}
```


```javascript
registration.paymentManager.retryable = false;
registration.paymentManager.userHint = '$$$';
registration.payentManager.instruments.set(/* ... */);
```

**Comment by aestes** [comment]
I'm generally in favor of this proposal. WebKit will have an implementation challenge with populating the validationURL prior to session start (we aren't told about it until we've started a session and asked to validate by PassKit).

Let me see if we can resolve that on our end.

**Comment by aestes** [comment]
Looks like we can query the validation URL at any time. It's not dependent on there being an active session.

I'm in favor of adopting this approach in WebKit and getting rid of the `applepayvalidatemerchant` event.

**Comment by aestes** [comment]
And unless we think other payment methods will need a merchant validation mechanism, we could avoid PaymentRequest changes entirely by putting the static validationURL property on ApplePaySession rather than PaymentRequest.

**Comment by rsolomakhin** [comment]
@aestes, I would prefer to make this method generic, so that payment handlers have the option of firing the `merchantvalidation` event as well. The code in the payment handler would look like this:

```javascript
const VALIDATION_URL = '...';
const SESSION_ID = '...';
self.addEventListener('canmakepayment', (c) => {
  c.validateMerchant(VALIDATION_URL).then((b) => {
    c.respondWith(b == SESSION_ID);
  });
});
```

The code on the merchant website would look like this:

```javascript

const MERCHANT_SERVER = '...';
paymentRequest.addEventListener('merchantvalidation', (v) => {
  v.complete(new Promise(async resolve => {
    const b = await fetch(MERCHANT_SERVER +
        encodeURIComponent(v.validationUrl)).then(r => r.text());
    resolve(b);
  });
});
```

The overall flow would work like this:

![Generic merchant validation](https://i.imgur.com/6EzrU8f.png)

What do you think? I'm open to suggestions and persuasion: we don't *have* to have a generic merchant validation mechanism if you feel that's right.

**Comment by aestes** [comment]
@rsolomakhin I don't have any objections to this, especially since it works so similarly to merchant validation in Apple Pay JS. I think @marcoscaceres was concerned about using events for things that only happen once, but since your design allows for multiple payment apps to perform validation then an event seems like the right mechanism.

**Comment by aestes** [comment]
@rsolomakhin Should we also add an `onmerchantvalidation` attribute to PaymentRequest, or do you propose only supporting this event through addEventListener()?

**Comment by rsolomakhin** [comment]
@aestes: Yes, it makes sense to add the `onmerchantvalidation` attribute as well to be consistent with the other events.

**Comment by riking** [comment]
Going to state the obvious here and mention that either the merchant-website example code should switch on the method name in the `merchantvalidation` event, or the Merchant Server should check the `validationUrl` query parameter against a whitelist of domains -- else you're landing in mandatory server-side request forgery land.

**Comment by rsolomakhin** [comment]
Good points @riking . I believe *both* server-side and client-side checks should be performed.

**Comment by marcoscaceres** [comment]
Noting WebKit’s implementation https://trac.webkit.org/changeset/226766

**Comment by marcoscaceres** [comment]
Takin this one ... basing on https://trac.webkit.org/changeset/226766

**Comment by marcoscaceres** [comment]
Ok, PR sent #751!
