### ISSUE TITLE
updateWith accepts a details object?

### ISSUE THREAD

**Issue by jdalton** [w3c/browser-payment-api#657]
I noticed the doc note [here](https://www.w3.org/TR/payment-request/#updatewith()-method) *(or [here](https://w3c.github.io/payment-request/#updatewith-method))*:
> If a developer wants to update the payment request, then they need to call updateWith() and provide a PaymentDetailsUpdate dictionary, or a promise for one, containing changed values that the user agent presents to the user.

The bit that's interesting is the a developer may provide a PaymentDetailsUpdate dictionary object *(so not a promise)* but the IDL and the spec steps describe only the `detailsPromise`.

Google dev docs show `updateWith` accepting a vanilla object too  ([here](https://developers.google.com/web/fundamentals/payments/deep-dive-into-payment-request#defining_the_available_shipping_options) and [here](https://developers.google.com/web/fundamentals/payments/deep-dive-into-payment-request#customizing_the_shipping_options_error)).
And Google's implementation appears to accept vanilla objects too.

Does the spec text need to be updated or am I missing something?

**Comment by romandev** [comment]
This case can be helpful to you. (https://github.com/w3c/ServiceWorker/issues/724)

**Comment by marcoscaceres** [comment]
Just to clarify further on @romandev's comment, WebIDL autowraps parameters of promise-accepting methods: so `updateWith(details)` and `updateWith(Promise.resolve(details))` are, from a developer perspective, equivalent.
