### ISSUE TITLE
ShippingAddressChange replaces address every time

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#659]
In the spec, when `shippingaddresschange` fires, the spec queues a task to create a new `PaymentAddress` and replace the old `PaymentAddress` on `request`.

I'm wondering if we should instead have the task update the `request`'s `shippingAddress`'s `PaymentAddress`'s internal slots instead (i.e., don't trash the `PaymentAddress` instance, just update it)?   

The problem I see is a developer holding a reference to `request.shippingAddress`, and then not realizing that it's actually changed with the event.

```JS
var address;
// First "onshippingaddresschange"
request.request.addEventListener("shippingaddresschange", () => {
    address = request.shippingAddress;
  },
  { once: true }
);

// later
request.addEventListener("oshippingaddresschange", () => {
  // ooops! this is now an obsolete reference
  validate(address);
});
``` 

@domenic, thoughts?

**Comment by adrianhopebailie** [comment]
Personally I prefer the current behaviour as that seems consistent with the way most frameworks deal with state.

That said, we don't have an easy way to get the current state of the request so perhaps that is more important: https://github.com/w3c/payment-request/issues/592

**Comment by domenic** [comment]
Basically the question is whether this should be an immutable object or a mutable one. I don't feel strongly either way. In favor of immutable, it's kind of nice to be able to see that it changed by saying `if (request.shippingAddress !== address) { ... }`.

**Comment by marcoscaceres** [comment]
Agree about the immutable aspect. Let's leave it as is.
