### ISSUE TITLE
Add Crypto Currency (BTC, ETH) as supported method

### ISSUE THREAD

**Issue by buhrmi** [w3c/browser-payment-api#661]
Hello,

I was wondering if there is an effort underway to make the Payment Request API work with crypto currency. I think crypto currency is a perfect fit for an API like this, utilizing the user agent to store the private keys of the user (instead of his credit card number), and use it to sign a transaction, send it onto the blockchain, send the transaction hash to the seller. This would work without the need for any payment processor.

**Comment by ianbjacobs** [comment]
Hi @buhrmi,

We have had a number of discussions where we say "Let's work on that" but have not started to do so. Since this issue has come up previously [1] I am going to close this issue and we'll keep track of our progress on 232. Thanks!
Ian

[1] https://github.com/w3c/webpayments/issues/232
