### ISSUE TITLE
Add equivalent of applepaypaymentmethodchanged

### ISSUE THREAD

**Issue by aestes** [w3c/browser-payment-api#662]
WebKit's Payment Request implementation recently [switched](https://trac.webkit.org/changeset/225849/webkit) from the non-standard `applepaypaymentmethodchanged` event to using `PaymentDetailsModifier`s for handling payment instrument changes in Apple Pay. This allows merchants to add additional display items based on the type of card selected by the user.

Right now, Apple Pay supports the following card types: `credit`, `debit`, `prepaid`, and `store`. For the first three types, the only information WebKit provided in `applepaypaymentmethodchanged` was the card type itself, so it's an easy migration to `PaymentDetailsModifier` for these types, e.g.:

```JS
{
    total: {
        label: 'Total',
        amount: {
            currency: 'USD',
            value: '10.00',
        },
    },
    displayItems: [{
        label: 'Item',
        amount: {
            currency: 'USD',
            value: '10.00',
        },
    }],
    modifiers: [{
        supportedMethods: 'https://apple.com/apple-pay',
        total: {
            label: 'Total',
            amount: {
                currency: 'USD',
                value: '15.00',
            },
        },
        additionalDisplayItems: [{
            label: 'Credit surcharge',
            amount: {
                currency: 'USD',
                value: '5.00',
            },
        }],
        data: {
            paymentMethodType: 'credit',
        },
    }],
}
```

However, for `store` cards (private-label credit cards), Apple Pay provided the merchant associated with the card with additional account information in `applepaypaymentmethodchanged` so that they can apply discounts based on factors like "points", premium account status, etc. In the `PaymentDetailsModifier` model, there is no clear way to do this, since the additional display items will differ from customer to customer.

While `PaymentDetailsModifier` will work fine for most use cases involving credit, debit, and prepaid cards, it would be nice to also have a solution in Payment Request for private-label cards.

One solution would be to add a standard `paymentinstrumentchange` event where payment methods can include arbitrary additional information, and use that as a replacement for `applepaypaymentmethodchanged` and in addition to `PaymentDetailsModifier`. I'd be interested to hear if there are other ideas, though.

cc: @marcoscaceres @rsolomakhin

**Comment by rsolomakhin** [comment]
@aestes: Thank you for letting us know about this use case. At this point I can't come up with anything better than what you suggested. This is an important use case, so I'm OK adding it to the spec. The event name `paymentinstrumentchange` sounds fine to me.

**Comment by rsolomakhin** [comment]
@aestes: Would you mind if this event firing was optional for implementers? For example, I would like to not fire this event for `"basic-card"` in Chrome.

**Comment by rsolomakhin** [comment]
@aestes: Do you have examples of some of these discount rules? For example, could we use something like `"premiumAccount": "true"`, `"accountType": "silver"`, or `"pointsAtLeast": "50000"` in `PaymentDetailsModifier.data`?

**Comment by aestes** [comment]
@rsolomakhin I think it's totally reasonable to make this event optional for implementors. I also think it could be optional for authors, since modifiers work in every case other than this one. It'd be sad to make every Apple Pay author respond to this event.

Regarding your suggestion of codifying the discount rules in a modifier, I don't think that would work. WebKit doesn't know anything about the account state. We just provide the merchant with the card PAN and let them look up the account status themselves to compute discounts (n.b. this is privacy-preserving since we have a mechanism to ensure that the merchant is the provider of the store card).

**Comment by rsolomakhin** [comment]
:+1:

**Comment by marcoscaceres** [comment]
@aestes, can you provide us with a bit more details about what a common `paymentinstrumentchange` event looks like? Even if we go with an arbitrary set of information (.e.g., we just have `event.details` being an object), would still be interested to see an example or two.

**Comment by aestes** [comment]
@marcoscaceres sure.

At a minimum, I imagine having a `PaymentInstrumentChangeEvent` that looks like this:

```
interface PaymentInstrumentChangeEvent : Event {
    readonly attribute DOMString methodName; // the payment method that triggered the instrument change
    readonly attribute object details; // payment method-specific details
    void updateWith(Promise<PaymentDetailsUpdate> detailsPromise);
}
```

For Apple Pay, `details` would store an [ApplePayPaymentMethod](https://developer.apple.com/documentation/applepayjs/applepaypaymentmethod). For `credit`, `debit`, and `prepaid` cards, only the `type` field would be populated, e.g.:

```
{
    methodName: 'https://apple.com/apple-pay',
    details: {
        type: 'credit',
    },
}
```

For `store` cards, though, where we've established an association between the card and the merchant domain, we will populate more fields:

```
{
    methodName: 'https://apple.com/apple-pay',
    details: {
        displayName: 'Private Label 9876',
        network: 'Private Label',
        type: 'store',
        paymentPass: {
            primaryAccountIdentifier: '...',
            primaryAccountNumberSuffix: '1234',
            deviceAccountIdentifier: '...',
            deviceAccountNumberSuffix: '5678',
            activationState: 'activated',
        },
    },
}
```

**Comment by marcoscaceres** [comment]
How about we let `PaymentRequestUpdateEvent` sprout `methodName` and `details` attributes - we can `null` the `details` by default, and adding the method name should be trivial. That would allow us to reuse the existing `updateWith()` machinery from #668, without needing to add a new interface.

**Comment by aestes** [comment]
@marcoscaceres 👍

**Comment by marcoscaceres** [comment]
WIP... not ready for review, but underway: https://github.com/w3c/payment-request/commit/d26aeed06906b9a52ef7a7b90a533b52028db3f8 

Need #674 in place first.

**Comment by mnoorenberghe** [comment]
> How about we let PaymentRequestUpdateEvent sprout methodName and details attributes - we can null the details by default, and adding the method name should be trivial.

I wonder if `details` would be confusingly generic if it's not used for other events. Perhaps `methodDetails` would make it's purpose more clear?

If you're intentionally leaving the name generic so it can be used from other change events in the future then the spec's description of `details` should make it clear that the details are about a payment method only when the event is a `paymentmethodchanged` and it's null otherwise.

**Comment by marcoscaceres** [comment]
My intention was to match the naming of [`PaymentResponse.details`](https://www.w3.org/TR/payment-request/#details-attribute).

**Comment by stpeter** [comment]
@marcoscaceres #674 seems to be in place so let us know when your PR is ready for review. :-)

**Comment by marcoscaceres** [comment]
So, as I'm spec'ing this out, I realized that it might be more consistent to put a nullable `paymentMethod` attribute on `PaymentRequest`. 

So:

```JS
partial interface PaymentRequest {
    readonly attribute PaymentMethod? paymentMethod;
    attribute EventHandler onpaymentmethodchanged;
};

interface PaymentMethod {
  readonly attribute USVString methodName;
  object details; // payment method specific
};
```

And so:

```js
request.onpaymentmethodchanged = ev => {
   const { paymentMethod } = ev.target;
   // recalculate based on either methodName and/or on the details
   const newTotal = recalculateCosts(paymentMethod);
   ev.updateWith({ total: newTotal });
}
```

**Comment by rsolomakhin** [comment]
Right, this sounds more consistent with the shipping address and shipping option events.

**Comment by ianbjacobs** [comment]
This topic was discussed at the 19 April FTF meeting:
https://www.w3.org/2018/04/19-wpwg-minutes.html#item04
