### ISSUE TITLE
Document privacy and security mitigations

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#675]
As part of the CR process and through implementation/deployment, we've learned quite a bit about abuse cases. We should make sure we properly document all mitigations we've put in place without being hand-wavy - in the Privacy and Security section. 

- [x]  use of SecureContext
- [x]  the `allowpaymentrequest` attribute on iframe 
- [x]  `canMakePayment()` and throttling
- [x]  requiring user action on `show()`
- [x] redacting address info #654

And so on... please add more to the above... those are just the ones off the top of my head. 

cc @lknik.

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

Want any help drafting text?

Ian

**Comment by marcoscaceres** [comment]
Help is always welcomed, @ianbjacobs.

**Comment by stpeter** [comment]
Both https://www.w3.org/TR/credential-management-1/ and https://www.w3.org/TR/encrypted-media/ have text we could emulate about secure contexts. The latter document especially has thorough sections on privacy and security.

**Comment by marcoscaceres** [comment]
Merged the ones listed, so closing.
