### ISSUE TITLE
Clarify addressLine definition

### ISSUE THREAD

**Issue by stpeter** [w3c/browser-payment-api#676]
(1) Would it be helpful to mention that in interface terms the `addressLine` data can be gathered in various ways (e.g., via a textarea element or multiple input elements)? The word "line" might make it sound as if there can be only one of them, whereas in the spec it's a FrozenArray and we might not want implementers to think they can have only one.

(2) In addition to the currently-mentioned constructs ("a street name, a house number, apartment number, a rural delivery route, descriptive instructions, or a post office box number") we might consider mentioning other common premise details like a suite or floor number, a building name, a department name, or a mail stop. Existing standardized address formats (e.g., OASIS xAL) have defined specialized fields for such constructs, but as far as I can see they can be included in `addressLine`.

**Comment by ianbjacobs** [comment]
Hi @stpeter,

In a previous discussion we observed that the recipient might include multiple lines, leading to this text in the specification: "This member may, under certain circumstances, contain multiline information. For example, it might contain "care of" information."

With that in mind, under 11.14 for [[addressLine]] would it address your comment (and be true) to add at the end "It may contain multiline information." ?

Ian

**Comment by stpeter** [comment]
@ianbjacobs Yes, that seems good. In practice multi-line input (whether via textarea or multiple input elements) seems quite likely. What threw me off (and might throw off implementers) is that the singular addressLine can contain multiple lines. But I suppose it's too late to change the name... ;-)

**Comment by ianbjacobs** [comment]
@marcoscaceres sound ok? Shall I do a PR? (or @stpeter)?

Ian

**Comment by marcoscaceres** [comment]
Wouldn't hurt to clarify things a bit more, so PR welcome.

**Comment by stpeter** [comment]
I'll chat with @marcoscaceres about this and then submit a PR.

**Comment by stpeter** [comment]
I'll chat with @marcoscaceres about this and then submit a PR.

**Comment by marcoscaceres** [comment]
@stpeter, I'd like to close this issue via with https://github.com/w3c/payment-request/pull/654 - could you please make any additional editorial clarifications on-top of that pull request? 

You should be able to do it either directly via the github interface, or clone repo and make changes directly on the "paymentaddress_constructor" branch.

**Comment by marcoscaceres** [comment]
closed via https://github.com/w3c/payment-request/pull/654

The PR adds a new model section, which hopefully makes things a little bit more clear with regards to addresses. @stpeter, if you still feel what is there is insufficient, we can reopen this.
