### ISSUE TITLE
Guidance on shipping options (mostly for devs)

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#680]
This doesn't affect the spec - it's mostly around best practice. 

Interesting question came up from @mnoorenberghe over in Mozilla's [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1432909): 

Should a merchant include the shipping option as a `displayItem` even though it's already included as a separate thing? The risk being that if it's included twice, the amounts might fall out of sync. 

@rsolomakhin states that merchants have been including the selected shipping option as a display item in a lot of cases. 

I personally don't think they should (as it's redundant, and in Firefox's UI, at least, we call out shipping clearly), but this might be different for other implementations. Thus, in Firefox, it might look weird if a vendor includes shipping as a display item, because we will also show it when we list everything being paid for: 

![screenshot 2018-02-06 20 49 05](https://user-images.githubusercontent.com/870154/35852502-2fcb3312-0b7f-11e8-8d72-825e2fcf4b36.png)

Thoughts?

**Comment by rsolomakhin** [comment]
@marcoscaceres: Do you think we can make it optional to duplicate the shipping option in the display items? If the selected shipping option is absent in the display items, then automatically add the selected shipping option to the display items. This would be for the purposes of browser UX only. The underlying data structures in the spec would not be affected.

**Comment by marcoscaceres** [comment]
> @marcoscaceres: Do you think we can make it optional to duplicate the shipping option in the display items? 

I guess it's already optional, right? That is, nothing prevents: 

```JS
const shipping = {
  id: "drone",
  label: "🚀 Drone Express (2 hours)",
  amount: { currency: "USD", value: "25.00" }
};

const details = {
  displayItems: [shipping],
  shippingOptions: [shipping]
}
```

> If the selected shipping option is absent in the display items, then automatically add the selected shipping option to the display items.

The problem is that there is no way to match them. That is, the `shipping` below are both passed by value, so there is no way currently for the payment sheet to know they the same thing:

```JS
// These shippings are the same here, but not the same to the the sheet!
const details = {
  displayItems: [shipping, toy], // These are PaymentItems
  shippingOptions: [shipping], // This is a PaymentShippingOption
};
```

>  This would be for the purposes of browser UX only. The underlying data structures in the spec would not be affected.

I guess one approach would be to set the "type" to "shipping" (and thus add adding a "shipping" type to the enum I proposed recently). 

```JS
{
  id: "drone",
  label: "🚀 Drone Express (2 hours)",
  amount: { currency: "USD", value: "25.00" }
  type: "shipping"
};
```

Alternatively, we can modify the API's `displayItems` sequence to accept both "PaymentItem" and `PaymentShippingOption`. Then, the payment sheet can look for the `id` member, which is what distinguishes shipping option from display items.

**Comment by domenic** [comment]
This seems really tough...

So given a situation where people are (as @rsolomakhin states) sending info like:

- Display items: shoes $100, shipping by drone $10
- Shipping options: by drone $10
- Total: $110

I don't see a world where you could usefully create a UI like Firefox's. It seems like you'd end up with

```
Shoes               $100
Shipping by drone   $10
------------------------
                    $110
Shipping            $10

              TOTAL $110
```

which is obviously quite confusing.

You could perhaps ask that everyone upgrade their code to include more information (e.g., include an id with every payment item/shipping option), so that Firefox could remove payment-items-that-are-actually-shipping-options from the list of items. But unless that's mandatory, you're in real trouble.

Is the goal to figure out a modification to the specification that would allow Firefox to dedupe, and hope that all sites using PaymentRequest upgrade to that? Or is to add guidance to the specification to ask developers to stop adding dupes?

(Side note: I guess it's already true that people can create confusing experiences in any browser by mismatching `total` with the sum of all the displayItems + shippingOptions + modifiers?)

**Comment by mnoorenberghe** [comment]
> Is the goal to figure out a modification to the specification that would allow Firefox to dedupe, and hope that all sites using PaymentRequest upgrade to that? Or is to add guidance to the specification to ask developers to stop adding dupes?

I would very much prefer the latter as it allows UAs to provide better UIs and reduces duplication on the part of authors.

**Comment by marcoscaceres** [comment]
@domenic, just want to be clear that Firefox would display the information in the manner below ("Shipping by drone" twice!), because shipping options have a label:


```
Shoes               $100
Shipping by drone   $10
------------------------
                    $110
Shipping by drone   $10

              TOTAL $110
```

So, ideally, with the exclusion of shipping as a display items, you would get the following:

```
Shoes               $100

------------------------

Shipping by drone   $10

              TOTAL $110
```

**Comment by domenic** [comment]
I mean, it depends on whether the developer enters the same label or not. If I were developing, I would probably put slightly different labels for a "display item" displayed alongside other items, vs. a "shipping option". Thus my above example.

**Comment by marcoscaceres** [comment]
Ok, thanks for the clarification. 

I think we are going to have differences of opinions here. But ultimately, we need to see what developers do. Just don't want to end up in a situation where devs conditionally add/remove display items based on browser detection. Feels like there is a slight risk of that happening.

**Comment by marcoscaceres** [comment]
Just a heads up that we (Firefox) are considering excluding the `displayItems` from the sheet entirely. We only show the total. We still validate the `details`, per spec... we just don't show them in the sheet anymore (not final design):   

<img width="627" alt="screenshot 2018-10-09 17 42 16" src="https://user-images.githubusercontent.com/870154/46710093-2b630000-cc92-11e8-997e-b691738ae200.png">

In any case, I this is probably better described in MDN.

**Comment by rsolomakhin** [comment]
Thank you for the heads up!

**Comment by aestes** [comment]
FWIW, Apple's [guidelines](https://developer.apple.com/design/human-interface-guidelines/apple-pay/architecture/payment/) for display items (i.e. line items) say to not "use line items to show an itemized list of products that make up the purchase."

We've been advising merchants to only include additional costs like tax, shipping, and discounts as line items. It sounds like this is different from what at least Firefox has in mind.

**Comment by marcoscaceres** [comment]
> We've been advising merchants to only include additional costs like tax, shipping, and discounts as line items. It sounds like this is different from what at least Firefox has in mind.

The above is definitely what we have in mind too (we agree with the guidelines). We show the cost of shipping when it's selected, so felt it was redundant to show it twice, like: 

<img width="518" alt="screenshot 2018-10-10 18 36 08" src="https://user-images.githubusercontent.com/870154/46842896-013d4980-ce1c-11e8-9003-0f8ce85ed069.png">

So we are hopeful that merchants are showing how tax and/or discount applied on the calling web page itself. We may need to check that assumption as we roll this out and work with merchants.
