### ISSUE TITLE
PaymentShippingOption as a subclass of DisplayItem

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#681]
Given the overlap, should we consider `PaymentShippingOption` inheriting from `PaymentItem` :

```Java
dictionary PaymentItem {
  required DOMString label;
  required PaymentCurrencyAmount amount;
  boolean pending = false;
};

dictionary PaymentShippingOption : PaymentItem {
  required DOMString id;
  boolean selected = false;
};
```

With `pending` being a somewhat meaningless member for `PaymentShippingOption`?

**Comment by domenic** [comment]
I don't think it's a good idea to use inheritance for overlap. Use inheritance for "is a". A shipping option is not a payment item, I don't think.

Instead just use similarly-named members in both cases.

**Comment by marcoscaceres** [comment]
> Use inheritance for "is a"
 
Agree, this was also how I was seeing them (kinda literally like that, as Firefox intends to display shipping option with other payment items). Basically, what lead me here was:
https://github.com/w3c/payment-request/issues/681

> Instead just use similarly-named members in both cases.
 
Yeah, this is also what I'm trying to ascertain. Can definitely live with them being separate and considered separate from an API perspective.

**Comment by marcoscaceres** [comment]
Sorry, meant #680 above.

**Comment by domenic** [comment]
Sorry for the delay.

Although I see the possible connection here, I think in the end the issue of "pending" clinches it. All payment items can potentially be pending. But payment shipping options cannot be pending, right? So I don't think they are payment items.

**Comment by mnoorenberghe** [comment]
I've seen various websites that give a shipping estimate and indicate that it is subject to change (and therefore is "pending") so to me pending makes just as much sense on a shipping option as on any other display item. IIRC I've seen Payment Request demos by Google that set `pending` to true when duplicating a shipping option (see #680) into the display items.

Personally I would rather shipping options weren't passed in the API with display items so I think the subclassing may add confusion but I don't think `pending` is a good reason to reject this idea.

**Comment by marcoscaceres** [comment]
Closing as my question was answered.
