### ISSUE TITLE
Add contact info / support URL to show() method?

### ISSUE THREAD

**Issue by stpeter** [w3c/browser-payment-api#687]
There is no method for the merchant to pass its contact information (e.g., a phone number) or a support URL (e.g., a live chat interface) to the payment sheet. This might leave the user without a clear way to get help from the merchant during the payment / checkout experience. 

At Mozilla we will probably add this to our list of user testing / user research topics, but has anyone (@zkoch @rsolomakhin perhaps) run into this with current implementations?

**Comment by rsolomakhin** [comment]
@stpeter : No merchants have requested this feature from us. Please do let us know the results of your user testing / user research.

**Comment by marcoscaceres** [comment]
@ianbjacobs, any chance you could reach out to some merchants to find out how they would handle this? Right now, this is just something we are wondering about.

**Comment by ianbjacobs** [comment]
@marcoscaceres, I will ask around.

Also adding @michelle, @asolove, and @lyverovski too. 

Meanwhile, here are 2 cents:

 * It is not clear to me that while in the sheet (owned by the browser) I would seek help from the merchant. It does make sense to me to have an easy way to get to browser documentation about the sheet. I might have questions like What is this thing? Where do I add cards or other data? 

 * As a user, I think I would be inclined to hit the "cancel" button and then find my way around the merchant site if I wanted help from the merchant.

Ian

**Comment by stpeter** [comment]
@ianbjacobs You might be more sophisticated than the typical user. ;-) No matter what, shoppers will be confused. Who will they call, what will they do? They have a payment sheet in front of them. It doesn't say how they can get help. They might cancel out of the whole thing, i.e., the dreaded SHOPPING CART ABANDONMENT. I'm really surprised that no one is worried about this. But we'll add it to the user research agenda on the Firefox team and see if we can gather some data...

**Comment by stpeter** [comment]
@ianbjacobs I guess we can close this for now, pending further feedback.

**Comment by ianbjacobs** [comment]
Up to you. I am fine with that.

**Comment by marcoscaceres** [comment]
Closing based on https://github.com/w3c/payment-request/issues/687#issuecomment-370003371
