### ISSUE TITLE
When "pay" happens, PaymentAddress request and response should match. 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#692]
[Elsewhere](https://bugzilla.mozilla.org/show_bug.cgi?id=1435155#c12), @hsivonen wrote: 

> While implementing redaction, I noticed that by spec, when redaction is not
> in use, when the request promise resolves, both the request and the response
> have the full address, but when redaction is in use, when the request
> promise resolves, only the response has the full address and the redacted
> address remains in the request. This seems like a footgun: Web developers
> who test with a browser that doesn't redact might, at the time of the
> request promise resolving, mistakenly pull the shipping address from the
> request object instead of the response object and it would work in browsers
> that don't redact and break in browsers that do redact.

**Comment by hsivonen** [comment]
LGTM. Thanks.

**Comment by marcoscaceres** [comment]
closed via https://github.com/w3c/payment-request/pull/654
