### ISSUE TITLE
Verifying the total

### ISSUE THREAD

**Issue by stpeter** [w3c/browser-payment-api#702]
The spec is unclear on this point: "It is the developer's responsibility to verify that the total amount is the sum of these items." 

Is it the responsibility of the merchant to verify these amounts before generating the PaymentDetails? 

Is it the responsibility of the browser to verify these amounts after receiving the PaymentDetails from the merchant?

**Comment by marcoscaceres** [comment]
> Is it the responsibility of the merchant to verify these amounts before generating the PaymentDetails?

Correct. 

> Is it the responsibility of the browser to verify these amounts after receiving the PaymentDetails from the merchant?

There is no expectation in the spec that the browser do any mathematical  calculations of any kind.

**Comment by stpeter** [comment]
Perhaps then it makes sense to say "It is the developer's responsibility to verify that the total amount is the sum of these items before generating the PaymentRequest."

**Comment by marcoscaceres** [comment]
Good suggestion, but I need to check the context, because "before generating" doesn't apply in all cases. Consider, the total can be updated by `.show()` and via `.updateWith()`.

**Comment by stpeter** [comment]
Yes, perhaps not "before generating" but "It is the developer's responsibility, when generating or updating the PaymentRequest, to verify that the total amount is the sum of these items."

**Comment by marcoscaceres** [comment]
@stpeter thanks for the suggestion - that makes it more clear. I'll add it.
