### ISSUE TITLE
UX Idea: Favicon in the sheet?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/browser-payment-api#707]
@marcoscaceres, @zkoch, @adrianba, @aestes,

At today's WPWG call [1] we discussed some of the perceived adoption challenges for payment request API. Among them is user unfamiliarity with the sheet. As @stpeter, put it, the "familiar milestones" about the merchant site are missing when one interacts with the sheet, and this
may be leading to users canceling.

Beyond displaying merchant origin, one idea was to show a favicon in a manner similar to tabs. Any thoughts on that idea?

Ian

[1] https://www.w3.org/2018/05/03-wpwg-minutes.html

**Comment by stpeter** [comment]
The good thing about a favicon is that it's accessible from a standard location and comes in standard sizes. Is it necessarily of a size that's desirable to merchants?

**Comment by domenic** [comment]
I'm very confused as to how this is a specification issue, and not a feature request for individual browsers best filed on their bug trackers.

**Comment by marcoscaceres** [comment]
Agree with @domenic. This seems like something browsers can compete on from a UX perspective. Like, Firefox could easily pull favicons from the document or from web manifest.

**Comment by ianbjacobs** [comment]
I agree this is not a spec question. If there is a better way to raise awareness on topics related to but not directly affected by the spec, please let me know. I'm happy to close this issue.

**Comment by stpeter** [comment]
Sure, a browser could pull in the favicon. Is that enough to overcome user skittishness with payment sheets that have no merchant branding? IMHO user testing/research needs to lead us in the direction of answers, so closing this for now might make sense.

**Comment by ianbjacobs** [comment]
Ok to close and look forward to hearing feedback if this idea is experimented with.
Ian

**Comment by marcoscaceres** [comment]
As @domenic stated, “feature request for individual browsers best filed on their bug trackers.” 

However, if there is actual (i.e., not perceived) data showing that there is significant abandonment over the status quo, and statistically significant data showing a direct correlation between presenting a favicon and significantly reduced abandonment, then we can have a discussion: What methodology was used, what sample size, who were the participants, etc. 

Without the data, we might be trying to fix a non issue or might be focusing on the wrong problem: people might be abandoning or cancelling payment requests for an infinite number of reasons. Browser’s ux teams, together with merchants, are in the best position to explore this. But as there are almost no websites using this API yet, it seems premature to be talking about this.

**Comment by stpeter** [comment]
This issue was triggered by early data (or at least anecdotes) provided by a WG participant on a call earlier today, based on a study they have underway. They can provide more details once their study is complete.

**Comment by marcoscaceres** [comment]
That’s really great to hear! I definitely agree we need to be researching and sharing data here, specially if it results in positive experiences for users.
