### ISSUE TITLE
Signaling payment handler details errors 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#727]
For example, the card might have expired. There might be insufficient digits, etc...

**Comment by ianbjacobs** [comment]
To say a bit more: suppose the merchant gets back some payment credentials and those credentials don't work for some reason. The merchant might want to prompt the user again, but "minus the unacceptable credentials". Such information would need to be passed to the payment handler as well.

**Comment by marcoscaceres** [comment]
The model in the spec is “the following things are erroneous: x, y, z.” But not “minus unacceptable”, which seems different to me.

**Comment by ianbjacobs** [comment]
I think there is a difference between:
 - Please correct this information, and
 - You can't use this, so the browser or payment handler should no longer present it as an option

Ian

**Comment by marcoscaceres** [comment]
> You can't use this, so the browser or payment handler should no longer present it as an option

I'm not in favor is this, tbh. Right now, everything maps to input fields.

**Comment by ianbjacobs** [comment]
We don't have this feature today and that has not been a show-stopper.

**Comment by marcoscaceres** [comment]
Paying for TPAC today...

<img width="576" alt="screenshot 2018-06-26 14 14 33" src="https://user-images.githubusercontent.com/870154/41939460-e23bab6a-7963-11e8-94d2-559242982529.png">

We can't do this today :)

**Comment by marcoscaceres** [comment]
This bug should probably move to the basic card spec.

**Comment by marcoscaceres** [comment]
Moved https://github.com/w3c/payment-method-basic-card/issues/57

**Comment by marcoscaceres** [comment]
Reopening, because this still needs infrastructure in this spec.
