### ISSUE TITLE
Always requiring CVV?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#730]
Right now, there is no way for a vendor to not ask for CVV? Sometimes it's not required. 

Should we do something there?

**Comment by marcoscaceres** [comment]
(maybe this is a basic card spec problem)

**Comment by ianbjacobs** [comment]
This is a general issue first raised by @mattsaxon:
 https://github.com/w3c/payment-request/issues/97

Matt then wrote a proposal:
  https://github.com/w3c/payment-request/pull/114

At some point it was suggested instead to be able (on a per payment method basis) to specify
fields you DO NOT want to get back. The primary use case cited was "I don't want the CVV; I am willing to accept the risk and prefer less friction in the user experience."

Each time we have discussed this, we have decided not to include it. 

Ian

**Comment by marcoscaceres** [comment]
Ah, yeah! thanks for the links.
