### ISSUE TITLE
Follow up on APA Comments on Web Payments FPWDs

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#735]
https://lists.w3.org/Archives/Public/public-apa/2016Aug/0086.html

**Comment by ianbjacobs** [comment]
Hi Marcos,

Please see issue #450 (now closed).

Ian

**Comment by marcoscaceres** [comment]
ah, I'm just on the phone with Janina Sajka, and we never emailed them back with #450 and that discussion.

**Comment by ianbjacobs** [comment]
@michael-n-cooper, @JaninaSajka,
cc: @plehegar 

Chatting with @marcoscaceres here at TPAC we have created a new pull request to address this issue that is both more specific and also accurately reflects implementations. Please review the pull request and let us know whether it satisfies the original APA review goals. Thank you,

https://github.com/w3c/payment-request/pull/802
