### ISSUE TITLE
bless() is racy with document.body

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#758]
I wonder if `bless()` should wait until there is actually a `document.body` (i.e., document.readyState is "compete")? Right now, I'm getting errors because "document.body is null" on tests.

**Comment by domenic** [comment]
What is `bless()`?

**Comment by marcoscaceres** [comment]
Oopps, wrong repo

**Comment by adrianhopebailie** [comment]
There should be more API's with a `bless` function!

**Comment by stpeter** [comment]
stpeter approves of this message :-)
