### ISSUE TITLE
Can PaymentMethodChangeEventInit really have a required member?

### ISSUE THREAD

**Issue by cdumez** [w3c/browser-payment-api#770]
Can PaymentMethodChangeEventInit really have a required member given that it is optional in the event constructor?

See:
https://w3c.github.io/payment-request/#dom-paymentmethodchangeeventinit
https://w3c.github.io/payment-request/#paymentmethodchangeevent-interface

**Comment by cdumez** [comment]
The *EventInit parameters are usually optional but AFAIK, none of them currently have required members. PaymentMethodChangeEventInit seems to be the exception.

Can this methodName member be optional?

**Comment by cdumez** [comment]
@marcoscaceres @aestes

**Comment by marcoscaceres** [comment]
@domenic, can you provide a bit of IDL guidance here? Do we make `eventInitDict` required or do we give the `methodName` member a default? Or something else entirely?

**Comment by domenic** [comment]
A default of `""` seems fine.
