### ISSUE TITLE
Extract actionable items from Shopify study

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#772]
The [Shopify study](https://shopifyengineering.myshopify.com/blogs/engineering/shaping-the-future-of-payments-in-the-browser ) contains at lot of actionable things for V2 (e.g., it's pretty clear we need to solve coupons, better merchant/sheet integration, etc.). 

It would be nice to go through the study with a fine-tooth comb and extract whatever actionable items we can. We have some of these already (e.g., coupon codes is #145), but there might be others we haven't filed bugs for.

**Comment by ianbjacobs** [comment]
@lyverovski and @Krystosterone, pinging you in case you have a clear picture of issues that you could raise on the spec in light of the experiment. 

Regarding usability of the sheet topics, some of those are being addressed (or at least discussed) in the visual identity task force. 
 https://github.com/w3c/webpayments/wiki/Web-Payments-API:-Brand-Analysis#useful-notes-on-connections-between-sheet-and-visual-identity

Ian

**Comment by ianbjacobs** [comment]
Closing this given our current emphasis on SPC.
