### ISSUE TITLE
Rename `PayerErrorFields` to be like `AddressErrors` and `BasicCardErrors`

### ISSUE THREAD

**Issue by mnoorenberghe** [w3c/browser-payment-api#782]
`AddressErrors` and `BasicCardErrors` both end in "Errors" but `PayerErrorFields` doesn't and I also find that name a bit confusing (should it have been `PayerFieldErrors`?). It would be nice to have consistency and rename to `PayerErrors` (or `PayerFieldErrors` if `PayerErrors` is too confusing).

**Comment by marcoscaceres** [comment]
This is kinda editorial. I don't mind fixing this - though it will mean IDL binding code in each browser will need a little updating.

**Comment by akansha2608** [comment]
Hi @marcos-travel @mnoorenberghe , i would like to work on it , can you please assigned this bug to me if its available :)

Thanks

**Comment by marcoscaceres** [comment]
@akansha2608, happy for you to work on it. It should be as simple as a find and replace. I think we want to go with `PayerErrors`.
