### ISSUE TITLE
test suite that checks whether shipping options can be updated

### ISSUE THREAD

**Issue by adimallikarjunareddy** [w3c/browser-payment-api#791]
Which test suite here https://w3c-test.org/payment-request/ checks for updating shipping options when any other events happen?

 Like address change should refresh the available shipping options and rates.

**Comment by marcoscaceres** [comment]
@adimallikarjunareddy, possibly:
https://w3c-test.org/payment-request/algorithms-manual.https.html#shipping-option-changed-algo

**Comment by marcoscaceres** [comment]
If the test is insufficient, we would be happy to add another... let us know! ... also, the spec links to tests directly ("see the little Tests box in each assertion"). For example:
https://w3c.github.io/payment-request/#onshippingoptionchange-attribute

**Comment by adimallikarjunareddy** [comment]
apologies if my question was not elaborate. I was just trying to see if we could have found the issue #778 through the test cases.

**Comment by marcoscaceres** [comment]
Moved to WPT - https://github.com/web-platform-tests/wpt/issues/14883
