### ISSUE TITLE
Make Basic Card Payment Method Spec an informative reference

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/browser-payment-api#798]
References to Basic Card are only used in examples and notes. Further, the Basic Card spec is a NOTE so can't be a normative reference.

**Comment by ianbjacobs** [comment]
Yes, please move to informative reference. Thanks!

**Comment by marcoscaceres** [comment]
Fixed 😸

**Comment by ianbjacobs** [comment]
WOW! marcos++
