### ISSUE TITLE
Meaning of canMakePayment()

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#800]
We discovered during testing that each implementation have slightly different definitions of "can make payment". During the F2F, we came to a consensus that "canMakePayment" means "the user agent supports the PMIs" - but it does not mean that there is a payment instrument set up. We concluded that we might add something to check if there is an active instrument in the future. I'll file a different bug for that.

**Comment by aestes** [comment]
For reference, WebKit changed its canMakePayment() implementation to match the consensus definition: https://trac.webkit.org/r237594.

**Comment by jenan-stripe** [comment]
+1 for consistency, but I'd be pretty worried if this lands before #801. The major wallet providers have active instrument checks, and if that's not landing soon with PaymentRequest, it's a much less compelling option for merchants.
