### ISSUE TITLE
Should we put `regionCode` attribute at risk? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#816]
In #690 we added `regionCode`... 

@aestes, @rsolomakhin, @zouhir, looks Chrome, Safari, and Edge don't expose the `regionCode` attribute. In Firefox, we implement it (just the IDL), but haven't mapped it to actual ISO3166-2 regions in the UI... thus, it just always returns `""`. 

For the purpose of CR, should we keep it in the spec or move it out?... or do any of you plan to implement it too sometime soon?

**Comment by rsolomakhin** [comment]
We **will** expose it in Chrome, just have not gotten to it yet. We have the internal plumbging all set for this.

**Comment by mnoorenberghe** [comment]
We also will expose it in Firefox. We're working on a dependency of that right now.

**Comment by marcoscaceres** [comment]
Ah, excellent. Thank you both!

**Comment by marcoscaceres** [comment]
Reopening, as Firefox remains the only browser supporting this (and support is limited to just returning the empty string... which is admittedly kinda useless). 

Fellow implementers, what say you? Are implementation plans still realistic to include `regionCode` in v1?

**Comment by ianbjacobs** [comment]
@aestes, @rsolomakhin, @zouhir I welcome your input on this question. Thank you!

**Comment by marcoscaceres** [comment]
just in case... https://github.com/w3c/payment-request/pull/823 ... let me know, as we will need to update WPT, and a bunch of docs.

**Comment by rsolomakhin** [comment]
We will implement this eventually. Hard to say the timeline.

**Comment by zouhir** [comment]
`Re: should we keep it in the spec or move it out?`
I would suspect some risk systems would be using an address with the `regionCode` as a vector in evaluating the trustworthiness of a transaction - if that's true or we have any data on that then I'd say we should keep it.

`Are implementation plans still realistic to include regionCode in v1?`
I unfortunatly can't comment on that yet.

**Comment by marcoscaceres** [comment]
Ok, it sounds like we should move it out and bring it back after we go to Proposed REC. @ianbjacobs should we start a CFC?

**Comment by ianbjacobs** [comment]
@marcoscaceres, I will work with the co-Chairs on the CFC. Thank you.
