### ISSUE TITLE
Receive payment api

### ISSUE THREAD

**Issue by johnmbokin** [w3c/browser-payment-api#831]
receive payment api isn't working why? Showing error site is down.  I am seeing this error while checking gap limit of xpub.

**Comment by marcoscaceres** [comment]
Hi @johnmbokin, this repository for a specification and not a website or any particular software. If you are experiencing issues with a website or a browser, please contact those parties instead.

**Comment by johnmbokin** [comment]
The Blockchain Receive Payments API is not creating a new btc address and i am not able to see my gap limit ?
