### ISSUE TITLE
Editorial: error is not well introduced

### ISSUE THREAD

**Issue by rvm4** [w3c/browser-payment-api#840]
The description of "error" in 6.3 is not very clear. Though, it is given greater clarity later on. Is it accurate to describe this as a global error message or a fallback error message when a more specific error field is not appropriate?

**Comment by marcoscaceres** [comment]
> Is it accurate to describe this as a global error message or a fallback error message when a more specific error field is not appropriate?

This was a bit of a design flaw... the `error` member there is specific for when when there is no valid shipping address. So maybe it should read (flipping what is there): 

> A human-readable string used to explain why goods cannot be shipped to the chosen shipping address, or any other reason why no shipping options are available.

**Comment by marcoscaceres** [comment]
Sent: https://github.com/w3c/payment-request/pull/845
