### ISSUE TITLE
Move PaymentAddress string defaults to AddressInit 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#853]
Right now, we do a lot of "set <var>address</var>.[[slot]] to the empty string" in prose. We should just move all that  prose logic to `AddressInit` by setting each member to default to `""` and `= []` for any sequence type. 

This shouldn't have any impact on developers, as the behavior we get is identical. However, it does significantly simplify implementation (as the binding layer can handle all of the above).

**Comment by marcoscaceres** [comment]
Setting as 1.1 target. CC @rsolomakhin, @aestes , @danyao, wdty?

**Comment by rsolomakhin** [comment]
> This shouldn't have any impact on developers, ... significantly simplify implementation

Sign me up!

**Comment by marcoscaceres** [comment]
I’ll put together a PR so you can see the changes. We can go from there.

**Comment by marcoscaceres** [comment]
Put up https://github.com/w3c/payment-request/pull/852
