### ISSUE TITLE
[[waitForUpdate]] must be set to true always after dispatch.

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#854]
Elsewhere, @danyao wrote: 

> From my reading of the spec, [[waitForUpdate]] is only set to true after updateWith() is called. Am I missing something?

Yes, indeed a small spec bug. Will send a patch.

**Comment by danyao** [comment]
Hi @marcoscaceres! I noticed that the [payer detail change algorithm](https://w3c.github.io/payment-request/#payer-detail-changed-algorithm) also fires a `PaymentRequestUpdateEvent`. But in this case, the algorithm doesn't set `[[waitForUpdate]]` to true immediately after event dispatching. Should we make it align with the other cases?

**Comment by marcoscaceres** [comment]
Yeah, well spotted. I'll draft a PR for the spec. We'll need to check if we have a test for that - but it should be easy to test.
