### ISSUE TITLE
PaymentRequest constructor throws in Safari but not Chrome on localhost

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/browser-payment-api#867]
When creating a new PaymentRequest in Safari the constructor throws with an ApplePay specific error.

This is in contrast to Chrome which allows the use of PR API on localhost.

**Comment by ianbjacobs** [comment]
cc @aestes

**Comment by rsolomakhin** [comment]
What's the error message? If it's localhost-related, perhaps Safari has a flag that allows development on that platform?

**Comment by marcoscaceres** [comment]
Maybe has something to do with WebKit’s definition of “secure context”. But I’m not sure? Was there some error message?

**Comment by adrianhopebailie** [comment]
code: 18
message: Trying to start an Apple Pay session from an insecure document.

**Comment by rsolomakhin** [comment]
By the way, you can use https://ngrok.com/ for testing on localhost but with HTTPS.

**Comment by adrianhopebailie** [comment]
> By the way, you can use ngrok.com for testing on localhost but with HTTPS

Yeh, have also used localtunnel but meh... localhost is just so EASY

**Comment by marcoscaceres** [comment]
SoOOooo... I'm going to close this as this is not really a spec bug.
