### ISSUE TITLE
show() should consume user activation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#886]
@aestes, @danyao, @rsolomakhin, moving discussion from #885. 

HTML has a new activation model. Right now, we presumedly have "transient" activation for `show()`:

```JS
window.onclick = () => {
   // set up payment stuff...
   const pay = request.show();
   // Does this succeed or reject? i.e., did .show() "consume" the user activation.
   document.body.requestFullscreen();
}
```

Presumedly, because of the modal nature of `.show()` we want to "consume" the activation, so that things like `requestFullscreen()` would fail if called immediately after `.show()`.

**Comment by rsolomakhin** [comment]
@jdtoupin Do you have a product opinion here? My vote is to consume user activation, so a click can trigger only one powerful feature. Consuming would also make click-jacking more difficult. 

EDIT: The right @jdtoupin

**Comment by jdtoupin** [comment]
Yes, consuming user activation makes sense to me.

**Comment by marcoscaceres** [comment]
Ok, makes sense to me too. 

As long as it's ok with @aestes (and we are not breaking anything with ApplePay... which I don't imagine we are), then I'll send a PR to add this and also update Firefox's implementation to match.

**Comment by marcoscaceres** [comment]
Sorry, I misread... REPORTING is indeed gone from the upstream.

**Comment by marcoscaceres** [comment]
(ignore that last message... wrong browser window... I hate browsers)

**Comment by marcoscaceres** [comment]
@aestes, when possible, please let me know if the above is ok 🙏.
