### ISSUE TITLE
Payment Method Basic Card spec uses various Payment Request definitions that Payment Request does not yet export

### ISSUE THREAD

**Issue by janiceshiu** [w3c/browser-payment-api#890]
The payment method basic card spec has many `data-cite` attributes that link to various definitions in payment request. However, those definitions are not yet exported to xref. Could we export this to xref so that basic card can use xref for linking? Thanks! 

1. [Payment Request Options](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L299-L301)
2. [Payment Request Creating a Payment Address from user-provided input](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L311-L312)
3. [Payment Request Payment Method Changed Algorithm](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L423-L424)
4. [Payment Request serialized method data](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L466)
5. [Payment Request serialised modifier data](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L552)
6. [Payment Request Details](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L588-L589)
7. [Payment Request Payment Details Base Modifiers](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L589-L591)
8. [Payment Request Payment Details Modifier Total](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L593-L595)
9. [Payment Request Payment Details Modifier Additional Display Items](https://github.com/w3c/payment-method-basic-card/blob/df6b49d757bdae56fb5197a40085cc53ddfcd95e/index.html#L597-L600)

**Comment by janiceshiu** [comment]
updated issue to list all missing exported definitions

**Comment by danyao** [comment]
Hi @janiceshiu Thanks for the contribution. Are you looking for a review or still working on this patch?

**Comment by janiceshiu** [comment]
Hi @danyao! I'd first like to check with payment request spec maintainers that those terms are okay to export to be used by other specs. If it is okay, I can submit a PR that adds the relevant `data-export=""` attributes. If there is a better way to go about this, please let me know. Thanks!

**Comment by danyao** [comment]
Ah got it. Thanks for the context!

I think it's fine to export the list you proposed.
