### ISSUE TITLE
ISP managed "micropayments" as alternative to advertisement based funding for web content creators.

### ISSUE THREAD

**Issue by keenla** [w3c/browser-payment-api#893]
Very early thoughts of letting Internet Service Providers to "manage financial support transfer from users to creators of intellectual content" (web page/site creation/managing; audio, video, news, blogs, art, …), giving creators a chance to provide alternative page  version of clean ad free content and helping them compensate service costs.

Reasons: as we all know, irrelevant ads are annoying, but sadly most easiest way to compensate costs; 
people are lazy - registering on countless sites and going through/setting up banking transfers for each is time consuming(or more commonly: users preferring to visit sites just as guest), and it increases risks for spam postings;
very often messages "please help us by donation" are dismissed only because its too lengthy(!!) to click through the donation payment chain for tiny transfer.

How it could look like in real life: 
browsing in "ad supported or adfree mode" in Chrome/Firefox/…; (adfree= micropayment transfer, not adblock)
links with price tag (example : 0.01(maybe?) cents per page view for Wikipedia or online forums/blogs/… just to show support, (there's possible misuse: creation of more "dilute" pages);
0.01$…1$ per daily news articles without registering as client; …1$…10$… per downloads of programs or music albums or streaming HQ movies or other digital arts
"tip box" - leave a cent or more for videos on Youtube(and similar) as a message: "Keep up good work!" with no more than 2…3 mouse clicks.
Main goal is small-payment method, that allows transfers to be completed within few seconds, and to give even the most cheapest online stuff chance to create considerable profit from amount of paying clients, not price.

**Comment by ianbjacobs** [comment]
Hi @keenla,

Thanks for writing to the group. I am going to close this issue because it does not bear directly on Payment Request.

I recommend checking out the Interledger Community Group:
 https://www.w3.org/community/interledger/

As well as the Web Monetization specification: 
 https://interledger.org/rfcs/0028-web-monetization/

Ian
