### ISSUE TITLE
the user interface's language should not be derived from `the body element`

### ISSUE THREAD

**Issue by janiceshiu** [w3c/browser-payment-api#895]
From the payment request spec, 
https://github.com/w3c/payment-request/blob/fe208dba28724d0a316bf706fbf39cc4414bd8f2/index.html#L1094-L1097
[The body element](https://html.spec.whatwg.org/multipage/dom.html#the-body-element-2)'s definition states "The body element of a document is the first of the html element's children that is either a body element or a frameset element, or null if there is no such element."

Thus,
* `<body>` is a node can can have a language
* `<frameset>` is a node
* `null` is not a node and cannot have a language.

In [this PR](https://github.com/whatwg/html/pull/5228), @annevk states
> I'm not sure I support the use case. Other APIs, e.g., the notification API, have no such defaulting and have explicit support for language annotation. And especially for the frameset case it seems that it's highly likely it might not match the language of the application anyway.

Thus, the user interface's language should not be derived from "the body element". The spec could probably include explicit support for language annotation the way the [notification API does it](https://notifications.spec.whatwg.org/#language).

cc @marcoscaceres

**Comment by marcoscaceres** [comment]
Agree, we should drop this requirement as I don't think anyone implements this. It should just be noted that, by default, payment sheet will use the browser's default language.   

In future version of the spec, we should add `{dir: "", lang: ""}` members to either the `PaymentDetailsInit` or to individual `PaymentItem`s. Not sure yet what the right level of granularity should be. I think we discussed something similar a few years ago... we should do some archeology.

**Comment by marcoscaceres** [comment]
Dug up: 
- https://github.com/w3c/payment-request/issues/650
- https://github.com/w3c/payment-request/issues/327

**Comment by marcoscaceres** [comment]
Sent PR: https://github.com/w3c/payment-request/pull/896
