### ISSUE TITLE
Expected behaviours: paymentmethodchange event updates with a rejection

### ISSUE THREAD

**Issue by maxlgu** [w3c/browser-payment-api#898]
What's the expected behaviours should be if the paymentmethodchange event updates with a rejection? The following snippet demonstrates this scenario:

`request.addEventListener('paymentmethodchange', (event) => {
    event.updateWith(Promise.reject('Error for test'));
  });`

**Comment by maxlgu** [comment]
CC @rsolomakhin

**Comment by rsolomakhin** [comment]
According to the ancient sacred texts (https://rsolomakhin.github.io/pr/ko/reject-update/):

> When the merchant request shipping, but responds to shipping address change by rejecting the update promise, which should cancel payment request.

Let's do the same for payment method change event.

**Comment by maxlgu** [comment]
I guess that mean the PH UI should be closed as well?

**Comment by rsolomakhin** [comment]
@maxlgu 

> I guess that mean the PH UI should be closed as well?

Yes, cancelling the payment request should close the PH UI.

**Comment by marcoscaceres** [comment]
@rsolomakhin, so this is not covered in the spec?

**Comment by marcoscaceres** [comment]
Reading [update a PaymentRequest's details algorithm](https://w3c.github.io/payment-request/#dfn-update-a-paymentrequest-s-details-algorithm) ... I think we are ok here. 

> Upon rejection of detailsPromise:
> [Abort the update](https://w3c.github.io/payment-request/#dfn-abort-the-update) with request and an "AbortError" DOMException.

Which:

> "Abort the current user interaction and close down any remaining user interface."

**Comment by marcoscaceres** [comment]
Ok, cool.. closing. @maxlgu does the above make sense? Or did we miss something?

**Comment by maxlgu** [comment]
That answers my question. Thanks!
