### ISSUE TITLE
Fix typo in code sample.

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#907]
The code sample at https://w3c.github.io/payment-request/#example-6-constructing-a-paymentrequest has a `request.retry()` statement, but the `retry()` method is defined on the `PaymentResponse` object. So the code sample should replace `request.retry()` with `response.retry()`. Thank you, @agektmr, for pointing this out!

**Comment by marcoscaceres** [comment]
Spec is ruined.
