### ISSUE TITLE
Payment sheet open in new tab when internet connection disconnect

### ISSUE THREAD

**Issue by ankushsapkal** [w3c/browser-payment-api#923]
I have implemented W3c payment method.
but We are facing on issue.
- Scenario
1) Open payment sheet and disconnect internet connection 
2) Click on continue button and check behavior.
you will get error message and close button 
3) now connect internet connection back
4) click on close button you will get new  tab .
after that no any action happen on this.

Can you please help me why exactly happen this and how to handle new tab .

Thanks,
Ankush sapkal

**Comment by ianbjacobs** [comment]
Hi @ankushsapkal,

What browser are you using?
cc @rsolomakhin, @danyao

**Comment by ankushsapkal** [comment]
Chrome browser ( supprted browser)

**Comment by rsolomakhin** [comment]
Thank you for reaching out! This sounds like a bug report and we'd like more information, so I've filed https://crbug.com/1123271 for this. Could we please continue the discussion there? It should be OK to close this issue, since it's not about the specification.

**Comment by ankushsapkal** [comment]
I already mentioned specifications . This issue is occurring on chrome browser it means support browser only. I tried with non supported browser but there is not occuring this issue no supported browser Firefox and Safari.

**Comment by ankushsapkal** [comment]
I am not able to debug payment sheet on chrome browser that's why we didn't find solutions on chrome

**Comment by rsolomakhin** [comment]
Thank you for the update! I've asked some extra follow up questions on https://crbug.com/1123271, which is a Chrome-specific bug tracker. Could you please respond at  https://crbug.com/1123271?
