### ISSUE TITLE
Proposal: drop `allowpaymentrequest` attribute

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#925]
Current state of things:

 * Only Chrome implements and ships `allowpaymentrequest`. Safari never implemented it, and Firefox never shipped it outside of Nightly. Payment Request has been disabled for 2+ years in Firefox, and seems unlikely to ship as Mozilla lacks a backing Payment Handler implementation. Work on implementing Payment Handler was [put on hold](https://www.mail-archive.com/dev-platform@lists.mozilla.org/msg29298.html). 
 * Permissions Policy spec defines "payment", allowing the `allow=` to explicitly override `allowpaymentrequest`. 
 * In Chrome, the `allowpaymentrequest` attribute is not implemented per spec, leading to some WPT failures.   

As such, I'm wondering if it might be prudent to remove `allowpaymentrequest` from HTML (and from Permission Policy and from Payment Request).  

If we agree, we would need to update:
 
 * html
 * Permission Policy spec
 * The Payment Request API spec. 

CC @danyao @rsolomakhin @adrianhopebailie

**Comment by danyao** [comment]
+1

**Comment by ianbjacobs** [comment]
+1

**Comment by danyao** [comment]
Filed Chrome tracking bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1127988
