### ISSUE TITLE
ISO 3166 typo

### ISSUE THREAD

**Issue by aphillips** [w3c/browser-payment-api#940]
https://www.w3.org/TR/2020/CR-payment-request-20201203/#dependencies

The dependency on ISO 3166 is misspelled as ISO 3366 (I assume you don't want a standard for coated abrasives??)

**Comment by ianbjacobs** [comment]
Hi @aphillips,

Thanks for catching this. I'll share the bad news with the Coated Abrasives CG.

Ian

**Comment by aphillips** [comment]
@ianbjacobs No worries. I18N's review will be wrapped up shortly--plenty for us to discuss in there. You might wish for some coated abrasives at that point....😛
