### ISSUE TITLE
ISO 4217 note commentary

### ISSUE THREAD

**Issue by aphillips** [w3c/browser-payment-api#949]
5. PaymentCurrencyAmount dictionary 
https://www.w3.org/TR/2020/CR-payment-request-20201203/#paymentcurrencyamount-dictionary

> Efforts are underway at ISO to account for digital currencies, which may result in an update to the [ISO4217] registry or an entirely new registry. The community expects this will resolve ambiguities that have crept in through the use of non-standard 3-letter codes; for example, does "BTC" refer to Bitcoin or to a future Bhutan currency? At the time of publication, it remains unclear what form this evolution will take, or even the time frame in which the work will be completed. The W3C Web Payments Working Group is liaising with ISO so that, in the future, revisions to this specification remain compatible with relevant ISO registries. 

I18N discussed this in our teleconference of 2021-03-25. Generally, we think that Web Payments's liaison with 4217's RA is the right course of action. The only callout here is that this note might encourage implementers to consider non-standard/private-use "de facto" currency codes in the interim (before non-governmental currencies get addressed) where this might harm interoperability vs. having a solid standard.

**Comment by ianbjacobs** [comment]
Hi @aphillips,

@marcoscaceres and I feel the specification here is not encouraging any particular behavior, only citing the problem. 

Is there a concrete change you would suggest? Thank you,
Ian

**Comment by aphillips** [comment]
I suppose I could suggest that some text be added discouraging implementers from "going off the ranch" and implementing non-standard workarounds... but I think that's probably overkill. I think you can resolve this comment.

**Comment by ianbjacobs** [comment]
Thanks @aphillips!

**Comment by ianbjacobs** [comment]
@aphillips or @r12a, do I remove the "i18n-needs-resolution" label or do you do that (based on Addison's response earlier today)?

**Comment by aphillips** [comment]
No, do not remove the label: PLH's tools use it to track resolution (and so do we). You can otherwise treat this as a normal issue (closing it when done, for example). See: https://www.w3.org/Guide/documentreview/#working_with_horizontal_review_labels

We track your progress in our repo (in this case, in i18n-activity#1045) and will resolve our issue. When you reach CR, if all of our issues are closed you'll have a clean bill of health. If any of our issues are open at that time which you feel are resolved, please do ping.

Thanks!!

**Comment by marcoscaceres** [comment]
closing as resolved.
