### ISSUE TITLE
Non-US examples

### ISSUE THREAD

**Issue by aphillips** [w3c/browser-payment-api#950]
(general)
https://www.w3.org/TR/2020/CR-payment-request-20201203

The examples in the spec use USD consistently as the currency and are otherwise somewhat USA-centric. All of the example text is in English (e.g. `Card processing fee`). While using English as a lingua franca promotes clarity and understanding, it is a good idea to be more inclusive in the examples.

As an aside, there are many non-credit card payment systems/payment methods that are non-US in nature that may be useful as examples as well.

(Note: this may have been addressed by #943)

**Comment by ianbjacobs** [comment]
@aphillips, you are correct that #943 attempts to address this; please let us know if that closes this issue. Thanks!
Ian

**Comment by marcoscaceres** [comment]
closed via 93767b767d711e99c5de11f1d230d4e55d58092c
