### ISSUE TITLE
Localizability of errors

### ISSUE THREAD

**Issue by aphillips** [w3c/browser-payment-api#951]
6.3 PaymentDetailsUpdate dictionary 
https://www.w3.org/TR/2020/CR-payment-request-20201203/#paymentdetailsupdate-dictionary

>  error member
>    A human-readable string that explains why goods cannot be shipped to the chosen shipping address, or any other reason why no shipping options are available. When the payment request is updated using updateWith(), the PaymentDetailsUpdate can contain a message in the error member that will be displayed to the user if the PaymentDetailsUpdate indicates that there are no valid shippingOptions (and the PaymentRequest was constructed with the requestShipping option set to true). 

There appears to be no language/direction metadata associated with this error message, nor a way to localize the message.

(also found in various places in the spec wherever DOMString `error` appears, for example [here](https://www.w3.org/TR/2020/CR-payment-request-20201203/#paymentvalidationerrors-dictionary))

This is a specific example of (and thus related to) #946 and #948

**Comment by marcoscaceres** [comment]
Based on https://github.com/w3c/payment-request/pull/956, leaving this open to address in a future version of the spec. 

@aphillips, for our records, could you please indicate if i18n is satisfied with this course of action? - and if so, remove the "i18n-needs-resolution" label. 

Please add any other labels the i18n WG needs to track this going forward.

**Comment by r12a** [comment]
(Just a process point: We don't ever remove the -needs-resolution labels.  The transition looks for tracker issues in the i18n WG repo that are still open and have -needs-resolution labels.  So the normal process just involves closing the issue (both here and in the i18n tracking repo) when resolved.  This btw enables us to easily see which issues were raised by the i18n WG, even after closure. We also apply labels to our tracker db (and not usually yours), as we close an item, to indicate that we need to ressurect the comment for the next version of the spec. hth )

**Comment by marcoscaceres** [comment]
Thanks @r12a for clarifying. We were a bit unsure.

**Comment by r12a** [comment]
@marcoscaceres here's the place to find guidance on that: https://www.w3.org/Guide/documentreview/#working_with_horizontal_review_labels

That page is linked from The Guide under 'Wide Review', and is the place you should start when you want any information about how wide/horizontal reviews are done.  We tried to consolidate all the WG-related guidance we could find into that one page, or link to it from that page.

**Comment by marcoscaceres** [comment]
Thanks @r12a! I wasn't aware of that document. That's super helpful.

**Comment by ianbjacobs** [comment]
@aphillips, with the adoption of #971, do you remove the needs resolution label?
