### ISSUE TITLE
Remove "standardized payment method identifier" content

### ISSUE THREAD

**Issue by maxlgu** [w3c/browser-payment-api#965]
This passage is outdated because basic-card has been deprecated.

"Each standardized payment method identifier defines its own unique IDL dictionary for use with the details attribute. The shape of this data (i.e., its members and their corresponding types and formats) differs depending on which standardized payment method identifier is selected by the end user."

**Comment by maxlgu** [comment]
@rsolomakhin

**Comment by ianbjacobs** [comment]
I note that SPC is currently implemented as a standardized payment method, so the passage may not yet be outdated.

**Comment by rsolomakhin** [comment]
@ianbjacobs is correct. Let's keep this paragraph.
